/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateTagDto,
  ListTagsParams,
  TagDto,
  UpdateTagDto
} from '.././model';





export const createTag = (
    createTagDto: CreateTagDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TagDto>> => {
    
    
    return axios.default.post(
      `/tag`,
      createTagDto,options
    );
  }



export const getCreateTagMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTag>>, TError,{data: CreateTagDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createTag>>, TError,{data: CreateTagDto}, TContext> => {

const mutationKey = ['createTag'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTag>>, {data: CreateTagDto}> = (props) => {
          const {data} = props ?? {};

          return  createTag(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateTagMutationResult = NonNullable<Awaited<ReturnType<typeof createTag>>>
    export type CreateTagMutationBody = CreateTagDto
    export type CreateTagMutationError = AxiosError<unknown>

    export const useCreateTag = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTag>>, TError,{data: CreateTagDto}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createTag>>,
        TError,
        {data: CreateTagDto},
        TContext
      > => {

      const mutationOptions = getCreateTagMutationOptions(options);

      return useMutation(mutationOptions);
    }
    export const listTags = (
    params: ListTagsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TagDto[]>> => {
    
    
    return axios.default.get(
      `/tag`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getListTagsQueryKey = (params?: ListTagsParams,) => {
    return [
    `/tag`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListTagsQueryOptions = <TData = Awaited<ReturnType<typeof listTags>>, TError = AxiosError<unknown>>(params: ListTagsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listTags>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListTagsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listTags>>> = ({ signal }) => listTags(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listTags>>, TError, TData> & { queryKey: QueryKey }
}

export type ListTagsQueryResult = NonNullable<Awaited<ReturnType<typeof listTags>>>
export type ListTagsQueryError = AxiosError<unknown>



export function useListTags<TData = Awaited<ReturnType<typeof listTags>>, TError = AxiosError<unknown>>(
 params: ListTagsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listTags>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListTagsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getTag = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TagDto>> => {
    
    
    return axios.default.get(
      `/tag/${id}`,options
    );
  }




export const getGetTagQueryKey = (id?: number,) => {
    return [
    `/tag/${id}`
    ] as const;
    }

    
export const getGetTagQueryOptions = <TData = Awaited<ReturnType<typeof getTag>>, TError = AxiosError<unknown>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTag>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTagQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTag>>> = ({ signal }) => getTag(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTag>>, TError, TData> & { queryKey: QueryKey }
}

export type GetTagQueryResult = NonNullable<Awaited<ReturnType<typeof getTag>>>
export type GetTagQueryError = AxiosError<unknown>



export function useGetTag<TData = Awaited<ReturnType<typeof getTag>>, TError = AxiosError<unknown>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTag>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetTagQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const updateTag = (
    id: number,
    updateTagDto: UpdateTagDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TagDto>> => {
    
    
    return axios.default.patch(
      `/tag/${id}`,
      updateTagDto,options
    );
  }



export const getUpdateTagMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTag>>, TError,{id: number;data: UpdateTagDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateTag>>, TError,{id: number;data: UpdateTagDto}, TContext> => {

const mutationKey = ['updateTag'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTag>>, {id: number;data: UpdateTagDto}> = (props) => {
          const {id,data} = props ?? {};

          return  updateTag(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateTagMutationResult = NonNullable<Awaited<ReturnType<typeof updateTag>>>
    export type UpdateTagMutationBody = UpdateTagDto
    export type UpdateTagMutationError = AxiosError<unknown>

    export const useUpdateTag = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTag>>, TError,{id: number;data: UpdateTagDto}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateTag>>,
        TError,
        {id: number;data: UpdateTagDto},
        TContext
      > => {

      const mutationOptions = getUpdateTagMutationOptions(options);

      return useMutation(mutationOptions);
    }
    export const deleteTag = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TagDto>> => {
    
    
    return axios.default.delete(
      `/tag/${id}`,options
    );
  }



export const getDeleteTagMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTag>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteTag>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteTag'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTag>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteTag(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteTagMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTag>>>
    
    export type DeleteTagMutationError = AxiosError<unknown>

    export const useDeleteTag = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTag>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteTag>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteTagMutationOptions(options);

      return useMutation(mutationOptions);
    }
    