/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */
import { faker } from "@faker-js/faker"
import type { RequestHandlerOptions } from "msw"
import { HttpResponse, http } from "msw"

import type { WorkspaceStatusDto } from "../model"

export const getCreateWorkspaceStatusResponseMock = (
	overrideResponse: Partial<Extract<WorkspaceStatusDto, object>> = {},
): WorkspaceStatusDto => ({
	id: faker.number.float({ fractionDigits: 2 }),
	name: faker.string.alpha({ length: { min: 10, max: 20 } }),
	color: faker.string.alpha({ length: { min: 10, max: 20 } }),
	statusType: faker.string.alpha({ length: { min: 10, max: 20 } }),
	workspaceId: faker.number.float({ fractionDigits: 2 }),
	...overrideResponse,
})

export const getListWorkspaceStatusesResponseMock = (): WorkspaceStatusDto[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		id: faker.number.float({ fractionDigits: 2 }),
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		color: faker.string.alpha({ length: { min: 10, max: 20 } }),
		statusType: faker.string.alpha({ length: { min: 10, max: 20 } }),
		workspaceId: faker.number.float({ fractionDigits: 2 }),
	}))

export const getGetWorkspaceStatusResponseMock = (
	overrideResponse: Partial<Extract<WorkspaceStatusDto, object>> = {},
): WorkspaceStatusDto => ({
	id: faker.number.float({ fractionDigits: 2 }),
	name: faker.string.alpha({ length: { min: 10, max: 20 } }),
	color: faker.string.alpha({ length: { min: 10, max: 20 } }),
	statusType: faker.string.alpha({ length: { min: 10, max: 20 } }),
	workspaceId: faker.number.float({ fractionDigits: 2 }),
	...overrideResponse,
})

export const getUpdateWorkspaceStatusResponseMock = (
	overrideResponse: Partial<Extract<WorkspaceStatusDto, object>> = {},
): WorkspaceStatusDto => ({
	id: faker.number.float({ fractionDigits: 2 }),
	name: faker.string.alpha({ length: { min: 10, max: 20 } }),
	color: faker.string.alpha({ length: { min: 10, max: 20 } }),
	statusType: faker.string.alpha({ length: { min: 10, max: 20 } }),
	workspaceId: faker.number.float({ fractionDigits: 2 }),
	...overrideResponse,
})

export const getDeleteWorkspaceStatusResponseMock = (
	overrideResponse: Partial<Extract<WorkspaceStatusDto, object>> = {},
): WorkspaceStatusDto => ({
	id: faker.number.float({ fractionDigits: 2 }),
	name: faker.string.alpha({ length: { min: 10, max: 20 } }),
	color: faker.string.alpha({ length: { min: 10, max: 20 } }),
	statusType: faker.string.alpha({ length: { min: 10, max: 20 } }),
	workspaceId: faker.number.float({ fractionDigits: 2 }),
	...overrideResponse,
})

export const getCreateWorkspaceStatusMockHandler = (
	overrideResponse?:
		| WorkspaceStatusDto
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<WorkspaceStatusDto> | WorkspaceStatusDto),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/workspace-status",
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getCreateWorkspaceStatusResponseMock(),
				{ status: 201 },
			)
		},
		options,
	)
}

export const getListWorkspaceStatusesMockHandler = (
	overrideResponse?:
		| WorkspaceStatusDto[]
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<WorkspaceStatusDto[]> | WorkspaceStatusDto[]),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/workspace-status",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getListWorkspaceStatusesResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getGetWorkspaceStatusMockHandler = (
	overrideResponse?:
		| WorkspaceStatusDto
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<WorkspaceStatusDto> | WorkspaceStatusDto),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/workspace-status/:id",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getGetWorkspaceStatusResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getUpdateWorkspaceStatusMockHandler = (
	overrideResponse?:
		| WorkspaceStatusDto
		| ((
				info: Parameters<Parameters<typeof http.patch>[1]>[0],
		  ) => Promise<WorkspaceStatusDto> | WorkspaceStatusDto),
	options?: RequestHandlerOptions,
) => {
	return http.patch(
		"*/workspace-status/:id",
		async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getUpdateWorkspaceStatusResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getDeleteWorkspaceStatusMockHandler = (
	overrideResponse?:
		| WorkspaceStatusDto
		| ((
				info: Parameters<Parameters<typeof http.delete>[1]>[0],
		  ) => Promise<WorkspaceStatusDto> | WorkspaceStatusDto),
	options?: RequestHandlerOptions,
) => {
	return http.delete(
		"*/workspace-status/:id",
		async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getDeleteWorkspaceStatusResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}
export const getWorkspaceStatusMock = () => [
	getCreateWorkspaceStatusMockHandler(),
	getListWorkspaceStatusesMockHandler(),
	getGetWorkspaceStatusMockHandler(),
	getUpdateWorkspaceStatusMockHandler(),
	getDeleteWorkspaceStatusMockHandler(),
]
