/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query"
import { useMutation, useQuery } from "@tanstack/react-query"
import { sendRequest } from "../../axios"
import type {
	CreateTaskDto,
	DeleteTaskPathParameters,
	GetTaskPathParameters,
	ListTasksParams,
	TaskDto,
	TaskWithWorkspaceDto,
	UpdateTaskDto,
	UpdateTaskPathParameters,
} from "../model"

export const createTask = (
	createTaskDto: CreateTaskDto,
	signal?: AbortSignal,
) => {
	return sendRequest<TaskWithWorkspaceDto>({
		url: `/task`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: createTaskDto,
		signal,
	})
}

export const getCreateTaskMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof createTask>>,
		TError,
		{ data: CreateTaskDto },
		TContext
	>
}): UseMutationOptions<
	Awaited<ReturnType<typeof createTask>>,
	TError,
	{ data: CreateTaskDto },
	TContext
> => {
	const mutationKey = ["createTask"]
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } }

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof createTask>>,
		{ data: CreateTaskDto }
	> = (props) => {
		const { data } = props ?? {}

		return createTask(data)
	}

	return { mutationFn, ...mutationOptions }
}

export type CreateTaskMutationResult = NonNullable<
	Awaited<ReturnType<typeof createTask>>
>
export type CreateTaskMutationBody = CreateTaskDto
export type CreateTaskMutationError = unknown

export const useCreateTask = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof createTask>>,
			TError,
			{ data: CreateTaskDto },
			TContext
		>
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof createTask>>,
	TError,
	{ data: CreateTaskDto },
	TContext
> => {
	return useMutation(getCreateTaskMutationOptions(options), queryClient)
}
export const listTasks = (params: ListTasksParams, signal?: AbortSignal) => {
	return sendRequest<TaskDto[]>({ url: `/task`, method: "GET", params, signal })
}

export const getListTasksQueryKey = (params?: ListTasksParams) => {
	return [`/task`, ...(params ? [params] : [])] as const
}

export const getListTasksQueryOptions = <
	TData = Awaited<ReturnType<typeof listTasks>>,
	TError = unknown,
>(
	params: ListTasksParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listTasks>>, TError, TData>
		>
	},
) => {
	const { query: queryOptions } = options ?? {}

	const queryKey = queryOptions?.queryKey ?? getListTasksQueryKey(params)

	const queryFn: QueryFunction<Awaited<ReturnType<typeof listTasks>>> = ({
		signal,
	}) => listTasks(params, signal)

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof listTasks>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListTasksQueryResult = NonNullable<
	Awaited<ReturnType<typeof listTasks>>
>
export type ListTasksQueryError = unknown

export function useListTasks<
	TData = Awaited<ReturnType<typeof listTasks>>,
	TError = unknown,
>(
	params: ListTasksParams,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listTasks>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof listTasks>>,
					TError,
					Awaited<ReturnType<typeof listTasks>>
				>,
				"initialData"
			>
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}
export function useListTasks<
	TData = Awaited<ReturnType<typeof listTasks>>,
	TError = unknown,
>(
	params: ListTasksParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listTasks>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof listTasks>>,
					TError,
					Awaited<ReturnType<typeof listTasks>>
				>,
				"initialData"
			>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}
export function useListTasks<
	TData = Awaited<ReturnType<typeof listTasks>>,
	TError = unknown,
>(
	params: ListTasksParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listTasks>>, TError, TData>
		>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}

export function useListTasks<
	TData = Awaited<ReturnType<typeof listTasks>>,
	TError = unknown,
>(
	params: ListTasksParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listTasks>>, TError, TData>
		>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
} {
	const queryOptions = getListTasksQueryOptions(params, options)

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> }

	return { ...query, queryKey: queryOptions.queryKey }
}

export const listPersonalTasks = (signal?: AbortSignal) => {
	return sendRequest<TaskWithWorkspaceDto[]>({
		url: `/task/personal`,
		method: "GET",
		signal,
	})
}

export const getListPersonalTasksQueryKey = () => {
	return [`/task/personal`] as const
}

export const getListPersonalTasksQueryOptions = <
	TData = Awaited<ReturnType<typeof listPersonalTasks>>,
	TError = unknown,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof listPersonalTasks>>,
			TError,
			TData
		>
	>
}) => {
	const { query: queryOptions } = options ?? {}

	const queryKey = queryOptions?.queryKey ?? getListPersonalTasksQueryKey()

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof listPersonalTasks>>
	> = ({ signal }) => listPersonalTasks(signal)

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof listPersonalTasks>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPersonalTasksQueryResult = NonNullable<
	Awaited<ReturnType<typeof listPersonalTasks>>
>
export type ListPersonalTasksQueryError = unknown

export function useListPersonalTasks<
	TData = Awaited<ReturnType<typeof listPersonalTasks>>,
	TError = unknown,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof listPersonalTasks>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof listPersonalTasks>>,
					TError,
					Awaited<ReturnType<typeof listPersonalTasks>>
				>,
				"initialData"
			>
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}
export function useListPersonalTasks<
	TData = Awaited<ReturnType<typeof listPersonalTasks>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof listPersonalTasks>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof listPersonalTasks>>,
					TError,
					Awaited<ReturnType<typeof listPersonalTasks>>
				>,
				"initialData"
			>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}
export function useListPersonalTasks<
	TData = Awaited<ReturnType<typeof listPersonalTasks>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof listPersonalTasks>>,
				TError,
				TData
			>
		>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}

export function useListPersonalTasks<
	TData = Awaited<ReturnType<typeof listPersonalTasks>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof listPersonalTasks>>,
				TError,
				TData
			>
		>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
} {
	const queryOptions = getListPersonalTasksQueryOptions(options)

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> }

	return { ...query, queryKey: queryOptions.queryKey }
}

export const getTask = (
	{ id }: GetTaskPathParameters,
	signal?: AbortSignal,
) => {
	return sendRequest<TaskWithWorkspaceDto>({
		url: `/task/${id}`,
		method: "GET",
		signal,
	})
}

export const getGetTaskQueryKey = ({ id }: GetTaskPathParameters) => {
	return [`/task/${id}`] as const
}

export const getGetTaskQueryOptions = <
	TData = Awaited<ReturnType<typeof getTask>>,
	TError = unknown,
>(
	{ id }: GetTaskPathParameters,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getTask>>, TError, TData>
		>
	},
) => {
	const { query: queryOptions } = options ?? {}

	const queryKey = queryOptions?.queryKey ?? getGetTaskQueryKey({ id })

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getTask>>> = ({
		signal,
	}) => getTask({ id }, signal)

	return {
		queryKey,
		queryFn,
		enabled: !!id,
		...queryOptions,
	} as UseQueryOptions<Awaited<ReturnType<typeof getTask>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>
	}
}

export type GetTaskQueryResult = NonNullable<
	Awaited<ReturnType<typeof getTask>>
>
export type GetTaskQueryError = unknown

export function useGetTask<
	TData = Awaited<ReturnType<typeof getTask>>,
	TError = unknown,
>(
	pathParams: GetTaskPathParameters,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getTask>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getTask>>,
					TError,
					Awaited<ReturnType<typeof getTask>>
				>,
				"initialData"
			>
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetTask<
	TData = Awaited<ReturnType<typeof getTask>>,
	TError = unknown,
>(
	pathParams: GetTaskPathParameters,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getTask>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getTask>>,
					TError,
					Awaited<ReturnType<typeof getTask>>
				>,
				"initialData"
			>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetTask<
	TData = Awaited<ReturnType<typeof getTask>>,
	TError = unknown,
>(
	pathParams: GetTaskPathParameters,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getTask>>, TError, TData>
		>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}

export function useGetTask<
	TData = Awaited<ReturnType<typeof getTask>>,
	TError = unknown,
>(
	{ id }: GetTaskPathParameters,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getTask>>, TError, TData>
		>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
} {
	const queryOptions = getGetTaskQueryOptions({ id }, options)

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> }

	return { ...query, queryKey: queryOptions.queryKey }
}

export const updateTask = (
	{ id }: UpdateTaskPathParameters,
	updateTaskDto: UpdateTaskDto,
	signal?: AbortSignal,
) => {
	return sendRequest<TaskWithWorkspaceDto>({
		url: `/task/${id}`,
		method: "PATCH",
		headers: { "Content-Type": "application/json" },
		data: updateTaskDto,
		signal,
	})
}

export const getUpdateTaskMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof updateTask>>,
		TError,
		{ pathParams: UpdateTaskPathParameters; data: UpdateTaskDto },
		TContext
	>
}): UseMutationOptions<
	Awaited<ReturnType<typeof updateTask>>,
	TError,
	{ pathParams: UpdateTaskPathParameters; data: UpdateTaskDto },
	TContext
> => {
	const mutationKey = ["updateTask"]
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } }

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof updateTask>>,
		{ pathParams: UpdateTaskPathParameters; data: UpdateTaskDto }
	> = (props) => {
		const { pathParams, data } = props ?? {}

		return updateTask(pathParams, data)
	}

	return { mutationFn, ...mutationOptions }
}

export type UpdateTaskMutationResult = NonNullable<
	Awaited<ReturnType<typeof updateTask>>
>
export type UpdateTaskMutationBody = UpdateTaskDto
export type UpdateTaskMutationError = unknown

export const useUpdateTask = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof updateTask>>,
			TError,
			{ pathParams: UpdateTaskPathParameters; data: UpdateTaskDto },
			TContext
		>
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof updateTask>>,
	TError,
	{ pathParams: UpdateTaskPathParameters; data: UpdateTaskDto },
	TContext
> => {
	return useMutation(getUpdateTaskMutationOptions(options), queryClient)
}
export const deleteTask = (
	{ id }: DeleteTaskPathParameters,
	signal?: AbortSignal,
) => {
	return sendRequest<TaskWithWorkspaceDto>({
		url: `/task/${id}`,
		method: "DELETE",
		signal,
	})
}

export const getDeleteTaskMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteTask>>,
		TError,
		{ pathParams: DeleteTaskPathParameters },
		TContext
	>
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteTask>>,
	TError,
	{ pathParams: DeleteTaskPathParameters },
	TContext
> => {
	const mutationKey = ["deleteTask"]
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } }

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteTask>>,
		{ pathParams: DeleteTaskPathParameters }
	> = (props) => {
		const { pathParams } = props ?? {}

		return deleteTask(pathParams)
	}

	return { mutationFn, ...mutationOptions }
}

export type DeleteTaskMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteTask>>
>

export type DeleteTaskMutationError = unknown

export const useDeleteTask = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteTask>>,
			TError,
			{ pathParams: DeleteTaskPathParameters },
			TContext
		>
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof deleteTask>>,
	TError,
	{ pathParams: DeleteTaskPathParameters },
	TContext
> => {
	return useMutation(getDeleteTaskMutationOptions(options), queryClient)
}
