/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */
import { faker } from "@faker-js/faker"
import type { RequestHandlerOptions } from "msw"
import { HttpResponse, http } from "msw"
import type {
	TaskDetailsDto,
	TaskDto,
	TaskRowDto,
	TaskRowWithWorkspaceDto,
	TaskWithWorkspaceDto,
} from "../model"
import {
	DeadlineType,
	ExtractionStatus,
	PermissionType,
	TaskCreationType,
	WorkspaceStatusType,
} from "../model"

export const getCreateTaskResponseMock = (
	overrideResponse: Partial<Extract<TaskWithWorkspaceDto, object>> = {},
): TaskWithWorkspaceDto => ({
	createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
	createdBy: faker.number.float({ fractionDigits: 2 }),
	updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
	updatedBy: faker.number.float({ fractionDigits: 2 }),
	deletedAt: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			null,
		]),
		null,
	]),
	deletedBy: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.number.float({ fractionDigits: 2 }),
			null,
		]),
		null,
	]),
	id: faker.number.float({ fractionDigits: 2 }),
	title: faker.string.alpha({ length: { min: 10, max: 20 } }),
	description: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		null,
	]),
	flagged: faker.datatype.boolean(),
	deadlineType: faker.helpers.arrayElement(Object.values(DeadlineType)),
	creationType: faker.helpers.arrayElement(Object.values(TaskCreationType)),
	dueDate: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			null,
		]),
		null,
	]),
	notes: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		null,
	]),
	workspaceId: faker.number.float({ fractionDigits: 2 }),
	source: faker.helpers.arrayElement([
		{
			...{
				createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
				createdBy: faker.number.float({ fractionDigits: 2 }),
				updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
				updatedBy: faker.number.float({ fractionDigits: 2 }),
				deletedAt: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
						null,
					]),
					null,
				]),
				deletedBy: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.number.float({ fractionDigits: 2 }),
						null,
					]),
					null,
				]),
				id: faker.number.float({ fractionDigits: 2 }),
				name: faker.string.alpha({ length: { min: 10, max: 20 } }),
				date: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
						null,
					]),
					null,
				]),
				workspaceId: faker.number.float({ fractionDigits: 2 }),
				attachmentKey: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					null,
				]),
				attachmentName: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					null,
				]),
				draft: faker.datatype.boolean(),
				extractionStatus: faker.helpers.arrayElement(
					Object.values(ExtractionStatus),
				),
				tags: Array.from(
					{ length: faker.number.int({ min: 1, max: 10 }) },
					(_, i) => i + 1,
				).map(() => ({
					createdAt: new Date(
						faker.date.past().toISOString().slice(0, 19) + "Z",
					),
					createdBy: faker.number.float({ fractionDigits: 2 }),
					updatedAt: new Date(
						faker.date.past().toISOString().slice(0, 19) + "Z",
					),
					updatedBy: faker.number.float({ fractionDigits: 2 }),
					id: faker.number.float({ fractionDigits: 2 }),
					name: faker.string.alpha({ length: { min: 10, max: 20 } }),
					workspaceId: faker.number.float({ fractionDigits: 2 }),
				})),
			},
		},
		null,
	]),
	tags: Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		createdBy: faker.number.float({ fractionDigits: 2 }),
		updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		updatedBy: faker.number.float({ fractionDigits: 2 }),
		id: faker.number.float({ fractionDigits: 2 }),
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		workspaceId: faker.number.float({ fractionDigits: 2 }),
	})),
	assigneeStatuses: Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		assignee: {
			createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			createdBy: faker.number.float({ fractionDigits: 2 }),
			updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			updatedBy: faker.number.float({ fractionDigits: 2 }),
			deletedAt: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
					null,
				]),
				null,
			]),
			deletedBy: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					faker.number.float({ fractionDigits: 2 }),
					null,
				]),
				null,
			]),
			id: faker.number.float({ fractionDigits: 2 }),
			name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			color: faker.string.alpha({ length: { min: 10, max: 20 } }),
			icon: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				null,
			]),
			iconName: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				null,
			]),
			workspaceId: faker.number.float({ fractionDigits: 2 }),
			users: Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				id: faker.number.float({ fractionDigits: 2 }),
				upn: faker.string.alpha({ length: { min: 10, max: 20 } }),
				info: faker.helpers.arrayElement([
					{
						...{
							upn: faker.string.alpha({ length: { min: 10, max: 20 } }),
							displayName: faker.helpers.arrayElement([
								faker.string.alpha({ length: { min: 10, max: 20 } }),
								undefined,
							]),
							name: faker.helpers.arrayElement([
								faker.string.alpha({ length: { min: 10, max: 20 } }),
								undefined,
							]),
							isBI: faker.helpers.arrayElement([
								faker.datatype.boolean(),
								undefined,
							]),
						},
					},
					null,
				]),
			})),
		},
		status: {
			id: faker.number.float({ fractionDigits: 2 }),
			name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			color: faker.string.alpha({ length: { min: 10, max: 20 } }),
			type: faker.helpers.arrayElement(Object.values(WorkspaceStatusType)),
			workspaceId: faker.number.float({ fractionDigits: 2 }),
		},
		description: faker.string.alpha({ length: { min: 10, max: 20 } }),
		editable: faker.datatype.boolean(),
	})),
	workspace: {
		createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		createdBy: faker.number.float({ fractionDigits: 2 }),
		updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		updatedBy: faker.number.float({ fractionDigits: 2 }),
		deletedAt: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
				null,
			]),
			null,
		]),
		deletedBy: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.number.float({ fractionDigits: 2 }),
				null,
			]),
			null,
		]),
		id: faker.number.float({ fractionDigits: 2 }),
		title: faker.string.alpha({ length: { min: 10, max: 20 } }),
		urlName: faker.string.alpha({ length: { min: 10, max: 20 } }),
		icon: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			null,
		]),
		assigneeStatusEditable: faker.datatype.boolean(),
		chatNotification: faker.datatype.boolean(),
		mailNotification: faker.datatype.boolean(),
		pikudId: faker.number.float({ fractionDigits: 2 }),
		permissionType: faker.helpers.arrayElement(Object.values(PermissionType)),
	},
	...overrideResponse,
})

export const getListTasksResponseMock = (): TaskDto[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		createdBy: faker.number.float({ fractionDigits: 2 }),
		updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		updatedBy: faker.number.float({ fractionDigits: 2 }),
		deletedAt: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
				null,
			]),
			null,
		]),
		deletedBy: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.number.float({ fractionDigits: 2 }),
				null,
			]),
			null,
		]),
		id: faker.number.float({ fractionDigits: 2 }),
		title: faker.string.alpha({ length: { min: 10, max: 20 } }),
		description: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			null,
		]),
		flagged: faker.datatype.boolean(),
		deadlineType: faker.helpers.arrayElement(Object.values(DeadlineType)),
		creationType: faker.helpers.arrayElement(Object.values(TaskCreationType)),
		dueDate: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
				null,
			]),
			null,
		]),
		notes: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			null,
		]),
		workspaceId: faker.number.float({ fractionDigits: 2 }),
		source: faker.helpers.arrayElement([
			{
				...{
					createdAt: new Date(
						faker.date.past().toISOString().slice(0, 19) + "Z",
					),
					createdBy: faker.number.float({ fractionDigits: 2 }),
					updatedAt: new Date(
						faker.date.past().toISOString().slice(0, 19) + "Z",
					),
					updatedBy: faker.number.float({ fractionDigits: 2 }),
					deletedAt: faker.helpers.arrayElement([
						faker.helpers.arrayElement([
							new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
							null,
						]),
						null,
					]),
					deletedBy: faker.helpers.arrayElement([
						faker.helpers.arrayElement([
							faker.number.float({ fractionDigits: 2 }),
							null,
						]),
						null,
					]),
					id: faker.number.float({ fractionDigits: 2 }),
					name: faker.string.alpha({ length: { min: 10, max: 20 } }),
					date: faker.helpers.arrayElement([
						faker.helpers.arrayElement([
							new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
							null,
						]),
						null,
					]),
					workspaceId: faker.number.float({ fractionDigits: 2 }),
					attachmentKey: faker.helpers.arrayElement([
						faker.helpers.arrayElement([
							faker.string.alpha({ length: { min: 10, max: 20 } }),
							null,
						]),
						null,
					]),
					attachmentName: faker.helpers.arrayElement([
						faker.helpers.arrayElement([
							faker.string.alpha({ length: { min: 10, max: 20 } }),
							null,
						]),
						null,
					]),
					draft: faker.datatype.boolean(),
					extractionStatus: faker.helpers.arrayElement(
						Object.values(ExtractionStatus),
					),
					tags: Array.from(
						{ length: faker.number.int({ min: 1, max: 10 }) },
						(_, i) => i + 1,
					).map(() => ({
						createdAt: new Date(
							faker.date.past().toISOString().slice(0, 19) + "Z",
						),
						createdBy: faker.number.float({ fractionDigits: 2 }),
						updatedAt: new Date(
							faker.date.past().toISOString().slice(0, 19) + "Z",
						),
						updatedBy: faker.number.float({ fractionDigits: 2 }),
						id: faker.number.float({ fractionDigits: 2 }),
						name: faker.string.alpha({ length: { min: 10, max: 20 } }),
						workspaceId: faker.number.float({ fractionDigits: 2 }),
					})),
				},
			},
			null,
		]),
		tags: Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			createdBy: faker.number.float({ fractionDigits: 2 }),
			updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			updatedBy: faker.number.float({ fractionDigits: 2 }),
			id: faker.number.float({ fractionDigits: 2 }),
			name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			workspaceId: faker.number.float({ fractionDigits: 2 }),
		})),
		assigneeStatuses: Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			assignee: {
				createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
				createdBy: faker.number.float({ fractionDigits: 2 }),
				updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
				updatedBy: faker.number.float({ fractionDigits: 2 }),
				deletedAt: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
						null,
					]),
					null,
				]),
				deletedBy: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.number.float({ fractionDigits: 2 }),
						null,
					]),
					null,
				]),
				id: faker.number.float({ fractionDigits: 2 }),
				name: faker.string.alpha({ length: { min: 10, max: 20 } }),
				color: faker.string.alpha({ length: { min: 10, max: 20 } }),
				icon: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					null,
				]),
				iconName: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					null,
				]),
				workspaceId: faker.number.float({ fractionDigits: 2 }),
				users: Array.from(
					{ length: faker.number.int({ min: 1, max: 10 }) },
					(_, i) => i + 1,
				).map(() => ({
					id: faker.number.float({ fractionDigits: 2 }),
					upn: faker.string.alpha({ length: { min: 10, max: 20 } }),
					info: faker.helpers.arrayElement([
						{
							...{
								upn: faker.string.alpha({ length: { min: 10, max: 20 } }),
								displayName: faker.helpers.arrayElement([
									faker.string.alpha({ length: { min: 10, max: 20 } }),
									undefined,
								]),
								name: faker.helpers.arrayElement([
									faker.string.alpha({ length: { min: 10, max: 20 } }),
									undefined,
								]),
								isBI: faker.helpers.arrayElement([
									faker.datatype.boolean(),
									undefined,
								]),
							},
						},
						null,
					]),
				})),
			},
			status: {
				id: faker.number.float({ fractionDigits: 2 }),
				name: faker.string.alpha({ length: { min: 10, max: 20 } }),
				color: faker.string.alpha({ length: { min: 10, max: 20 } }),
				type: faker.helpers.arrayElement(Object.values(WorkspaceStatusType)),
				workspaceId: faker.number.float({ fractionDigits: 2 }),
			},
			description: faker.string.alpha({ length: { min: 10, max: 20 } }),
			editable: faker.datatype.boolean(),
		})),
	}))

export const getListTaskRowsResponseMock = (): TaskRowDto[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		createdBy: faker.number.float({ fractionDigits: 2 }),
		updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		updatedBy: faker.number.float({ fractionDigits: 2 }),
		deletedAt: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
				null,
			]),
			null,
		]),
		deletedBy: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.number.float({ fractionDigits: 2 }),
				null,
			]),
			null,
		]),
		id: faker.number.float({ fractionDigits: 2 }),
		title: faker.string.alpha({ length: { min: 10, max: 20 } }),
		description: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			null,
		]),
		flagged: faker.datatype.boolean(),
		deadlineType: faker.helpers.arrayElement(Object.values(DeadlineType)),
		creationType: faker.helpers.arrayElement(Object.values(TaskCreationType)),
		dueDate: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
				null,
			]),
			null,
		]),
		notes: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			null,
		]),
		workspaceId: faker.number.float({ fractionDigits: 2 }),
		source: faker.helpers.arrayElement([
			{
				...{
					createdAt: new Date(
						faker.date.past().toISOString().slice(0, 19) + "Z",
					),
					createdBy: faker.number.float({ fractionDigits: 2 }),
					updatedAt: new Date(
						faker.date.past().toISOString().slice(0, 19) + "Z",
					),
					updatedBy: faker.number.float({ fractionDigits: 2 }),
					deletedAt: faker.helpers.arrayElement([
						faker.helpers.arrayElement([
							new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
							null,
						]),
						null,
					]),
					deletedBy: faker.helpers.arrayElement([
						faker.helpers.arrayElement([
							faker.number.float({ fractionDigits: 2 }),
							null,
						]),
						null,
					]),
					id: faker.number.float({ fractionDigits: 2 }),
					name: faker.string.alpha({ length: { min: 10, max: 20 } }),
					date: faker.helpers.arrayElement([
						faker.helpers.arrayElement([
							new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
							null,
						]),
						null,
					]),
					workspaceId: faker.number.float({ fractionDigits: 2 }),
					attachmentKey: faker.helpers.arrayElement([
						faker.helpers.arrayElement([
							faker.string.alpha({ length: { min: 10, max: 20 } }),
							null,
						]),
						null,
					]),
					attachmentName: faker.helpers.arrayElement([
						faker.helpers.arrayElement([
							faker.string.alpha({ length: { min: 10, max: 20 } }),
							null,
						]),
						null,
					]),
					draft: faker.datatype.boolean(),
					extractionStatus: faker.helpers.arrayElement(
						Object.values(ExtractionStatus),
					),
					tags: Array.from(
						{ length: faker.number.int({ min: 1, max: 10 }) },
						(_, i) => i + 1,
					).map(() => ({
						createdAt: new Date(
							faker.date.past().toISOString().slice(0, 19) + "Z",
						),
						createdBy: faker.number.float({ fractionDigits: 2 }),
						updatedAt: new Date(
							faker.date.past().toISOString().slice(0, 19) + "Z",
						),
						updatedBy: faker.number.float({ fractionDigits: 2 }),
						id: faker.number.float({ fractionDigits: 2 }),
						name: faker.string.alpha({ length: { min: 10, max: 20 } }),
						workspaceId: faker.number.float({ fractionDigits: 2 }),
					})),
				},
			},
			null,
		]),
		tags: Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			createdBy: faker.number.float({ fractionDigits: 2 }),
			updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			updatedBy: faker.number.float({ fractionDigits: 2 }),
			id: faker.number.float({ fractionDigits: 2 }),
			name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			workspaceId: faker.number.float({ fractionDigits: 2 }),
		})),
		rowKey: faker.string.alpha({ length: { min: 10, max: 20 } }),
		assignee: faker.helpers.arrayElement([
			{
				createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
				createdBy: faker.number.float({ fractionDigits: 2 }),
				updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
				updatedBy: faker.number.float({ fractionDigits: 2 }),
				deletedAt: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
						null,
					]),
					null,
				]),
				deletedBy: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.number.float({ fractionDigits: 2 }),
						null,
					]),
					null,
				]),
				id: faker.number.float({ fractionDigits: 2 }),
				name: faker.string.alpha({ length: { min: 10, max: 20 } }),
				color: faker.string.alpha({ length: { min: 10, max: 20 } }),
				icon: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					null,
				]),
				iconName: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					null,
				]),
				workspaceId: faker.number.float({ fractionDigits: 2 }),
				users: Array.from(
					{ length: faker.number.int({ min: 1, max: 10 }) },
					(_, i) => i + 1,
				).map(() => ({
					id: faker.number.float({ fractionDigits: 2 }),
					upn: faker.string.alpha({ length: { min: 10, max: 20 } }),
					info: faker.helpers.arrayElement([
						{
							...{
								upn: faker.string.alpha({ length: { min: 10, max: 20 } }),
								displayName: faker.helpers.arrayElement([
									faker.string.alpha({ length: { min: 10, max: 20 } }),
									undefined,
								]),
								name: faker.helpers.arrayElement([
									faker.string.alpha({ length: { min: 10, max: 20 } }),
									undefined,
								]),
								isBI: faker.helpers.arrayElement([
									faker.datatype.boolean(),
									undefined,
								]),
							},
						},
						null,
					]),
				})),
			},
			undefined,
		]),
		status: {
			id: faker.number.float({ fractionDigits: 2 }),
			name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			color: faker.string.alpha({ length: { min: 10, max: 20 } }),
			type: faker.helpers.arrayElement(Object.values(WorkspaceStatusType)),
			workspaceId: faker.number.float({ fractionDigits: 2 }),
		},
		editable: faker.datatype.boolean(),
		otherAssignees: Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			assignee: {
				createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
				createdBy: faker.number.float({ fractionDigits: 2 }),
				updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
				updatedBy: faker.number.float({ fractionDigits: 2 }),
				deletedAt: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
						null,
					]),
					null,
				]),
				deletedBy: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.number.float({ fractionDigits: 2 }),
						null,
					]),
					null,
				]),
				id: faker.number.float({ fractionDigits: 2 }),
				name: faker.string.alpha({ length: { min: 10, max: 20 } }),
				color: faker.string.alpha({ length: { min: 10, max: 20 } }),
				icon: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					null,
				]),
				iconName: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					null,
				]),
				workspaceId: faker.number.float({ fractionDigits: 2 }),
				users: Array.from(
					{ length: faker.number.int({ min: 1, max: 10 }) },
					(_, i) => i + 1,
				).map(() => ({
					id: faker.number.float({ fractionDigits: 2 }),
					upn: faker.string.alpha({ length: { min: 10, max: 20 } }),
					info: faker.helpers.arrayElement([
						{
							...{
								upn: faker.string.alpha({ length: { min: 10, max: 20 } }),
								displayName: faker.helpers.arrayElement([
									faker.string.alpha({ length: { min: 10, max: 20 } }),
									undefined,
								]),
								name: faker.helpers.arrayElement([
									faker.string.alpha({ length: { min: 10, max: 20 } }),
									undefined,
								]),
								isBI: faker.helpers.arrayElement([
									faker.datatype.boolean(),
									undefined,
								]),
							},
						},
						null,
					]),
				})),
			},
			status: {
				id: faker.number.float({ fractionDigits: 2 }),
				name: faker.string.alpha({ length: { min: 10, max: 20 } }),
				color: faker.string.alpha({ length: { min: 10, max: 20 } }),
				type: faker.helpers.arrayElement(Object.values(WorkspaceStatusType)),
				workspaceId: faker.number.float({ fractionDigits: 2 }),
			},
			description: faker.string.alpha({ length: { min: 10, max: 20 } }),
			editable: faker.datatype.boolean(),
		})),
		archivedAt: faker.helpers.arrayElement([
			new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			undefined,
		]),
	}))

export const getListPersonalTasksResponseMock = (): TaskWithWorkspaceDto[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		createdBy: faker.number.float({ fractionDigits: 2 }),
		updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		updatedBy: faker.number.float({ fractionDigits: 2 }),
		deletedAt: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
				null,
			]),
			null,
		]),
		deletedBy: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.number.float({ fractionDigits: 2 }),
				null,
			]),
			null,
		]),
		id: faker.number.float({ fractionDigits: 2 }),
		title: faker.string.alpha({ length: { min: 10, max: 20 } }),
		description: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			null,
		]),
		flagged: faker.datatype.boolean(),
		deadlineType: faker.helpers.arrayElement(Object.values(DeadlineType)),
		creationType: faker.helpers.arrayElement(Object.values(TaskCreationType)),
		dueDate: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
				null,
			]),
			null,
		]),
		notes: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			null,
		]),
		workspaceId: faker.number.float({ fractionDigits: 2 }),
		source: faker.helpers.arrayElement([
			{
				...{
					createdAt: new Date(
						faker.date.past().toISOString().slice(0, 19) + "Z",
					),
					createdBy: faker.number.float({ fractionDigits: 2 }),
					updatedAt: new Date(
						faker.date.past().toISOString().slice(0, 19) + "Z",
					),
					updatedBy: faker.number.float({ fractionDigits: 2 }),
					deletedAt: faker.helpers.arrayElement([
						faker.helpers.arrayElement([
							new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
							null,
						]),
						null,
					]),
					deletedBy: faker.helpers.arrayElement([
						faker.helpers.arrayElement([
							faker.number.float({ fractionDigits: 2 }),
							null,
						]),
						null,
					]),
					id: faker.number.float({ fractionDigits: 2 }),
					name: faker.string.alpha({ length: { min: 10, max: 20 } }),
					date: faker.helpers.arrayElement([
						faker.helpers.arrayElement([
							new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
							null,
						]),
						null,
					]),
					workspaceId: faker.number.float({ fractionDigits: 2 }),
					attachmentKey: faker.helpers.arrayElement([
						faker.helpers.arrayElement([
							faker.string.alpha({ length: { min: 10, max: 20 } }),
							null,
						]),
						null,
					]),
					attachmentName: faker.helpers.arrayElement([
						faker.helpers.arrayElement([
							faker.string.alpha({ length: { min: 10, max: 20 } }),
							null,
						]),
						null,
					]),
					draft: faker.datatype.boolean(),
					extractionStatus: faker.helpers.arrayElement(
						Object.values(ExtractionStatus),
					),
					tags: Array.from(
						{ length: faker.number.int({ min: 1, max: 10 }) },
						(_, i) => i + 1,
					).map(() => ({
						createdAt: new Date(
							faker.date.past().toISOString().slice(0, 19) + "Z",
						),
						createdBy: faker.number.float({ fractionDigits: 2 }),
						updatedAt: new Date(
							faker.date.past().toISOString().slice(0, 19) + "Z",
						),
						updatedBy: faker.number.float({ fractionDigits: 2 }),
						id: faker.number.float({ fractionDigits: 2 }),
						name: faker.string.alpha({ length: { min: 10, max: 20 } }),
						workspaceId: faker.number.float({ fractionDigits: 2 }),
					})),
				},
			},
			null,
		]),
		tags: Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			createdBy: faker.number.float({ fractionDigits: 2 }),
			updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			updatedBy: faker.number.float({ fractionDigits: 2 }),
			id: faker.number.float({ fractionDigits: 2 }),
			name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			workspaceId: faker.number.float({ fractionDigits: 2 }),
		})),
		assigneeStatuses: Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			assignee: {
				createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
				createdBy: faker.number.float({ fractionDigits: 2 }),
				updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
				updatedBy: faker.number.float({ fractionDigits: 2 }),
				deletedAt: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
						null,
					]),
					null,
				]),
				deletedBy: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.number.float({ fractionDigits: 2 }),
						null,
					]),
					null,
				]),
				id: faker.number.float({ fractionDigits: 2 }),
				name: faker.string.alpha({ length: { min: 10, max: 20 } }),
				color: faker.string.alpha({ length: { min: 10, max: 20 } }),
				icon: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					null,
				]),
				iconName: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					null,
				]),
				workspaceId: faker.number.float({ fractionDigits: 2 }),
				users: Array.from(
					{ length: faker.number.int({ min: 1, max: 10 }) },
					(_, i) => i + 1,
				).map(() => ({
					id: faker.number.float({ fractionDigits: 2 }),
					upn: faker.string.alpha({ length: { min: 10, max: 20 } }),
					info: faker.helpers.arrayElement([
						{
							...{
								upn: faker.string.alpha({ length: { min: 10, max: 20 } }),
								displayName: faker.helpers.arrayElement([
									faker.string.alpha({ length: { min: 10, max: 20 } }),
									undefined,
								]),
								name: faker.helpers.arrayElement([
									faker.string.alpha({ length: { min: 10, max: 20 } }),
									undefined,
								]),
								isBI: faker.helpers.arrayElement([
									faker.datatype.boolean(),
									undefined,
								]),
							},
						},
						null,
					]),
				})),
			},
			status: {
				id: faker.number.float({ fractionDigits: 2 }),
				name: faker.string.alpha({ length: { min: 10, max: 20 } }),
				color: faker.string.alpha({ length: { min: 10, max: 20 } }),
				type: faker.helpers.arrayElement(Object.values(WorkspaceStatusType)),
				workspaceId: faker.number.float({ fractionDigits: 2 }),
			},
			description: faker.string.alpha({ length: { min: 10, max: 20 } }),
			editable: faker.datatype.boolean(),
		})),
		workspace: {
			createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			createdBy: faker.number.float({ fractionDigits: 2 }),
			updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			updatedBy: faker.number.float({ fractionDigits: 2 }),
			deletedAt: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
					null,
				]),
				null,
			]),
			deletedBy: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					faker.number.float({ fractionDigits: 2 }),
					null,
				]),
				null,
			]),
			id: faker.number.float({ fractionDigits: 2 }),
			title: faker.string.alpha({ length: { min: 10, max: 20 } }),
			urlName: faker.string.alpha({ length: { min: 10, max: 20 } }),
			icon: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				null,
			]),
			assigneeStatusEditable: faker.datatype.boolean(),
			chatNotification: faker.datatype.boolean(),
			mailNotification: faker.datatype.boolean(),
			pikudId: faker.number.float({ fractionDigits: 2 }),
			permissionType: faker.helpers.arrayElement(Object.values(PermissionType)),
		},
	}))

export const getListPersonalTaskRowsResponseMock =
	(): TaskRowWithWorkspaceDto[] =>
		Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			createdBy: faker.number.float({ fractionDigits: 2 }),
			updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			updatedBy: faker.number.float({ fractionDigits: 2 }),
			deletedAt: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
					null,
				]),
				null,
			]),
			deletedBy: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					faker.number.float({ fractionDigits: 2 }),
					null,
				]),
				null,
			]),
			id: faker.number.float({ fractionDigits: 2 }),
			title: faker.string.alpha({ length: { min: 10, max: 20 } }),
			description: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				null,
			]),
			flagged: faker.datatype.boolean(),
			deadlineType: faker.helpers.arrayElement(Object.values(DeadlineType)),
			creationType: faker.helpers.arrayElement(Object.values(TaskCreationType)),
			dueDate: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
					null,
				]),
				null,
			]),
			notes: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				null,
			]),
			workspaceId: faker.number.float({ fractionDigits: 2 }),
			source: faker.helpers.arrayElement([
				{
					...{
						createdAt: new Date(
							faker.date.past().toISOString().slice(0, 19) + "Z",
						),
						createdBy: faker.number.float({ fractionDigits: 2 }),
						updatedAt: new Date(
							faker.date.past().toISOString().slice(0, 19) + "Z",
						),
						updatedBy: faker.number.float({ fractionDigits: 2 }),
						deletedAt: faker.helpers.arrayElement([
							faker.helpers.arrayElement([
								new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
								null,
							]),
							null,
						]),
						deletedBy: faker.helpers.arrayElement([
							faker.helpers.arrayElement([
								faker.number.float({ fractionDigits: 2 }),
								null,
							]),
							null,
						]),
						id: faker.number.float({ fractionDigits: 2 }),
						name: faker.string.alpha({ length: { min: 10, max: 20 } }),
						date: faker.helpers.arrayElement([
							faker.helpers.arrayElement([
								new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
								null,
							]),
							null,
						]),
						workspaceId: faker.number.float({ fractionDigits: 2 }),
						attachmentKey: faker.helpers.arrayElement([
							faker.helpers.arrayElement([
								faker.string.alpha({ length: { min: 10, max: 20 } }),
								null,
							]),
							null,
						]),
						attachmentName: faker.helpers.arrayElement([
							faker.helpers.arrayElement([
								faker.string.alpha({ length: { min: 10, max: 20 } }),
								null,
							]),
							null,
						]),
						draft: faker.datatype.boolean(),
						extractionStatus: faker.helpers.arrayElement(
							Object.values(ExtractionStatus),
						),
						tags: Array.from(
							{ length: faker.number.int({ min: 1, max: 10 }) },
							(_, i) => i + 1,
						).map(() => ({
							createdAt: new Date(
								faker.date.past().toISOString().slice(0, 19) + "Z",
							),
							createdBy: faker.number.float({ fractionDigits: 2 }),
							updatedAt: new Date(
								faker.date.past().toISOString().slice(0, 19) + "Z",
							),
							updatedBy: faker.number.float({ fractionDigits: 2 }),
							id: faker.number.float({ fractionDigits: 2 }),
							name: faker.string.alpha({ length: { min: 10, max: 20 } }),
							workspaceId: faker.number.float({ fractionDigits: 2 }),
						})),
					},
				},
				null,
			]),
			tags: Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
				createdBy: faker.number.float({ fractionDigits: 2 }),
				updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
				updatedBy: faker.number.float({ fractionDigits: 2 }),
				id: faker.number.float({ fractionDigits: 2 }),
				name: faker.string.alpha({ length: { min: 10, max: 20 } }),
				workspaceId: faker.number.float({ fractionDigits: 2 }),
			})),
			rowKey: faker.string.alpha({ length: { min: 10, max: 20 } }),
			assignee: faker.helpers.arrayElement([
				{
					createdAt: new Date(
						faker.date.past().toISOString().slice(0, 19) + "Z",
					),
					createdBy: faker.number.float({ fractionDigits: 2 }),
					updatedAt: new Date(
						faker.date.past().toISOString().slice(0, 19) + "Z",
					),
					updatedBy: faker.number.float({ fractionDigits: 2 }),
					deletedAt: faker.helpers.arrayElement([
						faker.helpers.arrayElement([
							new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
							null,
						]),
						null,
					]),
					deletedBy: faker.helpers.arrayElement([
						faker.helpers.arrayElement([
							faker.number.float({ fractionDigits: 2 }),
							null,
						]),
						null,
					]),
					id: faker.number.float({ fractionDigits: 2 }),
					name: faker.string.alpha({ length: { min: 10, max: 20 } }),
					color: faker.string.alpha({ length: { min: 10, max: 20 } }),
					icon: faker.helpers.arrayElement([
						faker.helpers.arrayElement([
							faker.string.alpha({ length: { min: 10, max: 20 } }),
							null,
						]),
						null,
					]),
					iconName: faker.helpers.arrayElement([
						faker.helpers.arrayElement([
							faker.string.alpha({ length: { min: 10, max: 20 } }),
							null,
						]),
						null,
					]),
					workspaceId: faker.number.float({ fractionDigits: 2 }),
					users: Array.from(
						{ length: faker.number.int({ min: 1, max: 10 }) },
						(_, i) => i + 1,
					).map(() => ({
						id: faker.number.float({ fractionDigits: 2 }),
						upn: faker.string.alpha({ length: { min: 10, max: 20 } }),
						info: faker.helpers.arrayElement([
							{
								...{
									upn: faker.string.alpha({ length: { min: 10, max: 20 } }),
									displayName: faker.helpers.arrayElement([
										faker.string.alpha({ length: { min: 10, max: 20 } }),
										undefined,
									]),
									name: faker.helpers.arrayElement([
										faker.string.alpha({ length: { min: 10, max: 20 } }),
										undefined,
									]),
									isBI: faker.helpers.arrayElement([
										faker.datatype.boolean(),
										undefined,
									]),
								},
							},
							null,
						]),
					})),
				},
				undefined,
			]),
			status: {
				id: faker.number.float({ fractionDigits: 2 }),
				name: faker.string.alpha({ length: { min: 10, max: 20 } }),
				color: faker.string.alpha({ length: { min: 10, max: 20 } }),
				type: faker.helpers.arrayElement(Object.values(WorkspaceStatusType)),
				workspaceId: faker.number.float({ fractionDigits: 2 }),
			},
			editable: faker.datatype.boolean(),
			otherAssignees: Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				assignee: {
					createdAt: new Date(
						faker.date.past().toISOString().slice(0, 19) + "Z",
					),
					createdBy: faker.number.float({ fractionDigits: 2 }),
					updatedAt: new Date(
						faker.date.past().toISOString().slice(0, 19) + "Z",
					),
					updatedBy: faker.number.float({ fractionDigits: 2 }),
					deletedAt: faker.helpers.arrayElement([
						faker.helpers.arrayElement([
							new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
							null,
						]),
						null,
					]),
					deletedBy: faker.helpers.arrayElement([
						faker.helpers.arrayElement([
							faker.number.float({ fractionDigits: 2 }),
							null,
						]),
						null,
					]),
					id: faker.number.float({ fractionDigits: 2 }),
					name: faker.string.alpha({ length: { min: 10, max: 20 } }),
					color: faker.string.alpha({ length: { min: 10, max: 20 } }),
					icon: faker.helpers.arrayElement([
						faker.helpers.arrayElement([
							faker.string.alpha({ length: { min: 10, max: 20 } }),
							null,
						]),
						null,
					]),
					iconName: faker.helpers.arrayElement([
						faker.helpers.arrayElement([
							faker.string.alpha({ length: { min: 10, max: 20 } }),
							null,
						]),
						null,
					]),
					workspaceId: faker.number.float({ fractionDigits: 2 }),
					users: Array.from(
						{ length: faker.number.int({ min: 1, max: 10 }) },
						(_, i) => i + 1,
					).map(() => ({
						id: faker.number.float({ fractionDigits: 2 }),
						upn: faker.string.alpha({ length: { min: 10, max: 20 } }),
						info: faker.helpers.arrayElement([
							{
								...{
									upn: faker.string.alpha({ length: { min: 10, max: 20 } }),
									displayName: faker.helpers.arrayElement([
										faker.string.alpha({ length: { min: 10, max: 20 } }),
										undefined,
									]),
									name: faker.helpers.arrayElement([
										faker.string.alpha({ length: { min: 10, max: 20 } }),
										undefined,
									]),
									isBI: faker.helpers.arrayElement([
										faker.datatype.boolean(),
										undefined,
									]),
								},
							},
							null,
						]),
					})),
				},
				status: {
					id: faker.number.float({ fractionDigits: 2 }),
					name: faker.string.alpha({ length: { min: 10, max: 20 } }),
					color: faker.string.alpha({ length: { min: 10, max: 20 } }),
					type: faker.helpers.arrayElement(Object.values(WorkspaceStatusType)),
					workspaceId: faker.number.float({ fractionDigits: 2 }),
				},
				description: faker.string.alpha({ length: { min: 10, max: 20 } }),
				editable: faker.datatype.boolean(),
			})),
			archivedAt: faker.helpers.arrayElement([
				new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
				undefined,
			]),
			workspace: {
				createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
				createdBy: faker.number.float({ fractionDigits: 2 }),
				updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
				updatedBy: faker.number.float({ fractionDigits: 2 }),
				deletedAt: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
						null,
					]),
					null,
				]),
				deletedBy: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.number.float({ fractionDigits: 2 }),
						null,
					]),
					null,
				]),
				id: faker.number.float({ fractionDigits: 2 }),
				title: faker.string.alpha({ length: { min: 10, max: 20 } }),
				urlName: faker.string.alpha({ length: { min: 10, max: 20 } }),
				icon: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					null,
				]),
				assigneeStatusEditable: faker.datatype.boolean(),
				chatNotification: faker.datatype.boolean(),
				mailNotification: faker.datatype.boolean(),
				pikudId: faker.number.float({ fractionDigits: 2 }),
				permissionType: faker.helpers.arrayElement(
					Object.values(PermissionType),
				),
			},
		}))

export const getGetTaskResponseMock = (
	overrideResponse: Partial<Extract<TaskDetailsDto, object>> = {},
): TaskDetailsDto => ({
	createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
	createdBy: faker.number.float({ fractionDigits: 2 }),
	updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
	updatedBy: faker.number.float({ fractionDigits: 2 }),
	deletedAt: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			null,
		]),
		null,
	]),
	deletedBy: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.number.float({ fractionDigits: 2 }),
			null,
		]),
		null,
	]),
	id: faker.number.float({ fractionDigits: 2 }),
	title: faker.string.alpha({ length: { min: 10, max: 20 } }),
	description: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		null,
	]),
	flagged: faker.datatype.boolean(),
	deadlineType: faker.helpers.arrayElement(Object.values(DeadlineType)),
	creationType: faker.helpers.arrayElement(Object.values(TaskCreationType)),
	dueDate: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			null,
		]),
		null,
	]),
	notes: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		null,
	]),
	workspaceId: faker.number.float({ fractionDigits: 2 }),
	source: faker.helpers.arrayElement([
		{
			...{
				createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
				createdBy: faker.number.float({ fractionDigits: 2 }),
				updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
				updatedBy: faker.number.float({ fractionDigits: 2 }),
				deletedAt: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
						null,
					]),
					null,
				]),
				deletedBy: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.number.float({ fractionDigits: 2 }),
						null,
					]),
					null,
				]),
				id: faker.number.float({ fractionDigits: 2 }),
				name: faker.string.alpha({ length: { min: 10, max: 20 } }),
				date: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
						null,
					]),
					null,
				]),
				workspaceId: faker.number.float({ fractionDigits: 2 }),
				attachmentKey: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					null,
				]),
				attachmentName: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					null,
				]),
				draft: faker.datatype.boolean(),
				extractionStatus: faker.helpers.arrayElement(
					Object.values(ExtractionStatus),
				),
				tags: Array.from(
					{ length: faker.number.int({ min: 1, max: 10 }) },
					(_, i) => i + 1,
				).map(() => ({
					createdAt: new Date(
						faker.date.past().toISOString().slice(0, 19) + "Z",
					),
					createdBy: faker.number.float({ fractionDigits: 2 }),
					updatedAt: new Date(
						faker.date.past().toISOString().slice(0, 19) + "Z",
					),
					updatedBy: faker.number.float({ fractionDigits: 2 }),
					id: faker.number.float({ fractionDigits: 2 }),
					name: faker.string.alpha({ length: { min: 10, max: 20 } }),
					workspaceId: faker.number.float({ fractionDigits: 2 }),
				})),
			},
		},
		null,
	]),
	tags: Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		createdBy: faker.number.float({ fractionDigits: 2 }),
		updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		updatedBy: faker.number.float({ fractionDigits: 2 }),
		id: faker.number.float({ fractionDigits: 2 }),
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		workspaceId: faker.number.float({ fractionDigits: 2 }),
	})),
	assigneeStatuses: Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		assignee: {
			createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			createdBy: faker.number.float({ fractionDigits: 2 }),
			updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			updatedBy: faker.number.float({ fractionDigits: 2 }),
			deletedAt: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
					null,
				]),
				null,
			]),
			deletedBy: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					faker.number.float({ fractionDigits: 2 }),
					null,
				]),
				null,
			]),
			id: faker.number.float({ fractionDigits: 2 }),
			name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			color: faker.string.alpha({ length: { min: 10, max: 20 } }),
			icon: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				null,
			]),
			iconName: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				null,
			]),
			workspaceId: faker.number.float({ fractionDigits: 2 }),
			users: Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				id: faker.number.float({ fractionDigits: 2 }),
				upn: faker.string.alpha({ length: { min: 10, max: 20 } }),
				info: faker.helpers.arrayElement([
					{
						...{
							upn: faker.string.alpha({ length: { min: 10, max: 20 } }),
							displayName: faker.helpers.arrayElement([
								faker.string.alpha({ length: { min: 10, max: 20 } }),
								undefined,
							]),
							name: faker.helpers.arrayElement([
								faker.string.alpha({ length: { min: 10, max: 20 } }),
								undefined,
							]),
							isBI: faker.helpers.arrayElement([
								faker.datatype.boolean(),
								undefined,
							]),
						},
					},
					null,
				]),
			})),
		},
		status: {
			id: faker.number.float({ fractionDigits: 2 }),
			name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			color: faker.string.alpha({ length: { min: 10, max: 20 } }),
			type: faker.helpers.arrayElement(Object.values(WorkspaceStatusType)),
			workspaceId: faker.number.float({ fractionDigits: 2 }),
		},
		description: faker.string.alpha({ length: { min: 10, max: 20 } }),
		editable: faker.datatype.boolean(),
	})),
	workspace: {
		createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		createdBy: faker.number.float({ fractionDigits: 2 }),
		updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		updatedBy: faker.number.float({ fractionDigits: 2 }),
		deletedAt: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
				null,
			]),
			null,
		]),
		deletedBy: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.number.float({ fractionDigits: 2 }),
				null,
			]),
			null,
		]),
		id: faker.number.float({ fractionDigits: 2 }),
		title: faker.string.alpha({ length: { min: 10, max: 20 } }),
		urlName: faker.string.alpha({ length: { min: 10, max: 20 } }),
		icon: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			null,
		]),
		assigneeStatusEditable: faker.datatype.boolean(),
		chatNotification: faker.datatype.boolean(),
		mailNotification: faker.datatype.boolean(),
		pikudId: faker.number.float({ fractionDigits: 2 }),
		permissionType: faker.helpers.arrayElement(Object.values(PermissionType)),
	},
	status: faker.helpers.arrayElement([
		{
			id: faker.number.float({ fractionDigits: 2 }),
			name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			color: faker.string.alpha({ length: { min: 10, max: 20 } }),
			type: faker.helpers.arrayElement(Object.values(WorkspaceStatusType)),
			workspaceId: faker.number.float({ fractionDigits: 2 }),
		},
		undefined,
	]),
	...overrideResponse,
})

export const getUpdateTaskResponseMock = (
	overrideResponse: Partial<Extract<TaskWithWorkspaceDto, object>> = {},
): TaskWithWorkspaceDto => ({
	createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
	createdBy: faker.number.float({ fractionDigits: 2 }),
	updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
	updatedBy: faker.number.float({ fractionDigits: 2 }),
	deletedAt: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			null,
		]),
		null,
	]),
	deletedBy: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.number.float({ fractionDigits: 2 }),
			null,
		]),
		null,
	]),
	id: faker.number.float({ fractionDigits: 2 }),
	title: faker.string.alpha({ length: { min: 10, max: 20 } }),
	description: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		null,
	]),
	flagged: faker.datatype.boolean(),
	deadlineType: faker.helpers.arrayElement(Object.values(DeadlineType)),
	creationType: faker.helpers.arrayElement(Object.values(TaskCreationType)),
	dueDate: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			null,
		]),
		null,
	]),
	notes: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		null,
	]),
	workspaceId: faker.number.float({ fractionDigits: 2 }),
	source: faker.helpers.arrayElement([
		{
			...{
				createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
				createdBy: faker.number.float({ fractionDigits: 2 }),
				updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
				updatedBy: faker.number.float({ fractionDigits: 2 }),
				deletedAt: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
						null,
					]),
					null,
				]),
				deletedBy: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.number.float({ fractionDigits: 2 }),
						null,
					]),
					null,
				]),
				id: faker.number.float({ fractionDigits: 2 }),
				name: faker.string.alpha({ length: { min: 10, max: 20 } }),
				date: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
						null,
					]),
					null,
				]),
				workspaceId: faker.number.float({ fractionDigits: 2 }),
				attachmentKey: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					null,
				]),
				attachmentName: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					null,
				]),
				draft: faker.datatype.boolean(),
				extractionStatus: faker.helpers.arrayElement(
					Object.values(ExtractionStatus),
				),
				tags: Array.from(
					{ length: faker.number.int({ min: 1, max: 10 }) },
					(_, i) => i + 1,
				).map(() => ({
					createdAt: new Date(
						faker.date.past().toISOString().slice(0, 19) + "Z",
					),
					createdBy: faker.number.float({ fractionDigits: 2 }),
					updatedAt: new Date(
						faker.date.past().toISOString().slice(0, 19) + "Z",
					),
					updatedBy: faker.number.float({ fractionDigits: 2 }),
					id: faker.number.float({ fractionDigits: 2 }),
					name: faker.string.alpha({ length: { min: 10, max: 20 } }),
					workspaceId: faker.number.float({ fractionDigits: 2 }),
				})),
			},
		},
		null,
	]),
	tags: Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		createdBy: faker.number.float({ fractionDigits: 2 }),
		updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		updatedBy: faker.number.float({ fractionDigits: 2 }),
		id: faker.number.float({ fractionDigits: 2 }),
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		workspaceId: faker.number.float({ fractionDigits: 2 }),
	})),
	assigneeStatuses: Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		assignee: {
			createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			createdBy: faker.number.float({ fractionDigits: 2 }),
			updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			updatedBy: faker.number.float({ fractionDigits: 2 }),
			deletedAt: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
					null,
				]),
				null,
			]),
			deletedBy: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					faker.number.float({ fractionDigits: 2 }),
					null,
				]),
				null,
			]),
			id: faker.number.float({ fractionDigits: 2 }),
			name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			color: faker.string.alpha({ length: { min: 10, max: 20 } }),
			icon: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				null,
			]),
			iconName: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				null,
			]),
			workspaceId: faker.number.float({ fractionDigits: 2 }),
			users: Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				id: faker.number.float({ fractionDigits: 2 }),
				upn: faker.string.alpha({ length: { min: 10, max: 20 } }),
				info: faker.helpers.arrayElement([
					{
						...{
							upn: faker.string.alpha({ length: { min: 10, max: 20 } }),
							displayName: faker.helpers.arrayElement([
								faker.string.alpha({ length: { min: 10, max: 20 } }),
								undefined,
							]),
							name: faker.helpers.arrayElement([
								faker.string.alpha({ length: { min: 10, max: 20 } }),
								undefined,
							]),
							isBI: faker.helpers.arrayElement([
								faker.datatype.boolean(),
								undefined,
							]),
						},
					},
					null,
				]),
			})),
		},
		status: {
			id: faker.number.float({ fractionDigits: 2 }),
			name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			color: faker.string.alpha({ length: { min: 10, max: 20 } }),
			type: faker.helpers.arrayElement(Object.values(WorkspaceStatusType)),
			workspaceId: faker.number.float({ fractionDigits: 2 }),
		},
		description: faker.string.alpha({ length: { min: 10, max: 20 } }),
		editable: faker.datatype.boolean(),
	})),
	workspace: {
		createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		createdBy: faker.number.float({ fractionDigits: 2 }),
		updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		updatedBy: faker.number.float({ fractionDigits: 2 }),
		deletedAt: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
				null,
			]),
			null,
		]),
		deletedBy: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.number.float({ fractionDigits: 2 }),
				null,
			]),
			null,
		]),
		id: faker.number.float({ fractionDigits: 2 }),
		title: faker.string.alpha({ length: { min: 10, max: 20 } }),
		urlName: faker.string.alpha({ length: { min: 10, max: 20 } }),
		icon: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			null,
		]),
		assigneeStatusEditable: faker.datatype.boolean(),
		chatNotification: faker.datatype.boolean(),
		mailNotification: faker.datatype.boolean(),
		pikudId: faker.number.float({ fractionDigits: 2 }),
		permissionType: faker.helpers.arrayElement(Object.values(PermissionType)),
	},
	...overrideResponse,
})

export const getDeleteTaskResponseMock = (
	overrideResponse: Partial<Extract<TaskWithWorkspaceDto, object>> = {},
): TaskWithWorkspaceDto => ({
	createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
	createdBy: faker.number.float({ fractionDigits: 2 }),
	updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
	updatedBy: faker.number.float({ fractionDigits: 2 }),
	deletedAt: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			null,
		]),
		null,
	]),
	deletedBy: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.number.float({ fractionDigits: 2 }),
			null,
		]),
		null,
	]),
	id: faker.number.float({ fractionDigits: 2 }),
	title: faker.string.alpha({ length: { min: 10, max: 20 } }),
	description: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		null,
	]),
	flagged: faker.datatype.boolean(),
	deadlineType: faker.helpers.arrayElement(Object.values(DeadlineType)),
	creationType: faker.helpers.arrayElement(Object.values(TaskCreationType)),
	dueDate: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			null,
		]),
		null,
	]),
	notes: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		null,
	]),
	workspaceId: faker.number.float({ fractionDigits: 2 }),
	source: faker.helpers.arrayElement([
		{
			...{
				createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
				createdBy: faker.number.float({ fractionDigits: 2 }),
				updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
				updatedBy: faker.number.float({ fractionDigits: 2 }),
				deletedAt: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
						null,
					]),
					null,
				]),
				deletedBy: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.number.float({ fractionDigits: 2 }),
						null,
					]),
					null,
				]),
				id: faker.number.float({ fractionDigits: 2 }),
				name: faker.string.alpha({ length: { min: 10, max: 20 } }),
				date: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
						null,
					]),
					null,
				]),
				workspaceId: faker.number.float({ fractionDigits: 2 }),
				attachmentKey: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					null,
				]),
				attachmentName: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					null,
				]),
				draft: faker.datatype.boolean(),
				extractionStatus: faker.helpers.arrayElement(
					Object.values(ExtractionStatus),
				),
				tags: Array.from(
					{ length: faker.number.int({ min: 1, max: 10 }) },
					(_, i) => i + 1,
				).map(() => ({
					createdAt: new Date(
						faker.date.past().toISOString().slice(0, 19) + "Z",
					),
					createdBy: faker.number.float({ fractionDigits: 2 }),
					updatedAt: new Date(
						faker.date.past().toISOString().slice(0, 19) + "Z",
					),
					updatedBy: faker.number.float({ fractionDigits: 2 }),
					id: faker.number.float({ fractionDigits: 2 }),
					name: faker.string.alpha({ length: { min: 10, max: 20 } }),
					workspaceId: faker.number.float({ fractionDigits: 2 }),
				})),
			},
		},
		null,
	]),
	tags: Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		createdBy: faker.number.float({ fractionDigits: 2 }),
		updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		updatedBy: faker.number.float({ fractionDigits: 2 }),
		id: faker.number.float({ fractionDigits: 2 }),
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		workspaceId: faker.number.float({ fractionDigits: 2 }),
	})),
	assigneeStatuses: Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		assignee: {
			createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			createdBy: faker.number.float({ fractionDigits: 2 }),
			updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			updatedBy: faker.number.float({ fractionDigits: 2 }),
			deletedAt: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
					null,
				]),
				null,
			]),
			deletedBy: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					faker.number.float({ fractionDigits: 2 }),
					null,
				]),
				null,
			]),
			id: faker.number.float({ fractionDigits: 2 }),
			name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			color: faker.string.alpha({ length: { min: 10, max: 20 } }),
			icon: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				null,
			]),
			iconName: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				null,
			]),
			workspaceId: faker.number.float({ fractionDigits: 2 }),
			users: Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				id: faker.number.float({ fractionDigits: 2 }),
				upn: faker.string.alpha({ length: { min: 10, max: 20 } }),
				info: faker.helpers.arrayElement([
					{
						...{
							upn: faker.string.alpha({ length: { min: 10, max: 20 } }),
							displayName: faker.helpers.arrayElement([
								faker.string.alpha({ length: { min: 10, max: 20 } }),
								undefined,
							]),
							name: faker.helpers.arrayElement([
								faker.string.alpha({ length: { min: 10, max: 20 } }),
								undefined,
							]),
							isBI: faker.helpers.arrayElement([
								faker.datatype.boolean(),
								undefined,
							]),
						},
					},
					null,
				]),
			})),
		},
		status: {
			id: faker.number.float({ fractionDigits: 2 }),
			name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			color: faker.string.alpha({ length: { min: 10, max: 20 } }),
			type: faker.helpers.arrayElement(Object.values(WorkspaceStatusType)),
			workspaceId: faker.number.float({ fractionDigits: 2 }),
		},
		description: faker.string.alpha({ length: { min: 10, max: 20 } }),
		editable: faker.datatype.boolean(),
	})),
	workspace: {
		createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		createdBy: faker.number.float({ fractionDigits: 2 }),
		updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		updatedBy: faker.number.float({ fractionDigits: 2 }),
		deletedAt: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
				null,
			]),
			null,
		]),
		deletedBy: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.number.float({ fractionDigits: 2 }),
				null,
			]),
			null,
		]),
		id: faker.number.float({ fractionDigits: 2 }),
		title: faker.string.alpha({ length: { min: 10, max: 20 } }),
		urlName: faker.string.alpha({ length: { min: 10, max: 20 } }),
		icon: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			null,
		]),
		assigneeStatusEditable: faker.datatype.boolean(),
		chatNotification: faker.datatype.boolean(),
		mailNotification: faker.datatype.boolean(),
		pikudId: faker.number.float({ fractionDigits: 2 }),
		permissionType: faker.helpers.arrayElement(Object.values(PermissionType)),
	},
	...overrideResponse,
})

export const getCreateTaskMockHandler = (
	overrideResponse?:
		| TaskWithWorkspaceDto
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<TaskWithWorkspaceDto> | TaskWithWorkspaceDto),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/task",
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getCreateTaskResponseMock(),
				{ status: 201 },
			)
		},
		options,
	)
}

export const getListTasksMockHandler = (
	overrideResponse?:
		| TaskDto[]
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<TaskDto[]> | TaskDto[]),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/task",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getListTasksResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getListTaskRowsMockHandler = (
	overrideResponse?:
		| TaskRowDto[]
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<TaskRowDto[]> | TaskRowDto[]),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/task/rows",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getListTaskRowsResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getListPersonalTasksMockHandler = (
	overrideResponse?:
		| TaskWithWorkspaceDto[]
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<TaskWithWorkspaceDto[]> | TaskWithWorkspaceDto[]),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/task/personal",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getListPersonalTasksResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getListPersonalTaskRowsMockHandler = (
	overrideResponse?:
		| TaskRowWithWorkspaceDto[]
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<TaskRowWithWorkspaceDto[]> | TaskRowWithWorkspaceDto[]),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/task/personal/rows",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getListPersonalTaskRowsResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getGetTaskMockHandler = (
	overrideResponse?:
		| TaskDetailsDto
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<TaskDetailsDto> | TaskDetailsDto),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/task/:id",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getGetTaskResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getUpdateTaskMockHandler = (
	overrideResponse?:
		| TaskWithWorkspaceDto
		| ((
				info: Parameters<Parameters<typeof http.patch>[1]>[0],
		  ) => Promise<TaskWithWorkspaceDto> | TaskWithWorkspaceDto),
	options?: RequestHandlerOptions,
) => {
	return http.patch(
		"*/task/:id",
		async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getUpdateTaskResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getDeleteTaskMockHandler = (
	overrideResponse?:
		| TaskWithWorkspaceDto
		| ((
				info: Parameters<Parameters<typeof http.delete>[1]>[0],
		  ) => Promise<TaskWithWorkspaceDto> | TaskWithWorkspaceDto),
	options?: RequestHandlerOptions,
) => {
	return http.delete(
		"*/task/:id",
		async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getDeleteTaskResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}
export const getTaskMock = () => [
	getCreateTaskMockHandler(),
	getListTasksMockHandler(),
	getListTaskRowsMockHandler(),
	getListPersonalTasksMockHandler(),
	getListPersonalTaskRowsMockHandler(),
	getGetTaskMockHandler(),
	getUpdateTaskMockHandler(),
	getDeleteTaskMockHandler(),
]
