/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */

import type {
	MutationFunction,
	QueryClient,
	UseMutationOptions,
	UseMutationResult,
} from "@tanstack/react-query"
import { useMutation } from "@tanstack/react-query"
import type { ErrorType } from "../../axios"

import { sendRequest } from "../../axios"
import type { UpdateUserEntrieParams } from "../model"

export const updateUserEntrie = (
	params?: UpdateUserEntrieParams,
	signal?: AbortSignal,
) => {
	return sendRequest<void>({
		url: `/user-workspace-entries`,
		method: "PATCH",
		params,
		signal,
	})
}

export const getUpdateUserEntrieMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof updateUserEntrie>>,
		TError,
		{ params?: UpdateUserEntrieParams },
		TContext
	>
}): UseMutationOptions<
	Awaited<ReturnType<typeof updateUserEntrie>>,
	TError,
	{ params?: UpdateUserEntrieParams },
	TContext
> => {
	const mutationKey = ["updateUserEntrie"]
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } }

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof updateUserEntrie>>,
		{ params?: UpdateUserEntrieParams }
	> = (props) => {
		const { params } = props ?? {}

		return updateUserEntrie(params)
	}

	return { mutationFn, ...mutationOptions }
}

export type UpdateUserEntrieMutationResult = NonNullable<
	Awaited<ReturnType<typeof updateUserEntrie>>
>

export type UpdateUserEntrieMutationError = ErrorType<unknown>

export const useUpdateUserEntrie = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof updateUserEntrie>>,
			TError,
			{ params?: UpdateUserEntrieParams },
			TContext
		>
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof updateUserEntrie>>,
	TError,
	{ params?: UpdateUserEntrieParams },
	TContext
> => {
	return useMutation(getUpdateUserEntrieMutationOptions(options), queryClient)
}
