/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query"
import { useMutation, useQuery } from "@tanstack/react-query"
import { apiRequest } from "../../axios"
import type {
	AssigneeUserDto,
	CreateAssigneeUserDto,
	DeleteAssigneeUserPathParameters,
	ListAssigneeUsersPathParameters,
	UpdateAssigneeUserPathParameters,
} from "../model"

export const createAssigneeUser = (
	createAssigneeUserDto: CreateAssigneeUserDto,
	signal?: AbortSignal,
) => {
	return apiRequest<AssigneeUserDto>({
		url: `/assignee-user`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: createAssigneeUserDto,
		signal,
	})
}

export const getCreateAssigneeUserMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof createAssigneeUser>>,
		TError,
		{ data: CreateAssigneeUserDto },
		TContext
	>
}): UseMutationOptions<
	Awaited<ReturnType<typeof createAssigneeUser>>,
	TError,
	{ data: CreateAssigneeUserDto },
	TContext
> => {
	const mutationKey = ["createAssigneeUser"]
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } }

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof createAssigneeUser>>,
		{ data: CreateAssigneeUserDto }
	> = (props) => {
		const { data } = props ?? {}

		return createAssigneeUser(data)
	}

	return { mutationFn, ...mutationOptions }
}

export type CreateAssigneeUserMutationResult = NonNullable<
	Awaited<ReturnType<typeof createAssigneeUser>>
>
export type CreateAssigneeUserMutationBody = CreateAssigneeUserDto
export type CreateAssigneeUserMutationError = unknown

export const useCreateAssigneeUser = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof createAssigneeUser>>,
			TError,
			{ data: CreateAssigneeUserDto },
			TContext
		>
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof createAssigneeUser>>,
	TError,
	{ data: CreateAssigneeUserDto },
	TContext
> => {
	return useMutation(getCreateAssigneeUserMutationOptions(options), queryClient)
}
export const listAssigneeUsers = (
	{ id }: ListAssigneeUsersPathParameters,
	signal?: AbortSignal,
) => {
	return apiRequest<AssigneeUserDto[]>({
		url: `/assignee-user/${id}`,
		method: "GET",
		signal,
	})
}

export const getListAssigneeUsersQueryKey = ({
	id,
}: ListAssigneeUsersPathParameters) => {
	return [`/assignee-user/${id}`] as const
}

export const getListAssigneeUsersQueryOptions = <
	TData = Awaited<ReturnType<typeof listAssigneeUsers>>,
	TError = unknown,
>(
	{ id }: ListAssigneeUsersPathParameters,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof listAssigneeUsers>>,
				TError,
				TData
			>
		>
	},
) => {
	const { query: queryOptions } = options ?? {}

	const queryKey =
		queryOptions?.queryKey ?? getListAssigneeUsersQueryKey({ id })

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof listAssigneeUsers>>
	> = ({ signal }) => listAssigneeUsers({ id }, signal)

	return {
		queryKey,
		queryFn,
		enabled: !!id,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof listAssigneeUsers>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAssigneeUsersQueryResult = NonNullable<
	Awaited<ReturnType<typeof listAssigneeUsers>>
>
export type ListAssigneeUsersQueryError = unknown

export function useListAssigneeUsers<
	TData = Awaited<ReturnType<typeof listAssigneeUsers>>,
	TError = unknown,
>(
	pathParams: ListAssigneeUsersPathParameters,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof listAssigneeUsers>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof listAssigneeUsers>>,
					TError,
					Awaited<ReturnType<typeof listAssigneeUsers>>
				>,
				"initialData"
			>
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}
export function useListAssigneeUsers<
	TData = Awaited<ReturnType<typeof listAssigneeUsers>>,
	TError = unknown,
>(
	pathParams: ListAssigneeUsersPathParameters,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof listAssigneeUsers>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof listAssigneeUsers>>,
					TError,
					Awaited<ReturnType<typeof listAssigneeUsers>>
				>,
				"initialData"
			>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}
export function useListAssigneeUsers<
	TData = Awaited<ReturnType<typeof listAssigneeUsers>>,
	TError = unknown,
>(
	pathParams: ListAssigneeUsersPathParameters,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof listAssigneeUsers>>,
				TError,
				TData
			>
		>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}

export function useListAssigneeUsers<
	TData = Awaited<ReturnType<typeof listAssigneeUsers>>,
	TError = unknown,
>(
	{ id }: ListAssigneeUsersPathParameters,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof listAssigneeUsers>>,
				TError,
				TData
			>
		>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
} {
	const queryOptions = getListAssigneeUsersQueryOptions({ id }, options)

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> }

	return { ...query, queryKey: queryOptions.queryKey }
}

export const updateAssigneeUser = (
	{ assigneeId, userId }: UpdateAssigneeUserPathParameters,
	signal?: AbortSignal,
) => {
	return apiRequest<AssigneeUserDto>({
		url: `/assignee-user/${assigneeId}/${userId}`,
		method: "GET",
		signal,
	})
}

export const getUpdateAssigneeUserQueryKey = ({
	assigneeId,
	userId,
}: UpdateAssigneeUserPathParameters) => {
	return [`/assignee-user/${assigneeId}/${userId}`] as const
}

export const getUpdateAssigneeUserQueryOptions = <
	TData = Awaited<ReturnType<typeof updateAssigneeUser>>,
	TError = unknown,
>(
	{ assigneeId, userId }: UpdateAssigneeUserPathParameters,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof updateAssigneeUser>>,
				TError,
				TData
			>
		>
	},
) => {
	const { query: queryOptions } = options ?? {}

	const queryKey =
		queryOptions?.queryKey ??
		getUpdateAssigneeUserQueryKey({ assigneeId, userId })

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof updateAssigneeUser>>
	> = ({ signal }) => updateAssigneeUser({ assigneeId, userId }, signal)

	return {
		queryKey,
		queryFn,
		enabled: !!(assigneeId && userId),
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof updateAssigneeUser>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UpdateAssigneeUserQueryResult = NonNullable<
	Awaited<ReturnType<typeof updateAssigneeUser>>
>
export type UpdateAssigneeUserQueryError = unknown

export function useUpdateAssigneeUser<
	TData = Awaited<ReturnType<typeof updateAssigneeUser>>,
	TError = unknown,
>(
	pathParams: UpdateAssigneeUserPathParameters,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof updateAssigneeUser>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof updateAssigneeUser>>,
					TError,
					Awaited<ReturnType<typeof updateAssigneeUser>>
				>,
				"initialData"
			>
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}
export function useUpdateAssigneeUser<
	TData = Awaited<ReturnType<typeof updateAssigneeUser>>,
	TError = unknown,
>(
	pathParams: UpdateAssigneeUserPathParameters,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof updateAssigneeUser>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof updateAssigneeUser>>,
					TError,
					Awaited<ReturnType<typeof updateAssigneeUser>>
				>,
				"initialData"
			>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}
export function useUpdateAssigneeUser<
	TData = Awaited<ReturnType<typeof updateAssigneeUser>>,
	TError = unknown,
>(
	pathParams: UpdateAssigneeUserPathParameters,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof updateAssigneeUser>>,
				TError,
				TData
			>
		>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}

export function useUpdateAssigneeUser<
	TData = Awaited<ReturnType<typeof updateAssigneeUser>>,
	TError = unknown,
>(
	{ assigneeId, userId }: UpdateAssigneeUserPathParameters,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof updateAssigneeUser>>,
				TError,
				TData
			>
		>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
} {
	const queryOptions = getUpdateAssigneeUserQueryOptions(
		{ assigneeId, userId },
		options,
	)

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> }

	return { ...query, queryKey: queryOptions.queryKey }
}

export const deleteAssigneeUser = (
	{ assigneeId, userId }: DeleteAssigneeUserPathParameters,
	signal?: AbortSignal,
) => {
	return apiRequest<AssigneeUserDto>({
		url: `/assignee-user/${assigneeId}/${userId}`,
		method: "DELETE",
		signal,
	})
}

export const getDeleteAssigneeUserMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteAssigneeUser>>,
		TError,
		{ pathParams: DeleteAssigneeUserPathParameters },
		TContext
	>
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteAssigneeUser>>,
	TError,
	{ pathParams: DeleteAssigneeUserPathParameters },
	TContext
> => {
	const mutationKey = ["deleteAssigneeUser"]
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } }

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteAssigneeUser>>,
		{ pathParams: DeleteAssigneeUserPathParameters }
	> = (props) => {
		const { pathParams } = props ?? {}

		return deleteAssigneeUser(pathParams)
	}

	return { mutationFn, ...mutationOptions }
}

export type DeleteAssigneeUserMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteAssigneeUser>>
>

export type DeleteAssigneeUserMutationError = unknown

export const useDeleteAssigneeUser = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteAssigneeUser>>,
			TError,
			{ pathParams: DeleteAssigneeUserPathParameters },
			TContext
		>
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof deleteAssigneeUser>>,
	TError,
	{ pathParams: DeleteAssigneeUserPathParameters },
	TContext
> => {
	return useMutation(getDeleteAssigneeUserMutationOptions(options), queryClient)
}
