/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query"
import { useMutation, useQuery } from "@tanstack/react-query"
import type { ErrorType } from "../../axios"

import { sendRequest } from "../../axios"
import type {
	GetUserViewParams,
	UpsertUserViewDto,
	UserViewDto,
} from "../model"

const withQueryKey = <T extends object, K>(
	query: T,
	queryKey: K,
): T & { queryKey: K } => {
	const result = { queryKey } as T & { queryKey: K }
	for (const key of Object.keys(query)) {
		// The explicit queryKey always wins, matching the previous
		// `{ ...query, queryKey }` spread where it was set last.
		if (key === "queryKey") continue
		Object.defineProperty(result, key, {
			enumerable: true,
			configurable: true,
			get: () => (query as Record<string, unknown>)[key],
		})
	}
	return result
}

export const getUserView = (
	params?: GetUserViewParams,
	signal?: AbortSignal,
) => {
	return sendRequest<UserViewDto>({
		url: `/user-views`,
		method: "GET",
		params,
		signal,
	})
}

export const getGetUserViewQueryKey = (params?: GetUserViewParams) => {
	return [`/user-views`, ...(params ? [params] : [])] as const
}

export const getGetUserViewQueryOptions = <
	TData = Awaited<ReturnType<typeof getUserView>>,
	TError = ErrorType<unknown>,
>(
	params?: GetUserViewParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getUserView>>, TError, TData>
		>
	},
) => {
	const { query: queryOptions } = options ?? {}

	const queryKey = queryOptions?.queryKey ?? getGetUserViewQueryKey(params)

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserView>>> = ({
		signal,
	}) => getUserView(params, signal)

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getUserView>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserViewQueryResult = NonNullable<
	Awaited<ReturnType<typeof getUserView>>
>
export type GetUserViewQueryError = ErrorType<unknown>

export function useGetUserView<
	TData = Awaited<ReturnType<typeof getUserView>>,
	TError = ErrorType<unknown>,
>(
	params: undefined | GetUserViewParams,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getUserView>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getUserView>>,
					TError,
					Awaited<ReturnType<typeof getUserView>>
				>,
				"initialData"
			>
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetUserView<
	TData = Awaited<ReturnType<typeof getUserView>>,
	TError = ErrorType<unknown>,
>(
	params?: GetUserViewParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getUserView>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getUserView>>,
					TError,
					Awaited<ReturnType<typeof getUserView>>
				>,
				"initialData"
			>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetUserView<
	TData = Awaited<ReturnType<typeof getUserView>>,
	TError = ErrorType<unknown>,
>(
	params?: GetUserViewParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getUserView>>, TError, TData>
		>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}

export function useGetUserView<
	TData = Awaited<ReturnType<typeof getUserView>>,
	TError = ErrorType<unknown>,
>(
	params?: GetUserViewParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getUserView>>, TError, TData>
		>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
} {
	const queryOptions = getGetUserViewQueryOptions(params, options)

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> }

	return withQueryKey(query, queryOptions.queryKey)
}

export const upsertUserView = (
	upsertUserViewDto: UpsertUserViewDto,
	signal?: AbortSignal,
) => {
	return sendRequest<UserViewDto>({
		url: `/user-views`,
		method: "PATCH",
		headers: { "Content-Type": "application/json" },
		data: upsertUserViewDto,
		signal,
	})
}

export const getUpsertUserViewMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof upsertUserView>>,
		TError,
		{ data: UpsertUserViewDto },
		TContext
	>
}): UseMutationOptions<
	Awaited<ReturnType<typeof upsertUserView>>,
	TError,
	{ data: UpsertUserViewDto },
	TContext
> => {
	const mutationKey = ["upsertUserView"]
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } }

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof upsertUserView>>,
		{ data: UpsertUserViewDto }
	> = (props) => {
		const { data } = props ?? {}

		return upsertUserView(data)
	}

	return { mutationFn, ...mutationOptions }
}

export type UpsertUserViewMutationResult = NonNullable<
	Awaited<ReturnType<typeof upsertUserView>>
>
export type UpsertUserViewMutationBody = UpsertUserViewDto
export type UpsertUserViewMutationError = ErrorType<unknown>

export const useUpsertUserView = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof upsertUserView>>,
			TError,
			{ data: UpsertUserViewDto },
			TContext
		>
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof upsertUserView>>,
	TError,
	{ data: UpsertUserViewDto },
	TContext
> => {
	return useMutation(getUpsertUserViewMutationOptions(options), queryClient)
}
