/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */

import type { RequestHandlerOptions } from "msw"
import { HttpResponse, http } from "msw"

export const getToggleUserTaskArchiveMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.patch>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.patch(
		"*/archived-user-assignee-task/:id",
		async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
			if (typeof overrideResponse === "function") {
				await overrideResponse(info)
			}

			return new HttpResponse(null, { status: 200 })
		},
		options,
	)
}
export const getArchivedUserAssigneeTaskMock = () => [
	getToggleUserTaskArchiveMockHandler(),
]
