/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query"
import { useMutation, useQuery } from "@tanstack/react-query"
import { apiRequest } from "../../axios"
import type {
	DeletePermissionParams,
	GetMyPermissionParams,
	GetPermissionsParams,
	PermissionDto,
	UpdatePermissionDto,
} from "../model"

export const getPermissions = (
	params: GetPermissionsParams,
	signal?: AbortSignal,
) => {
	return apiRequest<PermissionDto[]>({
		url: `/permission`,
		method: "GET",
		params,
		signal,
	})
}

export const getGetPermissionsQueryKey = (params?: GetPermissionsParams) => {
	return [`/permission`, ...(params ? [params] : [])] as const
}

export const getGetPermissionsQueryOptions = <
	TData = Awaited<ReturnType<typeof getPermissions>>,
	TError = unknown,
>(
	params: GetPermissionsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getPermissions>>, TError, TData>
		>
	},
) => {
	const { query: queryOptions } = options ?? {}

	const queryKey = queryOptions?.queryKey ?? getGetPermissionsQueryKey(params)

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getPermissions>>> = ({
		signal,
	}) => getPermissions(params, signal)

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getPermissions>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPermissionsQueryResult = NonNullable<
	Awaited<ReturnType<typeof getPermissions>>
>
export type GetPermissionsQueryError = unknown

export function useGetPermissions<
	TData = Awaited<ReturnType<typeof getPermissions>>,
	TError = unknown,
>(
	params: GetPermissionsParams,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getPermissions>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getPermissions>>,
					TError,
					Awaited<ReturnType<typeof getPermissions>>
				>,
				"initialData"
			>
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetPermissions<
	TData = Awaited<ReturnType<typeof getPermissions>>,
	TError = unknown,
>(
	params: GetPermissionsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getPermissions>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getPermissions>>,
					TError,
					Awaited<ReturnType<typeof getPermissions>>
				>,
				"initialData"
			>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetPermissions<
	TData = Awaited<ReturnType<typeof getPermissions>>,
	TError = unknown,
>(
	params: GetPermissionsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getPermissions>>, TError, TData>
		>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}

export function useGetPermissions<
	TData = Awaited<ReturnType<typeof getPermissions>>,
	TError = unknown,
>(
	params: GetPermissionsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getPermissions>>, TError, TData>
		>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
} {
	const queryOptions = getGetPermissionsQueryOptions(params, options)

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> }

	return { ...query, queryKey: queryOptions.queryKey }
}

export const updatePermission = (
	updatePermissionDto: UpdatePermissionDto,
	signal?: AbortSignal,
) => {
	return apiRequest<PermissionDto>({
		url: `/permission`,
		method: "PATCH",
		headers: { "Content-Type": "application/json" },
		data: updatePermissionDto,
		signal,
	})
}

export const getUpdatePermissionMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof updatePermission>>,
		TError,
		{ data: UpdatePermissionDto },
		TContext
	>
}): UseMutationOptions<
	Awaited<ReturnType<typeof updatePermission>>,
	TError,
	{ data: UpdatePermissionDto },
	TContext
> => {
	const mutationKey = ["updatePermission"]
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } }

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof updatePermission>>,
		{ data: UpdatePermissionDto }
	> = (props) => {
		const { data } = props ?? {}

		return updatePermission(data)
	}

	return { mutationFn, ...mutationOptions }
}

export type UpdatePermissionMutationResult = NonNullable<
	Awaited<ReturnType<typeof updatePermission>>
>
export type UpdatePermissionMutationBody = UpdatePermissionDto
export type UpdatePermissionMutationError = unknown

export const useUpdatePermission = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof updatePermission>>,
			TError,
			{ data: UpdatePermissionDto },
			TContext
		>
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof updatePermission>>,
	TError,
	{ data: UpdatePermissionDto },
	TContext
> => {
	return useMutation(getUpdatePermissionMutationOptions(options), queryClient)
}
export const deletePermission = (
	params: DeletePermissionParams,
	signal?: AbortSignal,
) => {
	return apiRequest<PermissionDto>({
		url: `/permission`,
		method: "DELETE",
		params,
		signal,
	})
}

export const getDeletePermissionMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deletePermission>>,
		TError,
		{ params: DeletePermissionParams },
		TContext
	>
}): UseMutationOptions<
	Awaited<ReturnType<typeof deletePermission>>,
	TError,
	{ params: DeletePermissionParams },
	TContext
> => {
	const mutationKey = ["deletePermission"]
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } }

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deletePermission>>,
		{ params: DeletePermissionParams }
	> = (props) => {
		const { params } = props ?? {}

		return deletePermission(params)
	}

	return { mutationFn, ...mutationOptions }
}

export type DeletePermissionMutationResult = NonNullable<
	Awaited<ReturnType<typeof deletePermission>>
>

export type DeletePermissionMutationError = unknown

export const useDeletePermission = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deletePermission>>,
			TError,
			{ params: DeletePermissionParams },
			TContext
		>
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof deletePermission>>,
	TError,
	{ params: DeletePermissionParams },
	TContext
> => {
	return useMutation(getDeletePermissionMutationOptions(options), queryClient)
}
export const getMyPermission = (
	params: GetMyPermissionParams,
	signal?: AbortSignal,
) => {
	return apiRequest<PermissionDto>({
		url: `/permission/me`,
		method: "GET",
		params,
		signal,
	})
}

export const getGetMyPermissionQueryKey = (params?: GetMyPermissionParams) => {
	return [`/permission/me`, ...(params ? [params] : [])] as const
}

export const getGetMyPermissionQueryOptions = <
	TData = Awaited<ReturnType<typeof getMyPermission>>,
	TError = unknown,
>(
	params: GetMyPermissionParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getMyPermission>>,
				TError,
				TData
			>
		>
	},
) => {
	const { query: queryOptions } = options ?? {}

	const queryKey = queryOptions?.queryKey ?? getGetMyPermissionQueryKey(params)

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyPermission>>> = ({
		signal,
	}) => getMyPermission(params, signal)

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getMyPermission>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMyPermissionQueryResult = NonNullable<
	Awaited<ReturnType<typeof getMyPermission>>
>
export type GetMyPermissionQueryError = unknown

export function useGetMyPermission<
	TData = Awaited<ReturnType<typeof getMyPermission>>,
	TError = unknown,
>(
	params: GetMyPermissionParams,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getMyPermission>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getMyPermission>>,
					TError,
					Awaited<ReturnType<typeof getMyPermission>>
				>,
				"initialData"
			>
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetMyPermission<
	TData = Awaited<ReturnType<typeof getMyPermission>>,
	TError = unknown,
>(
	params: GetMyPermissionParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getMyPermission>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getMyPermission>>,
					TError,
					Awaited<ReturnType<typeof getMyPermission>>
				>,
				"initialData"
			>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetMyPermission<
	TData = Awaited<ReturnType<typeof getMyPermission>>,
	TError = unknown,
>(
	params: GetMyPermissionParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getMyPermission>>,
				TError,
				TData
			>
		>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}

export function useGetMyPermission<
	TData = Awaited<ReturnType<typeof getMyPermission>>,
	TError = unknown,
>(
	params: GetMyPermissionParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getMyPermission>>,
				TError,
				TData
			>
		>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
} {
	const queryOptions = getGetMyPermissionQueryOptions(params, options)

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> }

	return { ...query, queryKey: queryOptions.queryKey }
}
