/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */
import { faker } from "@faker-js/faker"
import type { RequestHandlerOptions } from "msw"
import { HttpResponse, http } from "msw"

import type { MirageUserDto, UserDto } from "../model"

export const getCreateUserResponseMock = (
	overrideResponse: Partial<Extract<UserDto, object>> = {},
): UserDto => ({
	id: faker.number.float({ fractionDigits: 2 }),
	upn: faker.string.alpha({ length: { min: 10, max: 20 } }),
	info: faker.helpers.arrayElement([
		{
			...{
				upn: faker.string.alpha({ length: { min: 10, max: 20 } }),
				displayName: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					null,
				]),
				name: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					null,
				]),
				isBI: faker.helpers.arrayElement([faker.datatype.boolean(), null]),
			},
		},
		null,
	]),
	...overrideResponse,
})

export const getListUsersResponseMock = (): UserDto[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		id: faker.number.float({ fractionDigits: 2 }),
		upn: faker.string.alpha({ length: { min: 10, max: 20 } }),
		info: faker.helpers.arrayElement([
			{
				...{
					upn: faker.string.alpha({ length: { min: 10, max: 20 } }),
					displayName: faker.helpers.arrayElement([
						faker.helpers.arrayElement([
							faker.string.alpha({ length: { min: 10, max: 20 } }),
							null,
						]),
						null,
					]),
					name: faker.helpers.arrayElement([
						faker.helpers.arrayElement([
							faker.string.alpha({ length: { min: 10, max: 20 } }),
							null,
						]),
						null,
					]),
					isBI: faker.helpers.arrayElement([faker.datatype.boolean(), null]),
				},
			},
			null,
		]),
	}))

export const getSearchUsersResponseMock = (): MirageUserDto[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		upn: faker.string.alpha({ length: { min: 10, max: 20 } }),
		info: faker.helpers.arrayElement([
			{
				...{
					upn: faker.string.alpha({ length: { min: 10, max: 20 } }),
					displayName: faker.helpers.arrayElement([
						faker.helpers.arrayElement([
							faker.string.alpha({ length: { min: 10, max: 20 } }),
							null,
						]),
						null,
					]),
					name: faker.helpers.arrayElement([
						faker.helpers.arrayElement([
							faker.string.alpha({ length: { min: 10, max: 20 } }),
							null,
						]),
						null,
					]),
					isBI: faker.helpers.arrayElement([faker.datatype.boolean(), null]),
				},
			},
			null,
		]),
	}))

export const getGetUserResponseMock = (
	overrideResponse: Partial<Extract<UserDto, object>> = {},
): UserDto => ({
	id: faker.number.float({ fractionDigits: 2 }),
	upn: faker.string.alpha({ length: { min: 10, max: 20 } }),
	info: faker.helpers.arrayElement([
		{
			...{
				upn: faker.string.alpha({ length: { min: 10, max: 20 } }),
				displayName: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					null,
				]),
				name: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					null,
				]),
				isBI: faker.helpers.arrayElement([faker.datatype.boolean(), null]),
			},
		},
		null,
	]),
	...overrideResponse,
})

export const getUpdateUserResponseMock = (
	overrideResponse: Partial<Extract<UserDto, object>> = {},
): UserDto => ({
	id: faker.number.float({ fractionDigits: 2 }),
	upn: faker.string.alpha({ length: { min: 10, max: 20 } }),
	info: faker.helpers.arrayElement([
		{
			...{
				upn: faker.string.alpha({ length: { min: 10, max: 20 } }),
				displayName: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					null,
				]),
				name: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					null,
				]),
				isBI: faker.helpers.arrayElement([faker.datatype.boolean(), null]),
			},
		},
		null,
	]),
	...overrideResponse,
})

export const getDeleteUserResponseMock = (
	overrideResponse: Partial<Extract<UserDto, object>> = {},
): UserDto => ({
	id: faker.number.float({ fractionDigits: 2 }),
	upn: faker.string.alpha({ length: { min: 10, max: 20 } }),
	info: faker.helpers.arrayElement([
		{
			...{
				upn: faker.string.alpha({ length: { min: 10, max: 20 } }),
				displayName: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					null,
				]),
				name: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					null,
				]),
				isBI: faker.helpers.arrayElement([faker.datatype.boolean(), null]),
			},
		},
		null,
	]),
	...overrideResponse,
})

export const getCreateUserMockHandler = (
	overrideResponse?:
		| UserDto
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<UserDto> | UserDto),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/user",
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getCreateUserResponseMock(),
				{ status: 201 },
			)
		},
		options,
	)
}

export const getListUsersMockHandler = (
	overrideResponse?:
		| UserDto[]
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<UserDto[]> | UserDto[]),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/user",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getListUsersResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getSearchUsersMockHandler = (
	overrideResponse?:
		| MirageUserDto[]
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<MirageUserDto[]> | MirageUserDto[]),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/user/search",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getSearchUsersResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getGetUserMockHandler = (
	overrideResponse?:
		| UserDto
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<UserDto> | UserDto),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/user/:id",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getGetUserResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getUpdateUserMockHandler = (
	overrideResponse?:
		| UserDto
		| ((
				info: Parameters<Parameters<typeof http.patch>[1]>[0],
		  ) => Promise<UserDto> | UserDto),
	options?: RequestHandlerOptions,
) => {
	return http.patch(
		"*/user/:id",
		async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getUpdateUserResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getDeleteUserMockHandler = (
	overrideResponse?:
		| UserDto
		| ((
				info: Parameters<Parameters<typeof http.delete>[1]>[0],
		  ) => Promise<UserDto> | UserDto),
	options?: RequestHandlerOptions,
) => {
	return http.delete(
		"*/user/:id",
		async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getDeleteUserResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}
export const getUserMock = () => [
	getCreateUserMockHandler(),
	getListUsersMockHandler(),
	getSearchUsersMockHandler(),
	getGetUserMockHandler(),
	getUpdateUserMockHandler(),
	getDeleteUserMockHandler(),
]
