/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query"
import { useMutation, useQuery } from "@tanstack/react-query"
import type { ErrorType } from "../../axios.ts"

import { sendRequest } from "../../axios.ts"
import type {
	CreateUserDto,
	DeleteUserPathParameters,
	GetUserPathParameters,
	MirageUserDto,
	SearchUsersParams,
	UpdateUserDto,
	UpdateUserPathParameters,
	UserDto,
} from "../model"

const withQueryKey = <T extends object, K>(
	query: T,
	queryKey: K,
): T & { queryKey: K } => {
	const result = { queryKey } as T & { queryKey: K }
	for (const key of Object.keys(query)) {
		// The explicit queryKey always wins, matching the previous
		// `{ ...query, queryKey }` spread where it was set last.
		if (key === "queryKey") continue
		Object.defineProperty(result, key, {
			enumerable: true,
			configurable: true,
			get: () => (query as Record<string, unknown>)[key],
		})
	}
	return result
}

export const createUser = (
	createUserDto: CreateUserDto,
	signal?: AbortSignal,
) => {
	return sendRequest<UserDto>({
		url: `/user`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: createUserDto,
		signal,
	})
}

export const getCreateUserMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof createUser>>,
		TError,
		{ data: CreateUserDto },
		TContext
	>
}): UseMutationOptions<
	Awaited<ReturnType<typeof createUser>>,
	TError,
	{ data: CreateUserDto },
	TContext
> => {
	const mutationKey = ["createUser"]
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } }

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof createUser>>,
		{ data: CreateUserDto }
	> = (props) => {
		const { data } = props ?? {}

		return createUser(data)
	}

	return { mutationFn, ...mutationOptions }
}

export type CreateUserMutationResult = NonNullable<
	Awaited<ReturnType<typeof createUser>>
>
export type CreateUserMutationBody = CreateUserDto
export type CreateUserMutationError = ErrorType<unknown>

export const useCreateUser = <TError = ErrorType<unknown>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof createUser>>,
			TError,
			{ data: CreateUserDto },
			TContext
		>
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof createUser>>,
	TError,
	{ data: CreateUserDto },
	TContext
> => {
	return useMutation(getCreateUserMutationOptions(options), queryClient)
}
export const listUsers = (signal?: AbortSignal) => {
	return sendRequest<UserDto[]>({ url: `/user`, method: "GET", signal })
}

export const getListUsersQueryKey = () => {
	return [`/user`] as const
}

export const getListUsersQueryOptions = <
	TData = Awaited<ReturnType<typeof listUsers>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>
	>
}) => {
	const { query: queryOptions } = options ?? {}

	const queryKey = queryOptions?.queryKey ?? getListUsersQueryKey()

	const queryFn: QueryFunction<Awaited<ReturnType<typeof listUsers>>> = ({
		signal,
	}) => listUsers(signal)

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof listUsers>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListUsersQueryResult = NonNullable<
	Awaited<ReturnType<typeof listUsers>>
>
export type ListUsersQueryError = ErrorType<unknown>

export function useListUsers<
	TData = Awaited<ReturnType<typeof listUsers>>,
	TError = ErrorType<unknown>,
>(
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof listUsers>>,
					TError,
					Awaited<ReturnType<typeof listUsers>>
				>,
				"initialData"
			>
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}
export function useListUsers<
	TData = Awaited<ReturnType<typeof listUsers>>,
	TError = ErrorType<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof listUsers>>,
					TError,
					Awaited<ReturnType<typeof listUsers>>
				>,
				"initialData"
			>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}
export function useListUsers<
	TData = Awaited<ReturnType<typeof listUsers>>,
	TError = ErrorType<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>
		>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}

export function useListUsers<
	TData = Awaited<ReturnType<typeof listUsers>>,
	TError = ErrorType<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>
		>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
} {
	const queryOptions = getListUsersQueryOptions(options)

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> }

	return withQueryKey(query, queryOptions.queryKey)
}

export const searchUsers = (
	params: SearchUsersParams,
	signal?: AbortSignal,
) => {
	return sendRequest<MirageUserDto[]>({
		url: `/user/search`,
		method: "GET",
		params,
		signal,
	})
}

export const getSearchUsersQueryKey = (params?: SearchUsersParams) => {
	return [`/user/search`, ...(params ? [params] : [])] as const
}

export const getSearchUsersQueryOptions = <
	TData = Awaited<ReturnType<typeof searchUsers>>,
	TError = ErrorType<unknown>,
>(
	params: SearchUsersParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof searchUsers>>, TError, TData>
		>
	},
) => {
	const { query: queryOptions } = options ?? {}

	const queryKey = queryOptions?.queryKey ?? getSearchUsersQueryKey(params)

	const queryFn: QueryFunction<Awaited<ReturnType<typeof searchUsers>>> = ({
		signal,
	}) => searchUsers(params, signal)

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof searchUsers>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchUsersQueryResult = NonNullable<
	Awaited<ReturnType<typeof searchUsers>>
>
export type SearchUsersQueryError = ErrorType<unknown>

export function useSearchUsers<
	TData = Awaited<ReturnType<typeof searchUsers>>,
	TError = ErrorType<unknown>,
>(
	params: SearchUsersParams,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof searchUsers>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof searchUsers>>,
					TError,
					Awaited<ReturnType<typeof searchUsers>>
				>,
				"initialData"
			>
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}
export function useSearchUsers<
	TData = Awaited<ReturnType<typeof searchUsers>>,
	TError = ErrorType<unknown>,
>(
	params: SearchUsersParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof searchUsers>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof searchUsers>>,
					TError,
					Awaited<ReturnType<typeof searchUsers>>
				>,
				"initialData"
			>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}
export function useSearchUsers<
	TData = Awaited<ReturnType<typeof searchUsers>>,
	TError = ErrorType<unknown>,
>(
	params: SearchUsersParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof searchUsers>>, TError, TData>
		>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}

export function useSearchUsers<
	TData = Awaited<ReturnType<typeof searchUsers>>,
	TError = ErrorType<unknown>,
>(
	params: SearchUsersParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof searchUsers>>, TError, TData>
		>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
} {
	const queryOptions = getSearchUsersQueryOptions(params, options)

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> }

	return withQueryKey(query, queryOptions.queryKey)
}

export const getUser = (
	{ id }: GetUserPathParameters,
	signal?: AbortSignal,
) => {
	return sendRequest<UserDto>({ url: `/user/${id}`, method: "GET", signal })
}

export const getGetUserQueryKey = ({ id }: GetUserPathParameters) => {
	return [`/user/${id}`] as const
}

export const getGetUserQueryOptions = <
	TData = Awaited<ReturnType<typeof getUser>>,
	TError = ErrorType<unknown>,
>(
	{ id }: GetUserPathParameters,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>
		>
	},
) => {
	const { query: queryOptions } = options ?? {}

	const queryKey = queryOptions?.queryKey ?? getGetUserQueryKey({ id })

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getUser>>> = ({
		signal,
	}) => getUser({ id }, signal)

	return {
		queryKey,
		queryFn,
		enabled: id !== null && id !== undefined,
		...queryOptions,
	} as UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>
	}
}

export type GetUserQueryResult = NonNullable<
	Awaited<ReturnType<typeof getUser>>
>
export type GetUserQueryError = ErrorType<unknown>

export function useGetUser<
	TData = Awaited<ReturnType<typeof getUser>>,
	TError = ErrorType<unknown>,
>(
	pathParams: GetUserPathParameters,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getUser>>,
					TError,
					Awaited<ReturnType<typeof getUser>>
				>,
				"initialData"
			>
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetUser<
	TData = Awaited<ReturnType<typeof getUser>>,
	TError = ErrorType<unknown>,
>(
	pathParams: GetUserPathParameters,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getUser>>,
					TError,
					Awaited<ReturnType<typeof getUser>>
				>,
				"initialData"
			>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetUser<
	TData = Awaited<ReturnType<typeof getUser>>,
	TError = ErrorType<unknown>,
>(
	pathParams: GetUserPathParameters,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>
		>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}

export function useGetUser<
	TData = Awaited<ReturnType<typeof getUser>>,
	TError = ErrorType<unknown>,
>(
	{ id }: GetUserPathParameters,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>
		>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
} {
	const queryOptions = getGetUserQueryOptions({ id }, options)

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> }

	return withQueryKey(query, queryOptions.queryKey)
}

export const updateUser = (
	{ id }: UpdateUserPathParameters,
	updateUserDto: UpdateUserDto,
	signal?: AbortSignal,
) => {
	return sendRequest<UserDto>({
		url: `/user/${id}`,
		method: "PATCH",
		headers: { "Content-Type": "application/json" },
		data: updateUserDto,
		signal,
	})
}

export const getUpdateUserMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof updateUser>>,
		TError,
		{ pathParams: UpdateUserPathParameters; data: UpdateUserDto },
		TContext
	>
}): UseMutationOptions<
	Awaited<ReturnType<typeof updateUser>>,
	TError,
	{ pathParams: UpdateUserPathParameters; data: UpdateUserDto },
	TContext
> => {
	const mutationKey = ["updateUser"]
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } }

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof updateUser>>,
		{ pathParams: UpdateUserPathParameters; data: UpdateUserDto }
	> = (props) => {
		const { pathParams, data } = props ?? {}

		return updateUser(pathParams, data)
	}

	return { mutationFn, ...mutationOptions }
}

export type UpdateUserMutationResult = NonNullable<
	Awaited<ReturnType<typeof updateUser>>
>
export type UpdateUserMutationBody = UpdateUserDto
export type UpdateUserMutationError = ErrorType<unknown>

export const useUpdateUser = <TError = ErrorType<unknown>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof updateUser>>,
			TError,
			{ pathParams: UpdateUserPathParameters; data: UpdateUserDto },
			TContext
		>
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof updateUser>>,
	TError,
	{ pathParams: UpdateUserPathParameters; data: UpdateUserDto },
	TContext
> => {
	return useMutation(getUpdateUserMutationOptions(options), queryClient)
}
export const deleteUser = (
	{ id }: DeleteUserPathParameters,
	signal?: AbortSignal,
) => {
	return sendRequest<UserDto>({ url: `/user/${id}`, method: "DELETE", signal })
}

export const getDeleteUserMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteUser>>,
		TError,
		{ pathParams: DeleteUserPathParameters },
		TContext
	>
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteUser>>,
	TError,
	{ pathParams: DeleteUserPathParameters },
	TContext
> => {
	const mutationKey = ["deleteUser"]
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } }

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteUser>>,
		{ pathParams: DeleteUserPathParameters }
	> = (props) => {
		const { pathParams } = props ?? {}

		return deleteUser(pathParams)
	}

	return { mutationFn, ...mutationOptions }
}

export type DeleteUserMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteUser>>
>

export type DeleteUserMutationError = ErrorType<unknown>

export const useDeleteUser = <TError = ErrorType<unknown>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteUser>>,
			TError,
			{ pathParams: DeleteUserPathParameters },
			TContext
		>
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof deleteUser>>,
	TError,
	{ pathParams: DeleteUserPathParameters },
	TContext
> => {
	return useMutation(getDeleteUserMutationOptions(options), queryClient)
}
