/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */
import { faker } from "@faker-js/faker"
import type { RequestHandlerOptions } from "msw"
import { HttpResponse, http } from "msw"
import type { SourceDto, SourceWithTasksDto } from "../model"
import {
	DeadlineType,
	ExtractionStatus,
	TaskCreationType,
	WorkspaceStatusType,
} from "../model"

export const getCreateSourceResponseMock = (
	overrideResponse: Partial<Extract<SourceDto, object>> = {},
): SourceDto => ({
	createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
	createdBy: faker.number.float({ fractionDigits: 2 }),
	updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
	updatedBy: faker.number.float({ fractionDigits: 2 }),
	deletedAt: faker.helpers.arrayElement([
		new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		null,
	]),
	deletedBy: faker.helpers.arrayElement([
		faker.number.float({ fractionDigits: 2 }),
		null,
	]),
	id: faker.number.float({ fractionDigits: 2 }),
	name: faker.string.alpha({ length: { min: 10, max: 20 } }),
	date: faker.helpers.arrayElement([
		new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		null,
	]),
	workspaceId: faker.number.float({ fractionDigits: 2 }),
	attachmentKey: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		null,
	]),
	attachmentName: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		null,
	]),
	draft: faker.datatype.boolean(),
	extractionStatus: faker.helpers.arrayElement([
		faker.helpers.arrayElement(Object.values(ExtractionStatus)),
		null,
	]),
	tags: Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		createdBy: faker.number.float({ fractionDigits: 2 }),
		updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		updatedBy: faker.number.float({ fractionDigits: 2 }),
		id: faker.number.float({ fractionDigits: 2 }),
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		workspaceId: faker.number.float({ fractionDigits: 2 }),
	})),
	...overrideResponse,
})

export const getListSourcesResponseMock = (): SourceDto[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		createdBy: faker.number.float({ fractionDigits: 2 }),
		updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		updatedBy: faker.number.float({ fractionDigits: 2 }),
		deletedAt: faker.helpers.arrayElement([
			new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			null,
		]),
		deletedBy: faker.helpers.arrayElement([
			faker.number.float({ fractionDigits: 2 }),
			null,
		]),
		id: faker.number.float({ fractionDigits: 2 }),
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		date: faker.helpers.arrayElement([
			new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			null,
		]),
		workspaceId: faker.number.float({ fractionDigits: 2 }),
		attachmentKey: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		attachmentName: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		draft: faker.datatype.boolean(),
		extractionStatus: faker.helpers.arrayElement([
			faker.helpers.arrayElement(Object.values(ExtractionStatus)),
			null,
		]),
		tags: Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			createdBy: faker.number.float({ fractionDigits: 2 }),
			updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			updatedBy: faker.number.float({ fractionDigits: 2 }),
			id: faker.number.float({ fractionDigits: 2 }),
			name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			workspaceId: faker.number.float({ fractionDigits: 2 }),
		})),
	}))

export const getGetSourceResponseMock = (
	overrideResponse: Partial<Extract<SourceWithTasksDto, object>> = {},
): SourceWithTasksDto => ({
	createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
	createdBy: faker.number.float({ fractionDigits: 2 }),
	updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
	updatedBy: faker.number.float({ fractionDigits: 2 }),
	deletedAt: faker.helpers.arrayElement([
		new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		null,
	]),
	deletedBy: faker.helpers.arrayElement([
		faker.number.float({ fractionDigits: 2 }),
		null,
	]),
	id: faker.number.float({ fractionDigits: 2 }),
	name: faker.string.alpha({ length: { min: 10, max: 20 } }),
	date: faker.helpers.arrayElement([
		new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		null,
	]),
	workspaceId: faker.number.float({ fractionDigits: 2 }),
	attachmentKey: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		null,
	]),
	attachmentName: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		null,
	]),
	draft: faker.datatype.boolean(),
	extractionStatus: faker.helpers.arrayElement([
		faker.helpers.arrayElement(Object.values(ExtractionStatus)),
		null,
	]),
	tags: Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		createdBy: faker.number.float({ fractionDigits: 2 }),
		updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		updatedBy: faker.number.float({ fractionDigits: 2 }),
		id: faker.number.float({ fractionDigits: 2 }),
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		workspaceId: faker.number.float({ fractionDigits: 2 }),
	})),
	tasks: Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		createdBy: faker.number.float({ fractionDigits: 2 }),
		updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		updatedBy: faker.number.float({ fractionDigits: 2 }),
		deletedAt: faker.helpers.arrayElement([
			new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			null,
		]),
		deletedBy: faker.helpers.arrayElement([
			faker.number.float({ fractionDigits: 2 }),
			null,
		]),
		id: faker.number.float({ fractionDigits: 2 }),
		title: faker.string.alpha({ length: { min: 10, max: 20 } }),
		description: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		flagged: faker.datatype.boolean(),
		deadlineType: faker.helpers.arrayElement(Object.values(DeadlineType)),
		creationType: faker.helpers.arrayElement(Object.values(TaskCreationType)),
		dueDate: faker.helpers.arrayElement([
			new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			null,
		]),
		notes: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		workspaceId: faker.number.float({ fractionDigits: 2 }),
		source: faker.helpers.arrayElement([
			{
				...{
					createdAt: new Date(
						faker.date.past().toISOString().slice(0, 19) + "Z",
					),
					createdBy: faker.number.float({ fractionDigits: 2 }),
					updatedAt: new Date(
						faker.date.past().toISOString().slice(0, 19) + "Z",
					),
					updatedBy: faker.number.float({ fractionDigits: 2 }),
					deletedAt: faker.helpers.arrayElement([
						new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
						null,
					]),
					deletedBy: faker.helpers.arrayElement([
						faker.number.float({ fractionDigits: 2 }),
						null,
					]),
					id: faker.number.float({ fractionDigits: 2 }),
					name: faker.string.alpha({ length: { min: 10, max: 20 } }),
					date: faker.helpers.arrayElement([
						new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
						null,
					]),
					workspaceId: faker.number.float({ fractionDigits: 2 }),
					attachmentKey: faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					attachmentName: faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					draft: faker.datatype.boolean(),
					extractionStatus: faker.helpers.arrayElement([
						faker.helpers.arrayElement(Object.values(ExtractionStatus)),
						null,
					]),
					tags: Array.from(
						{ length: faker.number.int({ min: 1, max: 10 }) },
						(_, i) => i + 1,
					).map(() => ({
						createdAt: new Date(
							faker.date.past().toISOString().slice(0, 19) + "Z",
						),
						createdBy: faker.number.float({ fractionDigits: 2 }),
						updatedAt: new Date(
							faker.date.past().toISOString().slice(0, 19) + "Z",
						),
						updatedBy: faker.number.float({ fractionDigits: 2 }),
						id: faker.number.float({ fractionDigits: 2 }),
						name: faker.string.alpha({ length: { min: 10, max: 20 } }),
						workspaceId: faker.number.float({ fractionDigits: 2 }),
					})),
				},
			},
			null,
		]),
		tags: Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			createdBy: faker.number.float({ fractionDigits: 2 }),
			updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			updatedBy: faker.number.float({ fractionDigits: 2 }),
			id: faker.number.float({ fractionDigits: 2 }),
			name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			workspaceId: faker.number.float({ fractionDigits: 2 }),
		})),
		lastMessage: {
			createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			createdBy: faker.number.float({ fractionDigits: 2 }),
			updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			updatedBy: faker.number.float({ fractionDigits: 2 }),
			deletedAt: faker.helpers.arrayElement([
				new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
				null,
			]),
			deletedBy: faker.helpers.arrayElement([
				faker.number.float({ fractionDigits: 2 }),
				null,
			]),
			id: faker.number.float({ fractionDigits: 2 }),
			content: faker.string.alpha({ length: { min: 10, max: 20 } }),
			user: {
				id: faker.number.float({ fractionDigits: 2 }),
				upn: faker.string.alpha({ length: { min: 10, max: 20 } }),
				info: faker.helpers.arrayElement([
					{
						...{
							upn: faker.string.alpha({ length: { min: 10, max: 20 } }),
							displayName: faker.helpers.arrayElement([
								faker.string.alpha({ length: { min: 10, max: 20 } }),
								undefined,
							]),
							name: faker.helpers.arrayElement([
								faker.string.alpha({ length: { min: 10, max: 20 } }),
								undefined,
							]),
							isBI: faker.helpers.arrayElement([
								faker.datatype.boolean(),
								undefined,
							]),
						},
					},
					null,
				]),
			},
			taskId: faker.number.float({ fractionDigits: 2 }),
		},
		messageCount: faker.number.float({ fractionDigits: 2 }),
		assigneeStatuses: Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			assignee: {
				createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
				createdBy: faker.number.float({ fractionDigits: 2 }),
				updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
				updatedBy: faker.number.float({ fractionDigits: 2 }),
				deletedAt: faker.helpers.arrayElement([
					new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
					null,
				]),
				deletedBy: faker.helpers.arrayElement([
					faker.number.float({ fractionDigits: 2 }),
					null,
				]),
				id: faker.number.float({ fractionDigits: 2 }),
				name: faker.string.alpha({ length: { min: 10, max: 20 } }),
				color: faker.string.alpha({ length: { min: 10, max: 20 } }),
				icon: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				iconName: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				workspaceId: faker.number.float({ fractionDigits: 2 }),
				users: Array.from(
					{ length: faker.number.int({ min: 1, max: 10 }) },
					(_, i) => i + 1,
				).map(() => ({
					id: faker.number.float({ fractionDigits: 2 }),
					upn: faker.string.alpha({ length: { min: 10, max: 20 } }),
					info: faker.helpers.arrayElement([
						{
							...{
								upn: faker.string.alpha({ length: { min: 10, max: 20 } }),
								displayName: faker.helpers.arrayElement([
									faker.string.alpha({ length: { min: 10, max: 20 } }),
									undefined,
								]),
								name: faker.helpers.arrayElement([
									faker.string.alpha({ length: { min: 10, max: 20 } }),
									undefined,
								]),
								isBI: faker.helpers.arrayElement([
									faker.datatype.boolean(),
									undefined,
								]),
							},
						},
						null,
					]),
				})),
			},
			status: {
				id: faker.number.float({ fractionDigits: 2 }),
				name: faker.string.alpha({ length: { min: 10, max: 20 } }),
				color: faker.string.alpha({ length: { min: 10, max: 20 } }),
				type: faker.helpers.arrayElement(Object.values(WorkspaceStatusType)),
				workspaceId: faker.number.float({ fractionDigits: 2 }),
			},
			description: faker.string.alpha({ length: { min: 10, max: 20 } }),
			archivedAt: faker.helpers.arrayElement([
				new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
				null,
			]),
			editable: faker.datatype.boolean(),
		})),
	})),
	...overrideResponse,
})

export const getUpdateSourceResponseMock = (
	overrideResponse: Partial<Extract<SourceDto, object>> = {},
): SourceDto => ({
	createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
	createdBy: faker.number.float({ fractionDigits: 2 }),
	updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
	updatedBy: faker.number.float({ fractionDigits: 2 }),
	deletedAt: faker.helpers.arrayElement([
		new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		null,
	]),
	deletedBy: faker.helpers.arrayElement([
		faker.number.float({ fractionDigits: 2 }),
		null,
	]),
	id: faker.number.float({ fractionDigits: 2 }),
	name: faker.string.alpha({ length: { min: 10, max: 20 } }),
	date: faker.helpers.arrayElement([
		new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		null,
	]),
	workspaceId: faker.number.float({ fractionDigits: 2 }),
	attachmentKey: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		null,
	]),
	attachmentName: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		null,
	]),
	draft: faker.datatype.boolean(),
	extractionStatus: faker.helpers.arrayElement([
		faker.helpers.arrayElement(Object.values(ExtractionStatus)),
		null,
	]),
	tags: Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		createdBy: faker.number.float({ fractionDigits: 2 }),
		updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		updatedBy: faker.number.float({ fractionDigits: 2 }),
		id: faker.number.float({ fractionDigits: 2 }),
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		workspaceId: faker.number.float({ fractionDigits: 2 }),
	})),
	...overrideResponse,
})

export const getDeleteSourceResponseMock = (
	overrideResponse: Partial<Extract<SourceDto, object>> = {},
): SourceDto => ({
	createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
	createdBy: faker.number.float({ fractionDigits: 2 }),
	updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
	updatedBy: faker.number.float({ fractionDigits: 2 }),
	deletedAt: faker.helpers.arrayElement([
		new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		null,
	]),
	deletedBy: faker.helpers.arrayElement([
		faker.number.float({ fractionDigits: 2 }),
		null,
	]),
	id: faker.number.float({ fractionDigits: 2 }),
	name: faker.string.alpha({ length: { min: 10, max: 20 } }),
	date: faker.helpers.arrayElement([
		new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		null,
	]),
	workspaceId: faker.number.float({ fractionDigits: 2 }),
	attachmentKey: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		null,
	]),
	attachmentName: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		null,
	]),
	draft: faker.datatype.boolean(),
	extractionStatus: faker.helpers.arrayElement([
		faker.helpers.arrayElement(Object.values(ExtractionStatus)),
		null,
	]),
	tags: Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		createdBy: faker.number.float({ fractionDigits: 2 }),
		updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		updatedBy: faker.number.float({ fractionDigits: 2 }),
		id: faker.number.float({ fractionDigits: 2 }),
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		workspaceId: faker.number.float({ fractionDigits: 2 }),
	})),
	...overrideResponse,
})

export const getExtractSourceResponseMock = (
	overrideResponse: Partial<Extract<SourceDto, object>> = {},
): SourceDto => ({
	createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
	createdBy: faker.number.float({ fractionDigits: 2 }),
	updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
	updatedBy: faker.number.float({ fractionDigits: 2 }),
	deletedAt: faker.helpers.arrayElement([
		new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		null,
	]),
	deletedBy: faker.helpers.arrayElement([
		faker.number.float({ fractionDigits: 2 }),
		null,
	]),
	id: faker.number.float({ fractionDigits: 2 }),
	name: faker.string.alpha({ length: { min: 10, max: 20 } }),
	date: faker.helpers.arrayElement([
		new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		null,
	]),
	workspaceId: faker.number.float({ fractionDigits: 2 }),
	attachmentKey: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		null,
	]),
	attachmentName: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		null,
	]),
	draft: faker.datatype.boolean(),
	extractionStatus: faker.helpers.arrayElement([
		faker.helpers.arrayElement(Object.values(ExtractionStatus)),
		null,
	]),
	tags: Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		createdBy: faker.number.float({ fractionDigits: 2 }),
		updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		updatedBy: faker.number.float({ fractionDigits: 2 }),
		id: faker.number.float({ fractionDigits: 2 }),
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		workspaceId: faker.number.float({ fractionDigits: 2 }),
	})),
	...overrideResponse,
})

export const getAiExtractionCallbackResponseMock = (
	overrideResponse: Partial<Extract<SourceWithTasksDto, object>> = {},
): SourceWithTasksDto => ({
	createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
	createdBy: faker.number.float({ fractionDigits: 2 }),
	updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
	updatedBy: faker.number.float({ fractionDigits: 2 }),
	deletedAt: faker.helpers.arrayElement([
		new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		null,
	]),
	deletedBy: faker.helpers.arrayElement([
		faker.number.float({ fractionDigits: 2 }),
		null,
	]),
	id: faker.number.float({ fractionDigits: 2 }),
	name: faker.string.alpha({ length: { min: 10, max: 20 } }),
	date: faker.helpers.arrayElement([
		new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		null,
	]),
	workspaceId: faker.number.float({ fractionDigits: 2 }),
	attachmentKey: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		null,
	]),
	attachmentName: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		null,
	]),
	draft: faker.datatype.boolean(),
	extractionStatus: faker.helpers.arrayElement([
		faker.helpers.arrayElement(Object.values(ExtractionStatus)),
		null,
	]),
	tags: Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		createdBy: faker.number.float({ fractionDigits: 2 }),
		updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		updatedBy: faker.number.float({ fractionDigits: 2 }),
		id: faker.number.float({ fractionDigits: 2 }),
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		workspaceId: faker.number.float({ fractionDigits: 2 }),
	})),
	tasks: Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		createdBy: faker.number.float({ fractionDigits: 2 }),
		updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		updatedBy: faker.number.float({ fractionDigits: 2 }),
		deletedAt: faker.helpers.arrayElement([
			new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			null,
		]),
		deletedBy: faker.helpers.arrayElement([
			faker.number.float({ fractionDigits: 2 }),
			null,
		]),
		id: faker.number.float({ fractionDigits: 2 }),
		title: faker.string.alpha({ length: { min: 10, max: 20 } }),
		description: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		flagged: faker.datatype.boolean(),
		deadlineType: faker.helpers.arrayElement(Object.values(DeadlineType)),
		creationType: faker.helpers.arrayElement(Object.values(TaskCreationType)),
		dueDate: faker.helpers.arrayElement([
			new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			null,
		]),
		notes: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		workspaceId: faker.number.float({ fractionDigits: 2 }),
		source: faker.helpers.arrayElement([
			{
				...{
					createdAt: new Date(
						faker.date.past().toISOString().slice(0, 19) + "Z",
					),
					createdBy: faker.number.float({ fractionDigits: 2 }),
					updatedAt: new Date(
						faker.date.past().toISOString().slice(0, 19) + "Z",
					),
					updatedBy: faker.number.float({ fractionDigits: 2 }),
					deletedAt: faker.helpers.arrayElement([
						new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
						null,
					]),
					deletedBy: faker.helpers.arrayElement([
						faker.number.float({ fractionDigits: 2 }),
						null,
					]),
					id: faker.number.float({ fractionDigits: 2 }),
					name: faker.string.alpha({ length: { min: 10, max: 20 } }),
					date: faker.helpers.arrayElement([
						new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
						null,
					]),
					workspaceId: faker.number.float({ fractionDigits: 2 }),
					attachmentKey: faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					attachmentName: faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					draft: faker.datatype.boolean(),
					extractionStatus: faker.helpers.arrayElement([
						faker.helpers.arrayElement(Object.values(ExtractionStatus)),
						null,
					]),
					tags: Array.from(
						{ length: faker.number.int({ min: 1, max: 10 }) },
						(_, i) => i + 1,
					).map(() => ({
						createdAt: new Date(
							faker.date.past().toISOString().slice(0, 19) + "Z",
						),
						createdBy: faker.number.float({ fractionDigits: 2 }),
						updatedAt: new Date(
							faker.date.past().toISOString().slice(0, 19) + "Z",
						),
						updatedBy: faker.number.float({ fractionDigits: 2 }),
						id: faker.number.float({ fractionDigits: 2 }),
						name: faker.string.alpha({ length: { min: 10, max: 20 } }),
						workspaceId: faker.number.float({ fractionDigits: 2 }),
					})),
				},
			},
			null,
		]),
		tags: Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			createdBy: faker.number.float({ fractionDigits: 2 }),
			updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			updatedBy: faker.number.float({ fractionDigits: 2 }),
			id: faker.number.float({ fractionDigits: 2 }),
			name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			workspaceId: faker.number.float({ fractionDigits: 2 }),
		})),
		lastMessage: {
			createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			createdBy: faker.number.float({ fractionDigits: 2 }),
			updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			updatedBy: faker.number.float({ fractionDigits: 2 }),
			deletedAt: faker.helpers.arrayElement([
				new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
				null,
			]),
			deletedBy: faker.helpers.arrayElement([
				faker.number.float({ fractionDigits: 2 }),
				null,
			]),
			id: faker.number.float({ fractionDigits: 2 }),
			content: faker.string.alpha({ length: { min: 10, max: 20 } }),
			user: {
				id: faker.number.float({ fractionDigits: 2 }),
				upn: faker.string.alpha({ length: { min: 10, max: 20 } }),
				info: faker.helpers.arrayElement([
					{
						...{
							upn: faker.string.alpha({ length: { min: 10, max: 20 } }),
							displayName: faker.helpers.arrayElement([
								faker.string.alpha({ length: { min: 10, max: 20 } }),
								undefined,
							]),
							name: faker.helpers.arrayElement([
								faker.string.alpha({ length: { min: 10, max: 20 } }),
								undefined,
							]),
							isBI: faker.helpers.arrayElement([
								faker.datatype.boolean(),
								undefined,
							]),
						},
					},
					null,
				]),
			},
			taskId: faker.number.float({ fractionDigits: 2 }),
		},
		messageCount: faker.number.float({ fractionDigits: 2 }),
		assigneeStatuses: Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			assignee: {
				createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
				createdBy: faker.number.float({ fractionDigits: 2 }),
				updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
				updatedBy: faker.number.float({ fractionDigits: 2 }),
				deletedAt: faker.helpers.arrayElement([
					new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
					null,
				]),
				deletedBy: faker.helpers.arrayElement([
					faker.number.float({ fractionDigits: 2 }),
					null,
				]),
				id: faker.number.float({ fractionDigits: 2 }),
				name: faker.string.alpha({ length: { min: 10, max: 20 } }),
				color: faker.string.alpha({ length: { min: 10, max: 20 } }),
				icon: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				iconName: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				workspaceId: faker.number.float({ fractionDigits: 2 }),
				users: Array.from(
					{ length: faker.number.int({ min: 1, max: 10 }) },
					(_, i) => i + 1,
				).map(() => ({
					id: faker.number.float({ fractionDigits: 2 }),
					upn: faker.string.alpha({ length: { min: 10, max: 20 } }),
					info: faker.helpers.arrayElement([
						{
							...{
								upn: faker.string.alpha({ length: { min: 10, max: 20 } }),
								displayName: faker.helpers.arrayElement([
									faker.string.alpha({ length: { min: 10, max: 20 } }),
									undefined,
								]),
								name: faker.helpers.arrayElement([
									faker.string.alpha({ length: { min: 10, max: 20 } }),
									undefined,
								]),
								isBI: faker.helpers.arrayElement([
									faker.datatype.boolean(),
									undefined,
								]),
							},
						},
						null,
					]),
				})),
			},
			status: {
				id: faker.number.float({ fractionDigits: 2 }),
				name: faker.string.alpha({ length: { min: 10, max: 20 } }),
				color: faker.string.alpha({ length: { min: 10, max: 20 } }),
				type: faker.helpers.arrayElement(Object.values(WorkspaceStatusType)),
				workspaceId: faker.number.float({ fractionDigits: 2 }),
			},
			description: faker.string.alpha({ length: { min: 10, max: 20 } }),
			archivedAt: faker.helpers.arrayElement([
				new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
				null,
			]),
			editable: faker.datatype.boolean(),
		})),
	})),
	...overrideResponse,
})

export const getCreateSourceMockHandler = (
	overrideResponse?:
		| SourceDto
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<SourceDto> | SourceDto),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/source",
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getCreateSourceResponseMock(),
				{ status: 201 },
			)
		},
		options,
	)
}

export const getListSourcesMockHandler = (
	overrideResponse?:
		| SourceDto[]
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<SourceDto[]> | SourceDto[]),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/source",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getListSourcesResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getGetSourceMockHandler = (
	overrideResponse?:
		| SourceWithTasksDto
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<SourceWithTasksDto> | SourceWithTasksDto),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/source/:id",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getGetSourceResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getUpdateSourceMockHandler = (
	overrideResponse?:
		| SourceDto
		| ((
				info: Parameters<Parameters<typeof http.patch>[1]>[0],
		  ) => Promise<SourceDto> | SourceDto),
	options?: RequestHandlerOptions,
) => {
	return http.patch(
		"*/source/:id",
		async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getUpdateSourceResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getDeleteSourceMockHandler = (
	overrideResponse?:
		| SourceDto
		| ((
				info: Parameters<Parameters<typeof http.delete>[1]>[0],
		  ) => Promise<SourceDto> | SourceDto),
	options?: RequestHandlerOptions,
) => {
	return http.delete(
		"*/source/:id",
		async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getDeleteSourceResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getExtractSourceMockHandler = (
	overrideResponse?:
		| SourceDto
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<SourceDto> | SourceDto),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/source/:id/extract",
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getExtractSourceResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getAiExtractionCallbackMockHandler = (
	overrideResponse?:
		| SourceWithTasksDto
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<SourceWithTasksDto> | SourceWithTasksDto),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/source/:id/ai-result",
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getAiExtractionCallbackResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}
export const getSourceMock = () => [
	getCreateSourceMockHandler(),
	getListSourcesMockHandler(),
	getGetSourceMockHandler(),
	getUpdateSourceMockHandler(),
	getDeleteSourceMockHandler(),
	getExtractSourceMockHandler(),
	getAiExtractionCallbackMockHandler(),
]
