/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query"
import { useMutation, useQuery } from "@tanstack/react-query"
import type { ErrorType } from "../../axios.ts"

import { sendRequest } from "../../axios.ts"
import { serializeFormData } from "../../form-data.ts"
import type {
	AiExtractionCallbackPathParameters,
	CreateSourceDto,
	DeleteSourcePathParameters,
	ExtractSourcePathParameters,
	GetAIExtractionCallbackDto,
	GetSourcePathParameters,
	ListSourcesParams,
	SourceDto,
	SourceWithTasksDto,
	UpdateSourceDto,
	UpdateSourcePathParameters,
} from "../model"

const withQueryKey = <T extends object, K>(
	query: T,
	queryKey: K,
): T & { queryKey: K } => {
	const result = { queryKey } as T & { queryKey: K }
	for (const key of Object.keys(query)) {
		// The explicit queryKey always wins, matching the previous
		// `{ ...query, queryKey }` spread where it was set last.
		if (key === "queryKey") continue
		Object.defineProperty(result, key, {
			enumerable: true,
			configurable: true,
			get: () => (query as Record<string, unknown>)[key],
		})
	}
	return result
}

export const createSource = (
	createSourceDto: CreateSourceDto,
	signal?: AbortSignal,
) => {
	const formData = serializeFormData(createSourceDto)
	return sendRequest<SourceDto>({
		url: `/source`,
		method: "POST",
		headers: { "Content-Type": "multipart/form-data" },
		data: formData,
		signal,
	})
}

export const getCreateSourceMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof createSource>>,
		TError,
		{ data: CreateSourceDto },
		TContext
	>
}): UseMutationOptions<
	Awaited<ReturnType<typeof createSource>>,
	TError,
	{ data: CreateSourceDto },
	TContext
> => {
	const mutationKey = ["createSource"]
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } }

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof createSource>>,
		{ data: CreateSourceDto }
	> = (props) => {
		const { data } = props ?? {}

		return createSource(data)
	}

	return { mutationFn, ...mutationOptions }
}

export type CreateSourceMutationResult = NonNullable<
	Awaited<ReturnType<typeof createSource>>
>
export type CreateSourceMutationBody = CreateSourceDto
export type CreateSourceMutationError = ErrorType<unknown>

export const useCreateSource = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof createSource>>,
			TError,
			{ data: CreateSourceDto },
			TContext
		>
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof createSource>>,
	TError,
	{ data: CreateSourceDto },
	TContext
> => {
	return useMutation(getCreateSourceMutationOptions(options), queryClient)
}
export const listSources = (
	params: ListSourcesParams,
	signal?: AbortSignal,
) => {
	return sendRequest<SourceDto[]>({
		url: `/source`,
		method: "GET",
		params,
		signal,
	})
}

export const getListSourcesQueryKey = (params?: ListSourcesParams) => {
	return [`/source`, ...(params ? [params] : [])] as const
}

export const getListSourcesQueryOptions = <
	TData = Awaited<ReturnType<typeof listSources>>,
	TError = ErrorType<unknown>,
>(
	params: ListSourcesParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listSources>>, TError, TData>
		>
	},
) => {
	const { query: queryOptions } = options ?? {}

	const queryKey = queryOptions?.queryKey ?? getListSourcesQueryKey(params)

	const queryFn: QueryFunction<Awaited<ReturnType<typeof listSources>>> = ({
		signal,
	}) => listSources(params, signal)

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof listSources>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListSourcesQueryResult = NonNullable<
	Awaited<ReturnType<typeof listSources>>
>
export type ListSourcesQueryError = ErrorType<unknown>

export function useListSources<
	TData = Awaited<ReturnType<typeof listSources>>,
	TError = ErrorType<unknown>,
>(
	params: ListSourcesParams,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listSources>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof listSources>>,
					TError,
					Awaited<ReturnType<typeof listSources>>
				>,
				"initialData"
			>
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}
export function useListSources<
	TData = Awaited<ReturnType<typeof listSources>>,
	TError = ErrorType<unknown>,
>(
	params: ListSourcesParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listSources>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof listSources>>,
					TError,
					Awaited<ReturnType<typeof listSources>>
				>,
				"initialData"
			>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}
export function useListSources<
	TData = Awaited<ReturnType<typeof listSources>>,
	TError = ErrorType<unknown>,
>(
	params: ListSourcesParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listSources>>, TError, TData>
		>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}

export function useListSources<
	TData = Awaited<ReturnType<typeof listSources>>,
	TError = ErrorType<unknown>,
>(
	params: ListSourcesParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listSources>>, TError, TData>
		>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
} {
	const queryOptions = getListSourcesQueryOptions(params, options)

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> }

	return withQueryKey(query, queryOptions.queryKey)
}

export const getSource = (
	{ id }: GetSourcePathParameters,
	signal?: AbortSignal,
) => {
	return sendRequest<SourceWithTasksDto>({
		url: `/source/${id}`,
		method: "GET",
		signal,
	})
}

export const getGetSourceQueryKey = ({ id }: GetSourcePathParameters) => {
	return [`/source/${id}`] as const
}

export const getGetSourceQueryOptions = <
	TData = Awaited<ReturnType<typeof getSource>>,
	TError = ErrorType<unknown>,
>(
	{ id }: GetSourcePathParameters,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getSource>>, TError, TData>
		>
	},
) => {
	const { query: queryOptions } = options ?? {}

	const queryKey = queryOptions?.queryKey ?? getGetSourceQueryKey({ id })

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getSource>>> = ({
		signal,
	}) => getSource({ id }, signal)

	return {
		queryKey,
		queryFn,
		enabled: id !== null && id !== undefined,
		...queryOptions,
	} as UseQueryOptions<Awaited<ReturnType<typeof getSource>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>
	}
}

export type GetSourceQueryResult = NonNullable<
	Awaited<ReturnType<typeof getSource>>
>
export type GetSourceQueryError = ErrorType<unknown>

export function useGetSource<
	TData = Awaited<ReturnType<typeof getSource>>,
	TError = ErrorType<unknown>,
>(
	pathParams: GetSourcePathParameters,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getSource>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getSource>>,
					TError,
					Awaited<ReturnType<typeof getSource>>
				>,
				"initialData"
			>
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetSource<
	TData = Awaited<ReturnType<typeof getSource>>,
	TError = ErrorType<unknown>,
>(
	pathParams: GetSourcePathParameters,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getSource>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getSource>>,
					TError,
					Awaited<ReturnType<typeof getSource>>
				>,
				"initialData"
			>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetSource<
	TData = Awaited<ReturnType<typeof getSource>>,
	TError = ErrorType<unknown>,
>(
	pathParams: GetSourcePathParameters,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getSource>>, TError, TData>
		>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}

export function useGetSource<
	TData = Awaited<ReturnType<typeof getSource>>,
	TError = ErrorType<unknown>,
>(
	{ id }: GetSourcePathParameters,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getSource>>, TError, TData>
		>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
} {
	const queryOptions = getGetSourceQueryOptions({ id }, options)

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> }

	return withQueryKey(query, queryOptions.queryKey)
}

export const updateSource = (
	{ id }: UpdateSourcePathParameters,
	updateSourceDto: UpdateSourceDto,
	signal?: AbortSignal,
) => {
	const formData = serializeFormData(updateSourceDto)
	return sendRequest<SourceDto>({
		url: `/source/${id}`,
		method: "PATCH",
		headers: { "Content-Type": "multipart/form-data" },
		data: formData,
		signal,
	})
}

export const getUpdateSourceMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof updateSource>>,
		TError,
		{ pathParams: UpdateSourcePathParameters; data: UpdateSourceDto },
		TContext
	>
}): UseMutationOptions<
	Awaited<ReturnType<typeof updateSource>>,
	TError,
	{ pathParams: UpdateSourcePathParameters; data: UpdateSourceDto },
	TContext
> => {
	const mutationKey = ["updateSource"]
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } }

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof updateSource>>,
		{ pathParams: UpdateSourcePathParameters; data: UpdateSourceDto }
	> = (props) => {
		const { pathParams, data } = props ?? {}

		return updateSource(pathParams, data)
	}

	return { mutationFn, ...mutationOptions }
}

export type UpdateSourceMutationResult = NonNullable<
	Awaited<ReturnType<typeof updateSource>>
>
export type UpdateSourceMutationBody = UpdateSourceDto
export type UpdateSourceMutationError = ErrorType<unknown>

export const useUpdateSource = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof updateSource>>,
			TError,
			{ pathParams: UpdateSourcePathParameters; data: UpdateSourceDto },
			TContext
		>
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof updateSource>>,
	TError,
	{ pathParams: UpdateSourcePathParameters; data: UpdateSourceDto },
	TContext
> => {
	return useMutation(getUpdateSourceMutationOptions(options), queryClient)
}
export const deleteSource = (
	{ id }: DeleteSourcePathParameters,
	signal?: AbortSignal,
) => {
	return sendRequest<SourceDto>({
		url: `/source/${id}`,
		method: "DELETE",
		signal,
	})
}

export const getDeleteSourceMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteSource>>,
		TError,
		{ pathParams: DeleteSourcePathParameters },
		TContext
	>
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteSource>>,
	TError,
	{ pathParams: DeleteSourcePathParameters },
	TContext
> => {
	const mutationKey = ["deleteSource"]
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } }

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteSource>>,
		{ pathParams: DeleteSourcePathParameters }
	> = (props) => {
		const { pathParams } = props ?? {}

		return deleteSource(pathParams)
	}

	return { mutationFn, ...mutationOptions }
}

export type DeleteSourceMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteSource>>
>

export type DeleteSourceMutationError = ErrorType<unknown>

export const useDeleteSource = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteSource>>,
			TError,
			{ pathParams: DeleteSourcePathParameters },
			TContext
		>
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof deleteSource>>,
	TError,
	{ pathParams: DeleteSourcePathParameters },
	TContext
> => {
	return useMutation(getDeleteSourceMutationOptions(options), queryClient)
}
export const extractSource = (
	{ id }: ExtractSourcePathParameters,
	signal?: AbortSignal,
) => {
	return sendRequest<SourceDto>({
		url: `/source/${id}/extract`,
		method: "POST",
		signal,
	})
}

export const getExtractSourceMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof extractSource>>,
		TError,
		{ pathParams: ExtractSourcePathParameters },
		TContext
	>
}): UseMutationOptions<
	Awaited<ReturnType<typeof extractSource>>,
	TError,
	{ pathParams: ExtractSourcePathParameters },
	TContext
> => {
	const mutationKey = ["extractSource"]
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } }

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof extractSource>>,
		{ pathParams: ExtractSourcePathParameters }
	> = (props) => {
		const { pathParams } = props ?? {}

		return extractSource(pathParams)
	}

	return { mutationFn, ...mutationOptions }
}

export type ExtractSourceMutationResult = NonNullable<
	Awaited<ReturnType<typeof extractSource>>
>

export type ExtractSourceMutationError = ErrorType<unknown>

export const useExtractSource = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof extractSource>>,
			TError,
			{ pathParams: ExtractSourcePathParameters },
			TContext
		>
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof extractSource>>,
	TError,
	{ pathParams: ExtractSourcePathParameters },
	TContext
> => {
	return useMutation(getExtractSourceMutationOptions(options), queryClient)
}
export const aiExtractionCallback = (
	{ id }: AiExtractionCallbackPathParameters,
	getAIExtractionCallbackDto: GetAIExtractionCallbackDto,
	signal?: AbortSignal,
) => {
	return sendRequest<SourceWithTasksDto>({
		url: `/source/${id}/ai-result`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: getAIExtractionCallbackDto,
		signal,
	})
}

export const getAiExtractionCallbackMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof aiExtractionCallback>>,
		TError,
		{
			pathParams: AiExtractionCallbackPathParameters
			data: GetAIExtractionCallbackDto
		},
		TContext
	>
}): UseMutationOptions<
	Awaited<ReturnType<typeof aiExtractionCallback>>,
	TError,
	{
		pathParams: AiExtractionCallbackPathParameters
		data: GetAIExtractionCallbackDto
	},
	TContext
> => {
	const mutationKey = ["aiExtractionCallback"]
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } }

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof aiExtractionCallback>>,
		{
			pathParams: AiExtractionCallbackPathParameters
			data: GetAIExtractionCallbackDto
		}
	> = (props) => {
		const { pathParams, data } = props ?? {}

		return aiExtractionCallback(pathParams, data)
	}

	return { mutationFn, ...mutationOptions }
}

export type AiExtractionCallbackMutationResult = NonNullable<
	Awaited<ReturnType<typeof aiExtractionCallback>>
>
export type AiExtractionCallbackMutationBody = GetAIExtractionCallbackDto
export type AiExtractionCallbackMutationError = ErrorType<unknown>

export const useAiExtractionCallback = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof aiExtractionCallback>>,
			TError,
			{
				pathParams: AiExtractionCallbackPathParameters
				data: GetAIExtractionCallbackDto
			},
			TContext
		>
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof aiExtractionCallback>>,
	TError,
	{
		pathParams: AiExtractionCallbackPathParameters
		data: GetAIExtractionCallbackDto
	},
	TContext
> => {
	return useMutation(
		getAiExtractionCallbackMutationOptions(options),
		queryClient,
	)
}
