/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query"
import { useMutation, useQuery } from "@tanstack/react-query"
import { sendRequest } from "../../axios"
import type {
	CreateSourceDto,
	DeleteSourcePathParameters,
	GetSourcePathParameters,
	ListSourcesParams,
	SourceDto,
	UpdateSourceDto,
	UpdateSourcePathParameters,
} from "../model"

export const createSource = (
	createSourceDto: CreateSourceDto,
	signal?: AbortSignal,
) => {
	return sendRequest<SourceDto>({
		url: `/source`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: createSourceDto,
		signal,
	})
}

export const getCreateSourceMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof createSource>>,
		TError,
		{ data: CreateSourceDto },
		TContext
	>
}): UseMutationOptions<
	Awaited<ReturnType<typeof createSource>>,
	TError,
	{ data: CreateSourceDto },
	TContext
> => {
	const mutationKey = ["createSource"]
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } }

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof createSource>>,
		{ data: CreateSourceDto }
	> = (props) => {
		const { data } = props ?? {}

		return createSource(data)
	}

	return { mutationFn, ...mutationOptions }
}

export type CreateSourceMutationResult = NonNullable<
	Awaited<ReturnType<typeof createSource>>
>
export type CreateSourceMutationBody = CreateSourceDto
export type CreateSourceMutationError = unknown

export const useCreateSource = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof createSource>>,
			TError,
			{ data: CreateSourceDto },
			TContext
		>
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof createSource>>,
	TError,
	{ data: CreateSourceDto },
	TContext
> => {
	return useMutation(getCreateSourceMutationOptions(options), queryClient)
}
export const listSources = (
	params: ListSourcesParams,
	signal?: AbortSignal,
) => {
	return sendRequest<SourceDto[]>({
		url: `/source`,
		method: "GET",
		params,
		signal,
	})
}

export const getListSourcesQueryKey = (params?: ListSourcesParams) => {
	return [`/source`, ...(params ? [params] : [])] as const
}

export const getListSourcesQueryOptions = <
	TData = Awaited<ReturnType<typeof listSources>>,
	TError = unknown,
>(
	params: ListSourcesParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listSources>>, TError, TData>
		>
	},
) => {
	const { query: queryOptions } = options ?? {}

	const queryKey = queryOptions?.queryKey ?? getListSourcesQueryKey(params)

	const queryFn: QueryFunction<Awaited<ReturnType<typeof listSources>>> = ({
		signal,
	}) => listSources(params, signal)

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof listSources>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListSourcesQueryResult = NonNullable<
	Awaited<ReturnType<typeof listSources>>
>
export type ListSourcesQueryError = unknown

export function useListSources<
	TData = Awaited<ReturnType<typeof listSources>>,
	TError = unknown,
>(
	params: ListSourcesParams,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listSources>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof listSources>>,
					TError,
					Awaited<ReturnType<typeof listSources>>
				>,
				"initialData"
			>
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}
export function useListSources<
	TData = Awaited<ReturnType<typeof listSources>>,
	TError = unknown,
>(
	params: ListSourcesParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listSources>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof listSources>>,
					TError,
					Awaited<ReturnType<typeof listSources>>
				>,
				"initialData"
			>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}
export function useListSources<
	TData = Awaited<ReturnType<typeof listSources>>,
	TError = unknown,
>(
	params: ListSourcesParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listSources>>, TError, TData>
		>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}

export function useListSources<
	TData = Awaited<ReturnType<typeof listSources>>,
	TError = unknown,
>(
	params: ListSourcesParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listSources>>, TError, TData>
		>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
} {
	const queryOptions = getListSourcesQueryOptions(params, options)

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> }

	return { ...query, queryKey: queryOptions.queryKey }
}

export const getSource = (
	{ id }: GetSourcePathParameters,
	signal?: AbortSignal,
) => {
	return sendRequest<SourceDto>({ url: `/source/${id}`, method: "GET", signal })
}

export const getGetSourceQueryKey = ({ id }: GetSourcePathParameters) => {
	return [`/source/${id}`] as const
}

export const getGetSourceQueryOptions = <
	TData = Awaited<ReturnType<typeof getSource>>,
	TError = unknown,
>(
	{ id }: GetSourcePathParameters,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getSource>>, TError, TData>
		>
	},
) => {
	const { query: queryOptions } = options ?? {}

	const queryKey = queryOptions?.queryKey ?? getGetSourceQueryKey({ id })

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getSource>>> = ({
		signal,
	}) => getSource({ id }, signal)

	return {
		queryKey,
		queryFn,
		enabled: !!id,
		...queryOptions,
	} as UseQueryOptions<Awaited<ReturnType<typeof getSource>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>
	}
}

export type GetSourceQueryResult = NonNullable<
	Awaited<ReturnType<typeof getSource>>
>
export type GetSourceQueryError = unknown

export function useGetSource<
	TData = Awaited<ReturnType<typeof getSource>>,
	TError = unknown,
>(
	pathParams: GetSourcePathParameters,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getSource>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getSource>>,
					TError,
					Awaited<ReturnType<typeof getSource>>
				>,
				"initialData"
			>
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetSource<
	TData = Awaited<ReturnType<typeof getSource>>,
	TError = unknown,
>(
	pathParams: GetSourcePathParameters,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getSource>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getSource>>,
					TError,
					Awaited<ReturnType<typeof getSource>>
				>,
				"initialData"
			>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetSource<
	TData = Awaited<ReturnType<typeof getSource>>,
	TError = unknown,
>(
	pathParams: GetSourcePathParameters,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getSource>>, TError, TData>
		>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}

export function useGetSource<
	TData = Awaited<ReturnType<typeof getSource>>,
	TError = unknown,
>(
	{ id }: GetSourcePathParameters,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getSource>>, TError, TData>
		>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
} {
	const queryOptions = getGetSourceQueryOptions({ id }, options)

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> }

	return { ...query, queryKey: queryOptions.queryKey }
}

export const updateSource = (
	{ id }: UpdateSourcePathParameters,
	updateSourceDto: UpdateSourceDto,
	signal?: AbortSignal,
) => {
	return sendRequest<SourceDto>({
		url: `/source/${id}`,
		method: "PATCH",
		headers: { "Content-Type": "application/json" },
		data: updateSourceDto,
		signal,
	})
}

export const getUpdateSourceMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof updateSource>>,
		TError,
		{ pathParams: UpdateSourcePathParameters; data: UpdateSourceDto },
		TContext
	>
}): UseMutationOptions<
	Awaited<ReturnType<typeof updateSource>>,
	TError,
	{ pathParams: UpdateSourcePathParameters; data: UpdateSourceDto },
	TContext
> => {
	const mutationKey = ["updateSource"]
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } }

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof updateSource>>,
		{ pathParams: UpdateSourcePathParameters; data: UpdateSourceDto }
	> = (props) => {
		const { pathParams, data } = props ?? {}

		return updateSource(pathParams, data)
	}

	return { mutationFn, ...mutationOptions }
}

export type UpdateSourceMutationResult = NonNullable<
	Awaited<ReturnType<typeof updateSource>>
>
export type UpdateSourceMutationBody = UpdateSourceDto
export type UpdateSourceMutationError = unknown

export const useUpdateSource = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof updateSource>>,
			TError,
			{ pathParams: UpdateSourcePathParameters; data: UpdateSourceDto },
			TContext
		>
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof updateSource>>,
	TError,
	{ pathParams: UpdateSourcePathParameters; data: UpdateSourceDto },
	TContext
> => {
	return useMutation(getUpdateSourceMutationOptions(options), queryClient)
}
export const deleteSource = (
	{ id }: DeleteSourcePathParameters,
	signal?: AbortSignal,
) => {
	return sendRequest<SourceDto>({
		url: `/source/${id}`,
		method: "DELETE",
		signal,
	})
}

export const getDeleteSourceMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteSource>>,
		TError,
		{ pathParams: DeleteSourcePathParameters },
		TContext
	>
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteSource>>,
	TError,
	{ pathParams: DeleteSourcePathParameters },
	TContext
> => {
	const mutationKey = ["deleteSource"]
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } }

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteSource>>,
		{ pathParams: DeleteSourcePathParameters }
	> = (props) => {
		const { pathParams } = props ?? {}

		return deleteSource(pathParams)
	}

	return { mutationFn, ...mutationOptions }
}

export type DeleteSourceMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteSource>>
>

export type DeleteSourceMutationError = unknown

export const useDeleteSource = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteSource>>,
			TError,
			{ pathParams: DeleteSourcePathParameters },
			TContext
		>
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof deleteSource>>,
	TError,
	{ pathParams: DeleteSourcePathParameters },
	TContext
> => {
	return useMutation(getDeleteSourceMutationOptions(options), queryClient)
}
