/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */
import { faker } from "@faker-js/faker"
import type { RequestHandlerOptions } from "msw"
import { HttpResponse, http } from "msw"

import type { SourceDto } from "../model"

export const getCreateSourceResponseMock = (
	overrideResponse: Partial<Extract<SourceDto, object>> = {},
): SourceDto => ({
	createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
	createdBy: faker.number.float({ fractionDigits: 2 }),
	updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
	updatedBy: faker.number.float({ fractionDigits: 2 }),
	deletedAt: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			null,
		]),
		null,
	]),
	deletedBy: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.number.float({ fractionDigits: 2 }),
			null,
		]),
		null,
	]),
	id: faker.number.float({ fractionDigits: 2 }),
	name: faker.string.alpha({ length: { min: 10, max: 20 } }),
	date: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
	workspaceId: faker.number.float({ fractionDigits: 2 }),
	attachmentKey: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		null,
	]),
	attachmentName: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		null,
	]),
	draft: faker.datatype.boolean(),
	tags: Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		createdBy: faker.number.float({ fractionDigits: 2 }),
		updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		updatedBy: faker.number.float({ fractionDigits: 2 }),
		id: faker.number.float({ fractionDigits: 2 }),
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		workspaceId: faker.number.float({ fractionDigits: 2 }),
	})),
	...overrideResponse,
})

export const getListSourcesResponseMock = (): SourceDto[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		createdBy: faker.number.float({ fractionDigits: 2 }),
		updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		updatedBy: faker.number.float({ fractionDigits: 2 }),
		deletedAt: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
				null,
			]),
			null,
		]),
		deletedBy: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.number.float({ fractionDigits: 2 }),
				null,
			]),
			null,
		]),
		id: faker.number.float({ fractionDigits: 2 }),
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		date: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		workspaceId: faker.number.float({ fractionDigits: 2 }),
		attachmentKey: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			null,
		]),
		attachmentName: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			null,
		]),
		draft: faker.datatype.boolean(),
		tags: Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			createdBy: faker.number.float({ fractionDigits: 2 }),
			updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			updatedBy: faker.number.float({ fractionDigits: 2 }),
			id: faker.number.float({ fractionDigits: 2 }),
			name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			workspaceId: faker.number.float({ fractionDigits: 2 }),
		})),
	}))

export const getGetSourceResponseMock = (
	overrideResponse: Partial<Extract<SourceDto, object>> = {},
): SourceDto => ({
	createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
	createdBy: faker.number.float({ fractionDigits: 2 }),
	updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
	updatedBy: faker.number.float({ fractionDigits: 2 }),
	deletedAt: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			null,
		]),
		null,
	]),
	deletedBy: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.number.float({ fractionDigits: 2 }),
			null,
		]),
		null,
	]),
	id: faker.number.float({ fractionDigits: 2 }),
	name: faker.string.alpha({ length: { min: 10, max: 20 } }),
	date: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
	workspaceId: faker.number.float({ fractionDigits: 2 }),
	attachmentKey: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		null,
	]),
	attachmentName: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		null,
	]),
	draft: faker.datatype.boolean(),
	tags: Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		createdBy: faker.number.float({ fractionDigits: 2 }),
		updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		updatedBy: faker.number.float({ fractionDigits: 2 }),
		id: faker.number.float({ fractionDigits: 2 }),
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		workspaceId: faker.number.float({ fractionDigits: 2 }),
	})),
	...overrideResponse,
})

export const getUpdateSourceResponseMock = (
	overrideResponse: Partial<Extract<SourceDto, object>> = {},
): SourceDto => ({
	createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
	createdBy: faker.number.float({ fractionDigits: 2 }),
	updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
	updatedBy: faker.number.float({ fractionDigits: 2 }),
	deletedAt: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			null,
		]),
		null,
	]),
	deletedBy: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.number.float({ fractionDigits: 2 }),
			null,
		]),
		null,
	]),
	id: faker.number.float({ fractionDigits: 2 }),
	name: faker.string.alpha({ length: { min: 10, max: 20 } }),
	date: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
	workspaceId: faker.number.float({ fractionDigits: 2 }),
	attachmentKey: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		null,
	]),
	attachmentName: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		null,
	]),
	draft: faker.datatype.boolean(),
	tags: Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		createdBy: faker.number.float({ fractionDigits: 2 }),
		updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		updatedBy: faker.number.float({ fractionDigits: 2 }),
		id: faker.number.float({ fractionDigits: 2 }),
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		workspaceId: faker.number.float({ fractionDigits: 2 }),
	})),
	...overrideResponse,
})

export const getDeleteSourceResponseMock = (
	overrideResponse: Partial<Extract<SourceDto, object>> = {},
): SourceDto => ({
	createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
	createdBy: faker.number.float({ fractionDigits: 2 }),
	updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
	updatedBy: faker.number.float({ fractionDigits: 2 }),
	deletedAt: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			null,
		]),
		null,
	]),
	deletedBy: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.number.float({ fractionDigits: 2 }),
			null,
		]),
		null,
	]),
	id: faker.number.float({ fractionDigits: 2 }),
	name: faker.string.alpha({ length: { min: 10, max: 20 } }),
	date: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
	workspaceId: faker.number.float({ fractionDigits: 2 }),
	attachmentKey: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		null,
	]),
	attachmentName: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		null,
	]),
	draft: faker.datatype.boolean(),
	tags: Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		createdBy: faker.number.float({ fractionDigits: 2 }),
		updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		updatedBy: faker.number.float({ fractionDigits: 2 }),
		id: faker.number.float({ fractionDigits: 2 }),
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		workspaceId: faker.number.float({ fractionDigits: 2 }),
	})),
	...overrideResponse,
})

export const getCreateSourceMockHandler = (
	overrideResponse?:
		| SourceDto
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<SourceDto> | SourceDto),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/source",
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getCreateSourceResponseMock(),
				{ status: 201 },
			)
		},
		options,
	)
}

export const getListSourcesMockHandler = (
	overrideResponse?:
		| SourceDto[]
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<SourceDto[]> | SourceDto[]),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/source",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getListSourcesResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getGetSourceMockHandler = (
	overrideResponse?:
		| SourceDto
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<SourceDto> | SourceDto),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/source/:id",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getGetSourceResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getUpdateSourceMockHandler = (
	overrideResponse?:
		| SourceDto
		| ((
				info: Parameters<Parameters<typeof http.patch>[1]>[0],
		  ) => Promise<SourceDto> | SourceDto),
	options?: RequestHandlerOptions,
) => {
	return http.patch(
		"*/source/:id",
		async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getUpdateSourceResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getDeleteSourceMockHandler = (
	overrideResponse?:
		| SourceDto
		| ((
				info: Parameters<Parameters<typeof http.delete>[1]>[0],
		  ) => Promise<SourceDto> | SourceDto),
	options?: RequestHandlerOptions,
) => {
	return http.delete(
		"*/source/:id",
		async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getDeleteSourceResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getAiExtractionCallbackMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/source/:id/ai-result",
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			if (typeof overrideResponse === "function") {
				await overrideResponse(info)
			}

			return new HttpResponse(null, { status: 201 })
		},
		options,
	)
}
export const getSourceMock = () => [
	getCreateSourceMockHandler(),
	getListSourcesMockHandler(),
	getGetSourceMockHandler(),
	getUpdateSourceMockHandler(),
	getDeleteSourceMockHandler(),
	getAiExtractionCallbackMockHandler(),
]
