/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AssigneeTaskStatusDto,
  UpdateAssigneeTaskStatusDto
} from '.././model';





export const listAssigneeTaskStatuses = (
    taskId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AssigneeTaskStatusDto[]>> => {
    
    
    return axios.default.get(
      `/assignee-task-status/${taskId}`,options
    );
  }




export const getListAssigneeTaskStatusesQueryKey = (taskId?: number,) => {
    return [
    `/assignee-task-status/${taskId}`
    ] as const;
    }

    
export const getListAssigneeTaskStatusesQueryOptions = <TData = Awaited<ReturnType<typeof listAssigneeTaskStatuses>>, TError = AxiosError<unknown>>(taskId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listAssigneeTaskStatuses>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAssigneeTaskStatusesQueryKey(taskId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAssigneeTaskStatuses>>> = ({ signal }) => listAssigneeTaskStatuses(taskId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(taskId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAssigneeTaskStatuses>>, TError, TData> & { queryKey: QueryKey }
}

export type ListAssigneeTaskStatusesQueryResult = NonNullable<Awaited<ReturnType<typeof listAssigneeTaskStatuses>>>
export type ListAssigneeTaskStatusesQueryError = AxiosError<unknown>



export function useListAssigneeTaskStatuses<TData = Awaited<ReturnType<typeof listAssigneeTaskStatuses>>, TError = AxiosError<unknown>>(
 taskId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listAssigneeTaskStatuses>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListAssigneeTaskStatusesQueryOptions(taskId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const upsertAssigneeTaskStatus = (
    updateAssigneeTaskStatusDto: UpdateAssigneeTaskStatusDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AssigneeTaskStatusDto>> => {
    
    
    return axios.default.put(
      `/assignee-task-status`,
      updateAssigneeTaskStatusDto,options
    );
  }



export const getUpsertAssigneeTaskStatusMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof upsertAssigneeTaskStatus>>, TError,{data: UpdateAssigneeTaskStatusDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof upsertAssigneeTaskStatus>>, TError,{data: UpdateAssigneeTaskStatusDto}, TContext> => {

const mutationKey = ['upsertAssigneeTaskStatus'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof upsertAssigneeTaskStatus>>, {data: UpdateAssigneeTaskStatusDto}> = (props) => {
          const {data} = props ?? {};

          return  upsertAssigneeTaskStatus(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpsertAssigneeTaskStatusMutationResult = NonNullable<Awaited<ReturnType<typeof upsertAssigneeTaskStatus>>>
    export type UpsertAssigneeTaskStatusMutationBody = UpdateAssigneeTaskStatusDto
    export type UpsertAssigneeTaskStatusMutationError = AxiosError<unknown>

    export const useUpsertAssigneeTaskStatus = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof upsertAssigneeTaskStatus>>, TError,{data: UpdateAssigneeTaskStatusDto}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof upsertAssigneeTaskStatus>>,
        TError,
        {data: UpdateAssigneeTaskStatusDto},
        TContext
      > => {

      const mutationOptions = getUpsertAssigneeTaskStatusMutationOptions(options);

      return useMutation(mutationOptions);
    }
    export const deleteAssigneeTaskStatus = (
    taskId: number,
    assigneeId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AssigneeTaskStatusDto>> => {
    
    
    return axios.default.delete(
      `/assignee-task-status/${taskId}/${assigneeId}`,options
    );
  }



export const getDeleteAssigneeTaskStatusMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAssigneeTaskStatus>>, TError,{taskId: number;assigneeId: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAssigneeTaskStatus>>, TError,{taskId: number;assigneeId: number}, TContext> => {

const mutationKey = ['deleteAssigneeTaskStatus'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAssigneeTaskStatus>>, {taskId: number;assigneeId: number}> = (props) => {
          const {taskId,assigneeId} = props ?? {};

          return  deleteAssigneeTaskStatus(taskId,assigneeId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAssigneeTaskStatusMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAssigneeTaskStatus>>>
    
    export type DeleteAssigneeTaskStatusMutationError = AxiosError<unknown>

    export const useDeleteAssigneeTaskStatus = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAssigneeTaskStatus>>, TError,{taskId: number;assigneeId: number}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteAssigneeTaskStatus>>,
        TError,
        {taskId: number;assigneeId: number},
        TContext
      > => {

      const mutationOptions = getDeleteAssigneeTaskStatusMutationOptions(options);

      return useMutation(mutationOptions);
    }
    