/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AssigneeDto,
  CreateAssigneeDto,
  ListAssigneesParams,
  UpdateAssigneeDto
} from '.././model';





export const createAssignee = (
    createAssigneeDto: CreateAssigneeDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AssigneeDto>> => {
    
    
    return axios.default.post(
      `/assignee`,
      createAssigneeDto,options
    );
  }



export const getCreateAssigneeMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAssignee>>, TError,{data: CreateAssigneeDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createAssignee>>, TError,{data: CreateAssigneeDto}, TContext> => {

const mutationKey = ['createAssignee'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createAssignee>>, {data: CreateAssigneeDto}> = (props) => {
          const {data} = props ?? {};

          return  createAssignee(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateAssigneeMutationResult = NonNullable<Awaited<ReturnType<typeof createAssignee>>>
    export type CreateAssigneeMutationBody = CreateAssigneeDto
    export type CreateAssigneeMutationError = AxiosError<unknown>

    export const useCreateAssignee = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAssignee>>, TError,{data: CreateAssigneeDto}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createAssignee>>,
        TError,
        {data: CreateAssigneeDto},
        TContext
      > => {

      const mutationOptions = getCreateAssigneeMutationOptions(options);

      return useMutation(mutationOptions);
    }
    export const listAssignees = (
    params: ListAssigneesParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AssigneeDto[]>> => {
    
    
    return axios.default.get(
      `/assignee`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getListAssigneesQueryKey = (params?: ListAssigneesParams,) => {
    return [
    `/assignee`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListAssigneesQueryOptions = <TData = Awaited<ReturnType<typeof listAssignees>>, TError = AxiosError<unknown>>(params: ListAssigneesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listAssignees>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAssigneesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAssignees>>> = ({ signal }) => listAssignees(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAssignees>>, TError, TData> & { queryKey: QueryKey }
}

export type ListAssigneesQueryResult = NonNullable<Awaited<ReturnType<typeof listAssignees>>>
export type ListAssigneesQueryError = AxiosError<unknown>



export function useListAssignees<TData = Awaited<ReturnType<typeof listAssignees>>, TError = AxiosError<unknown>>(
 params: ListAssigneesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listAssignees>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListAssigneesQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getAssignee = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AssigneeDto>> => {
    
    
    return axios.default.get(
      `/assignee/${id}`,options
    );
  }




export const getGetAssigneeQueryKey = (id?: number,) => {
    return [
    `/assignee/${id}`
    ] as const;
    }

    
export const getGetAssigneeQueryOptions = <TData = Awaited<ReturnType<typeof getAssignee>>, TError = AxiosError<unknown>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAssignee>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAssigneeQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAssignee>>> = ({ signal }) => getAssignee(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAssignee>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAssigneeQueryResult = NonNullable<Awaited<ReturnType<typeof getAssignee>>>
export type GetAssigneeQueryError = AxiosError<unknown>



export function useGetAssignee<TData = Awaited<ReturnType<typeof getAssignee>>, TError = AxiosError<unknown>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAssignee>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAssigneeQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const updateAssignee = (
    id: number,
    updateAssigneeDto: UpdateAssigneeDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AssigneeDto>> => {
    
    
    return axios.default.patch(
      `/assignee/${id}`,
      updateAssigneeDto,options
    );
  }



export const getUpdateAssigneeMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAssignee>>, TError,{id: number;data: UpdateAssigneeDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateAssignee>>, TError,{id: number;data: UpdateAssigneeDto}, TContext> => {

const mutationKey = ['updateAssignee'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateAssignee>>, {id: number;data: UpdateAssigneeDto}> = (props) => {
          const {id,data} = props ?? {};

          return  updateAssignee(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateAssigneeMutationResult = NonNullable<Awaited<ReturnType<typeof updateAssignee>>>
    export type UpdateAssigneeMutationBody = UpdateAssigneeDto
    export type UpdateAssigneeMutationError = AxiosError<unknown>

    export const useUpdateAssignee = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAssignee>>, TError,{id: number;data: UpdateAssigneeDto}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateAssignee>>,
        TError,
        {id: number;data: UpdateAssigneeDto},
        TContext
      > => {

      const mutationOptions = getUpdateAssigneeMutationOptions(options);

      return useMutation(mutationOptions);
    }
    export const deleteAssignee = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AssigneeDto>> => {
    
    
    return axios.default.delete(
      `/assignee/${id}`,options
    );
  }



export const getDeleteAssigneeMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAssignee>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAssignee>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteAssignee'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAssignee>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteAssignee(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAssigneeMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAssignee>>>
    
    export type DeleteAssigneeMutationError = AxiosError<unknown>

    export const useDeleteAssignee = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAssignee>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteAssignee>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteAssigneeMutationOptions(options);

      return useMutation(mutationOptions);
    }
    