/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";
import { apiRequest } from "../../axios";
import type {
	CreateWorkspaceDto,
	DeleteWorkspacePathParameters,
	GetWorkspacePathParameters,
	ListWorkspacesParams,
	UpdateWorkspaceDto,
	UpdateWorkspacePathParameters,
	WorkspaceDto,
} from "../model";

export const createWorkspace = (
	createWorkspaceDto: CreateWorkspaceDto,
	signal?: AbortSignal,
) => {
	return apiRequest<WorkspaceDto>({
		url: `/workspace`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: createWorkspaceDto,
		signal,
	});
};

export const getCreateWorkspaceMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof createWorkspace>>,
		TError,
		{ data: CreateWorkspaceDto },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof createWorkspace>>,
	TError,
	{ data: CreateWorkspaceDto },
	TContext
> => {
	const mutationKey = ["createWorkspace"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof createWorkspace>>,
		{ data: CreateWorkspaceDto }
	> = (props) => {
		const { data } = props ?? {};

		return createWorkspace(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type CreateWorkspaceMutationResult = NonNullable<
	Awaited<ReturnType<typeof createWorkspace>>
>;
export type CreateWorkspaceMutationBody = CreateWorkspaceDto;
export type CreateWorkspaceMutationError = unknown;

export const useCreateWorkspace = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof createWorkspace>>,
			TError,
			{ data: CreateWorkspaceDto },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof createWorkspace>>,
	TError,
	{ data: CreateWorkspaceDto },
	TContext
> => {
	return useMutation(getCreateWorkspaceMutationOptions(options), queryClient);
};
export const listWorkspaces = (
	params?: ListWorkspacesParams,
	signal?: AbortSignal,
) => {
	return apiRequest<WorkspaceDto[]>({
		url: `/workspace`,
		method: "GET",
		params,
		signal,
	});
};

export const getListWorkspacesQueryKey = (params?: ListWorkspacesParams) => {
	return [`/workspace`, ...(params ? [params] : [])] as const;
};

export const getListWorkspacesQueryOptions = <
	TData = Awaited<ReturnType<typeof listWorkspaces>>,
	TError = unknown,
>(
	params?: ListWorkspacesParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listWorkspaces>>, TError, TData>
		>;
	},
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getListWorkspacesQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof listWorkspaces>>> = ({
		signal,
	}) => listWorkspaces(params, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof listWorkspaces>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListWorkspacesQueryResult = NonNullable<
	Awaited<ReturnType<typeof listWorkspaces>>
>;
export type ListWorkspacesQueryError = unknown;

export function useListWorkspaces<
	TData = Awaited<ReturnType<typeof listWorkspaces>>,
	TError = unknown,
>(
	params: undefined | ListWorkspacesParams,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listWorkspaces>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof listWorkspaces>>,
					TError,
					Awaited<ReturnType<typeof listWorkspaces>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListWorkspaces<
	TData = Awaited<ReturnType<typeof listWorkspaces>>,
	TError = unknown,
>(
	params?: ListWorkspacesParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listWorkspaces>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof listWorkspaces>>,
					TError,
					Awaited<ReturnType<typeof listWorkspaces>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListWorkspaces<
	TData = Awaited<ReturnType<typeof listWorkspaces>>,
	TError = unknown,
>(
	params?: ListWorkspacesParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listWorkspaces>>, TError, TData>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useListWorkspaces<
	TData = Awaited<ReturnType<typeof listWorkspaces>>,
	TError = unknown,
>(
	params?: ListWorkspacesParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listWorkspaces>>, TError, TData>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getListWorkspacesQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const getWorkspace = (
	{ id }: GetWorkspacePathParameters,
	signal?: AbortSignal,
) => {
	return apiRequest<WorkspaceDto>({
		url: `/workspace/${id}`,
		method: "GET",
		signal,
	});
};

export const getGetWorkspaceQueryKey = ({ id }: GetWorkspacePathParameters) => {
	return [`/workspace/${id}`] as const;
};

export const getGetWorkspaceQueryOptions = <
	TData = Awaited<ReturnType<typeof getWorkspace>>,
	TError = unknown,
>(
	{ id }: GetWorkspacePathParameters,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getWorkspace>>, TError, TData>
		>;
	},
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetWorkspaceQueryKey({ id });

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getWorkspace>>> = ({
		signal,
	}) => getWorkspace({ id }, signal);

	return {
		queryKey,
		queryFn,
		enabled: !!id,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getWorkspace>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetWorkspaceQueryResult = NonNullable<
	Awaited<ReturnType<typeof getWorkspace>>
>;
export type GetWorkspaceQueryError = unknown;

export function useGetWorkspace<
	TData = Awaited<ReturnType<typeof getWorkspace>>,
	TError = unknown,
>(
	pathParams: GetWorkspacePathParameters,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getWorkspace>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getWorkspace>>,
					TError,
					Awaited<ReturnType<typeof getWorkspace>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetWorkspace<
	TData = Awaited<ReturnType<typeof getWorkspace>>,
	TError = unknown,
>(
	pathParams: GetWorkspacePathParameters,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getWorkspace>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getWorkspace>>,
					TError,
					Awaited<ReturnType<typeof getWorkspace>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetWorkspace<
	TData = Awaited<ReturnType<typeof getWorkspace>>,
	TError = unknown,
>(
	pathParams: GetWorkspacePathParameters,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getWorkspace>>, TError, TData>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetWorkspace<
	TData = Awaited<ReturnType<typeof getWorkspace>>,
	TError = unknown,
>(
	{ id }: GetWorkspacePathParameters,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getWorkspace>>, TError, TData>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetWorkspaceQueryOptions({ id }, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const updateWorkspace = (
	{ id }: UpdateWorkspacePathParameters,
	updateWorkspaceDto: UpdateWorkspaceDto,
	signal?: AbortSignal,
) => {
	return apiRequest<WorkspaceDto>({
		url: `/workspace/${id}`,
		method: "PATCH",
		headers: { "Content-Type": "application/json" },
		data: updateWorkspaceDto,
		signal,
	});
};

export const getUpdateWorkspaceMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof updateWorkspace>>,
		TError,
		{ pathParams: UpdateWorkspacePathParameters; data: UpdateWorkspaceDto },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof updateWorkspace>>,
	TError,
	{ pathParams: UpdateWorkspacePathParameters; data: UpdateWorkspaceDto },
	TContext
> => {
	const mutationKey = ["updateWorkspace"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof updateWorkspace>>,
		{ pathParams: UpdateWorkspacePathParameters; data: UpdateWorkspaceDto }
	> = (props) => {
		const { pathParams, data } = props ?? {};

		return updateWorkspace(pathParams, data);
	};

	return { mutationFn, ...mutationOptions };
};

export type UpdateWorkspaceMutationResult = NonNullable<
	Awaited<ReturnType<typeof updateWorkspace>>
>;
export type UpdateWorkspaceMutationBody = UpdateWorkspaceDto;
export type UpdateWorkspaceMutationError = unknown;

export const useUpdateWorkspace = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof updateWorkspace>>,
			TError,
			{ pathParams: UpdateWorkspacePathParameters; data: UpdateWorkspaceDto },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof updateWorkspace>>,
	TError,
	{ pathParams: UpdateWorkspacePathParameters; data: UpdateWorkspaceDto },
	TContext
> => {
	return useMutation(getUpdateWorkspaceMutationOptions(options), queryClient);
};
export const deleteWorkspace = (
	{ id }: DeleteWorkspacePathParameters,
	signal?: AbortSignal,
) => {
	return apiRequest<WorkspaceDto>({
		url: `/workspace/${id}`,
		method: "DELETE",
		signal,
	});
};

export const getDeleteWorkspaceMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteWorkspace>>,
		TError,
		{ pathParams: DeleteWorkspacePathParameters },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteWorkspace>>,
	TError,
	{ pathParams: DeleteWorkspacePathParameters },
	TContext
> => {
	const mutationKey = ["deleteWorkspace"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteWorkspace>>,
		{ pathParams: DeleteWorkspacePathParameters }
	> = (props) => {
		const { pathParams } = props ?? {};

		return deleteWorkspace(pathParams);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteWorkspaceMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteWorkspace>>
>;

export type DeleteWorkspaceMutationError = unknown;

export const useDeleteWorkspace = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteWorkspace>>,
			TError,
			{ pathParams: DeleteWorkspacePathParameters },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof deleteWorkspace>>,
	TError,
	{ pathParams: DeleteWorkspacePathParameters },
	TContext
> => {
	return useMutation(getDeleteWorkspaceMutationOptions(options), queryClient);
};
