/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */
import { faker } from "@faker-js/faker"
import type { RequestHandlerOptions } from "msw"
import { HttpResponse, http } from "msw"
import type { WorkspaceDto, WorkspaceWithPermissionDto } from "../model"
import { PermissionType } from "../model"

export const getCreateWorkspaceResponseMock = (
	overrideResponse: Partial<Extract<WorkspaceDto, object>> = {},
): WorkspaceDto => ({
	createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
	createdBy: faker.number.float({ fractionDigits: 2 }),
	updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
	updatedBy: faker.number.float({ fractionDigits: 2 }),
	deletedAt: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			null,
		]),
		null,
	]),
	deletedBy: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.number.float({ fractionDigits: 2 }),
			null,
		]),
		null,
	]),
	id: faker.number.float({ fractionDigits: 2 }),
	title: faker.string.alpha({ length: { min: 10, max: 20 } }),
	urlName: faker.string.alpha({ length: { min: 10, max: 20 } }),
	icon: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		null,
	]),
	assigneeStatusEditable: faker.datatype.boolean(),
	chatNotification: faker.datatype.boolean(),
	mailNotification: faker.datatype.boolean(),
	pikudId: faker.number.float({ fractionDigits: 2 }),
	...overrideResponse,
})

export const getListWorkspacesResponseMock = (): WorkspaceWithPermissionDto[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		createdBy: faker.number.float({ fractionDigits: 2 }),
		updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
		updatedBy: faker.number.float({ fractionDigits: 2 }),
		deletedAt: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
				null,
			]),
			null,
		]),
		deletedBy: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.number.float({ fractionDigits: 2 }),
				null,
			]),
			null,
		]),
		id: faker.number.float({ fractionDigits: 2 }),
		title: faker.string.alpha({ length: { min: 10, max: 20 } }),
		urlName: faker.string.alpha({ length: { min: 10, max: 20 } }),
		icon: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			null,
		]),
		assigneeStatusEditable: faker.datatype.boolean(),
		chatNotification: faker.datatype.boolean(),
		mailNotification: faker.datatype.boolean(),
		pikudId: faker.number.float({ fractionDigits: 2 }),
		permissionType: faker.helpers.arrayElement(Object.values(PermissionType)),
	}))

export const getGetUserWorkspacesResponseMock =
	(): WorkspaceWithPermissionDto[] =>
		Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			createdBy: faker.number.float({ fractionDigits: 2 }),
			updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			updatedBy: faker.number.float({ fractionDigits: 2 }),
			deletedAt: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
					null,
				]),
				null,
			]),
			deletedBy: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					faker.number.float({ fractionDigits: 2 }),
					null,
				]),
				null,
			]),
			id: faker.number.float({ fractionDigits: 2 }),
			title: faker.string.alpha({ length: { min: 10, max: 20 } }),
			urlName: faker.string.alpha({ length: { min: 10, max: 20 } }),
			icon: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				null,
			]),
			assigneeStatusEditable: faker.datatype.boolean(),
			chatNotification: faker.datatype.boolean(),
			mailNotification: faker.datatype.boolean(),
			pikudId: faker.number.float({ fractionDigits: 2 }),
			permissionType: faker.helpers.arrayElement(Object.values(PermissionType)),
		}))

export const getGetWorkspaceResponseMock = (
	overrideResponse: Partial<Extract<WorkspaceDto, object>> = {},
): WorkspaceDto => ({
	createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
	createdBy: faker.number.float({ fractionDigits: 2 }),
	updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
	updatedBy: faker.number.float({ fractionDigits: 2 }),
	deletedAt: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			null,
		]),
		null,
	]),
	deletedBy: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.number.float({ fractionDigits: 2 }),
			null,
		]),
		null,
	]),
	id: faker.number.float({ fractionDigits: 2 }),
	title: faker.string.alpha({ length: { min: 10, max: 20 } }),
	urlName: faker.string.alpha({ length: { min: 10, max: 20 } }),
	icon: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		null,
	]),
	assigneeStatusEditable: faker.datatype.boolean(),
	chatNotification: faker.datatype.boolean(),
	mailNotification: faker.datatype.boolean(),
	pikudId: faker.number.float({ fractionDigits: 2 }),
	...overrideResponse,
})

export const getUpdateWorkspaceResponseMock = (
	overrideResponse: Partial<Extract<WorkspaceDto, object>> = {},
): WorkspaceDto => ({
	createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
	createdBy: faker.number.float({ fractionDigits: 2 }),
	updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
	updatedBy: faker.number.float({ fractionDigits: 2 }),
	deletedAt: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			null,
		]),
		null,
	]),
	deletedBy: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.number.float({ fractionDigits: 2 }),
			null,
		]),
		null,
	]),
	id: faker.number.float({ fractionDigits: 2 }),
	title: faker.string.alpha({ length: { min: 10, max: 20 } }),
	urlName: faker.string.alpha({ length: { min: 10, max: 20 } }),
	icon: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		null,
	]),
	assigneeStatusEditable: faker.datatype.boolean(),
	chatNotification: faker.datatype.boolean(),
	mailNotification: faker.datatype.boolean(),
	pikudId: faker.number.float({ fractionDigits: 2 }),
	...overrideResponse,
})

export const getDeleteWorkspaceResponseMock = (
	overrideResponse: Partial<Extract<WorkspaceDto, object>> = {},
): WorkspaceDto => ({
	createdAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
	createdBy: faker.number.float({ fractionDigits: 2 }),
	updatedAt: new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
	updatedBy: faker.number.float({ fractionDigits: 2 }),
	deletedAt: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			new Date(faker.date.past().toISOString().slice(0, 19) + "Z"),
			null,
		]),
		null,
	]),
	deletedBy: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.number.float({ fractionDigits: 2 }),
			null,
		]),
		null,
	]),
	id: faker.number.float({ fractionDigits: 2 }),
	title: faker.string.alpha({ length: { min: 10, max: 20 } }),
	urlName: faker.string.alpha({ length: { min: 10, max: 20 } }),
	icon: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		null,
	]),
	assigneeStatusEditable: faker.datatype.boolean(),
	chatNotification: faker.datatype.boolean(),
	mailNotification: faker.datatype.boolean(),
	pikudId: faker.number.float({ fractionDigits: 2 }),
	...overrideResponse,
})

export const getCreateWorkspaceMockHandler = (
	overrideResponse?:
		| WorkspaceDto
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<WorkspaceDto> | WorkspaceDto),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/workspace",
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getCreateWorkspaceResponseMock(),
				{ status: 201 },
			)
		},
		options,
	)
}

export const getListWorkspacesMockHandler = (
	overrideResponse?:
		| WorkspaceWithPermissionDto[]
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) =>
				| Promise<WorkspaceWithPermissionDto[]>
				| WorkspaceWithPermissionDto[]),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/workspace",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getListWorkspacesResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getGetUserWorkspacesMockHandler = (
	overrideResponse?:
		| WorkspaceWithPermissionDto[]
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) =>
				| Promise<WorkspaceWithPermissionDto[]>
				| WorkspaceWithPermissionDto[]),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/workspace/mine",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getGetUserWorkspacesResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getGetWorkspaceMockHandler = (
	overrideResponse?:
		| WorkspaceDto
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<WorkspaceDto> | WorkspaceDto),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/workspace/:id",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getGetWorkspaceResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getUpdateWorkspaceMockHandler = (
	overrideResponse?:
		| WorkspaceDto
		| ((
				info: Parameters<Parameters<typeof http.patch>[1]>[0],
		  ) => Promise<WorkspaceDto> | WorkspaceDto),
	options?: RequestHandlerOptions,
) => {
	return http.patch(
		"*/workspace/:id",
		async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getUpdateWorkspaceResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}

export const getDeleteWorkspaceMockHandler = (
	overrideResponse?:
		| WorkspaceDto
		| ((
				info: Parameters<Parameters<typeof http.delete>[1]>[0],
		  ) => Promise<WorkspaceDto> | WorkspaceDto),
	options?: RequestHandlerOptions,
) => {
	return http.delete(
		"*/workspace/:id",
		async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getDeleteWorkspaceResponseMock(),
				{ status: 200 },
			)
		},
		options,
	)
}
export const getWorkspaceMock = () => [
	getCreateWorkspaceMockHandler(),
	getListWorkspacesMockHandler(),
	getGetUserWorkspacesMockHandler(),
	getGetWorkspaceMockHandler(),
	getUpdateWorkspaceMockHandler(),
	getDeleteWorkspaceMockHandler(),
]
