/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query"
import { useQuery } from "@tanstack/react-query"
import type { ErrorType } from "../../axios"

import { sendRequest } from "../../axios"
import type { ListTaskHistoryParams, TaskHistoryDto } from "../model"

const withQueryKey = <T extends object, K>(
	query: T,
	queryKey: K,
): T & { queryKey: K } => {
	const result = { queryKey } as T & { queryKey: K }
	for (const key of Object.keys(query)) {
		// The explicit queryKey always wins, matching the previous
		// `{ ...query, queryKey }` spread where it was set last.
		if (key === "queryKey") continue
		Object.defineProperty(result, key, {
			enumerable: true,
			configurable: true,
			get: () => (query as Record<string, unknown>)[key],
		})
	}
	return result
}

export const listTaskHistory = (
	params: ListTaskHistoryParams,
	signal?: AbortSignal,
) => {
	return sendRequest<TaskHistoryDto[]>({
		url: `/task-history`,
		method: "GET",
		params,
		signal,
	})
}

export const getListTaskHistoryQueryKey = (params?: ListTaskHistoryParams) => {
	return [`/task-history`, ...(params ? [params] : [])] as const
}

export const getListTaskHistoryQueryOptions = <
	TData = Awaited<ReturnType<typeof listTaskHistory>>,
	TError = ErrorType<unknown>,
>(
	params: ListTaskHistoryParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof listTaskHistory>>,
				TError,
				TData
			>
		>
	},
) => {
	const { query: queryOptions } = options ?? {}

	const queryKey = queryOptions?.queryKey ?? getListTaskHistoryQueryKey(params)

	const queryFn: QueryFunction<Awaited<ReturnType<typeof listTaskHistory>>> = ({
		signal,
	}) => listTaskHistory(params, signal)

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof listTaskHistory>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListTaskHistoryQueryResult = NonNullable<
	Awaited<ReturnType<typeof listTaskHistory>>
>
export type ListTaskHistoryQueryError = ErrorType<unknown>

export function useListTaskHistory<
	TData = Awaited<ReturnType<typeof listTaskHistory>>,
	TError = ErrorType<unknown>,
>(
	params: ListTaskHistoryParams,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof listTaskHistory>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof listTaskHistory>>,
					TError,
					Awaited<ReturnType<typeof listTaskHistory>>
				>,
				"initialData"
			>
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}
export function useListTaskHistory<
	TData = Awaited<ReturnType<typeof listTaskHistory>>,
	TError = ErrorType<unknown>,
>(
	params: ListTaskHistoryParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof listTaskHistory>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof listTaskHistory>>,
					TError,
					Awaited<ReturnType<typeof listTaskHistory>>
				>,
				"initialData"
			>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}
export function useListTaskHistory<
	TData = Awaited<ReturnType<typeof listTaskHistory>>,
	TError = ErrorType<unknown>,
>(
	params: ListTaskHistoryParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof listTaskHistory>>,
				TError,
				TData
			>
		>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}

export function useListTaskHistory<
	TData = Awaited<ReturnType<typeof listTaskHistory>>,
	TError = ErrorType<unknown>,
>(
	params: ListTaskHistoryParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof listTaskHistory>>,
				TError,
				TData
			>
		>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
} {
	const queryOptions = getListTaskHistoryQueryOptions(params, options)

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> }

	return withQueryKey(query, queryOptions.queryKey)
}
