/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  GetTaskHistoryParams,
  TaskHistoryDto
} from '.././model';





export const getTaskHistory = (
    params: GetTaskHistoryParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TaskHistoryDto[]>> => {
    
    
    return axios.default.get(
      `/task-history`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetTaskHistoryQueryKey = (params?: GetTaskHistoryParams,) => {
    return [
    `/task-history`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetTaskHistoryQueryOptions = <TData = Awaited<ReturnType<typeof getTaskHistory>>, TError = AxiosError<unknown>>(params: GetTaskHistoryParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTaskHistory>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTaskHistoryQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTaskHistory>>> = ({ signal }) => getTaskHistory(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTaskHistory>>, TError, TData> & { queryKey: QueryKey }
}

export type GetTaskHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof getTaskHistory>>>
export type GetTaskHistoryQueryError = AxiosError<unknown>



export function useGetTaskHistory<TData = Awaited<ReturnType<typeof getTaskHistory>>, TError = AxiosError<unknown>>(
 params: GetTaskHistoryParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTaskHistory>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetTaskHistoryQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



