/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */
import type { DeadlineType } from "./deadline-type"

export interface AIExtractedTaskDto {
	title: string
	deadlineType?: DeadlineType | null
	/** @nullable */
	deadlineDate?: string | null
	assigneeIds: number[]
}
