/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */
import type { AssigneeDto } from "./assignee-dto"
import type { TaskDto } from "./task-dto"
import type { WorkspaceStatusDto } from "./workspace-status-dto"

export interface AssigneeTaskStatusDto {
	task: TaskDto
	assignee: AssigneeDto
	status: WorkspaceStatusDto
	description: string
}
