/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */
import type { AssigneeDto } from "./assignee-dto"
import type { WorkspaceStatusDto } from "./workspace-status-dto"

export interface AssigneeStatusDto {
	assignee: AssigneeDto
	status: WorkspaceStatusDto
	description: string
	editable: boolean
}
