/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */
import type { UserDto } from "./user-dto"

export interface AssigneeDto {
	createdAt: Date
	createdBy: number
	updatedAt: Date
	updatedBy: number
	/** @nullable */
	deletedAt: Date | null
	/** @nullable */
	deletedBy: number | null
	id: number
	name: string
	color: string
	/** @nullable */
	icon: string | null
	workspaceId: number
	users: UserDto[]
}
