/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */

export interface CreateWorkspaceDto {
	title: string
	urlName: string
	/** @nullable */
	icon?: string | null
	assigneeStatusEditable?: boolean
	pikudId: number
}
