/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */
import type { CreateUserDto } from "./create-user-dto"

export interface CreateAssigneeDto {
	workspaceId: number
	name: string
	color: string
	/** @nullable */
	icon?: string | null
	users: CreateUserDto[]
}
