/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */
import type { CreateWorkspaceRequestErrorDtoMessage } from "./create-workspace-request-error-dto-message"

export interface CreateWorkspaceRequestErrorDto {
	statusCode: number
	/** Specific error code key */
	message: CreateWorkspaceRequestErrorDtoMessage
	error?: string
}
