/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */
import type { DeadlineType } from "./deadline-type"
import type { GetTaskAssigneeDto } from "./get-task-assignee-dto"

export interface CreateSourceTaskDto {
	title: string
	deadlineType: DeadlineType
	/** @nullable */
	dueDate?: Date | null
	notes?: string
	flagged?: boolean
	assignees?: GetTaskAssigneeDto[]
}
