/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */
import type { GetUserInfoDto } from "./get-user-info-dto.ts"

export interface CreateUserDto {
	upn: string
	/** @nullable */
	info?: GetUserInfoDto | null
}
