/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */

export type ExtractionErrorReason =
	(typeof ExtractionErrorReason)[keyof typeof ExtractionErrorReason]

export const ExtractionErrorReason = {
	EXTRACTION: "EXTRACTION",
	AI_SERVICE: "AI_SERVICE",
} as const
