/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */

export type HistoryAction = (typeof HistoryAction)[keyof typeof HistoryAction]

export const HistoryAction = {
	CREATE: "CREATE",
	UPDATE: "UPDATE",
	DUPLICATE: "DUPLICATE",
	DELETE: "DELETE",
} as const
