/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */

export type ListMessagesParams = {
	taskId?: number
	taskIds?: number[]
	workspaceId?: number
	personal?: boolean
	isArchived?: boolean
}
