/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */
import type { MessageDtoDeletedAt } from "./message-dto-deleted-at";
import type { MessageDtoDeletedBy } from "./message-dto-deleted-by";

export interface MessageDto {
	createdAt: string;
	createdBy: number;
	updatedAt: string;
	updatedBy: number;
	/** @nullable */
	deletedAt: MessageDtoDeletedAt;
	/** @nullable */
	deletedBy: MessageDtoDeletedBy;
	id: number;
	content: string;
	assigneeId: number;
	taskId: number;
}
