/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */
import type { PermissionType } from "./permission-type"
import type { UserDto } from "./user-dto"

export interface PermissionDto {
	user: UserDto
	workspaceId: number
	type: PermissionType
}
