/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */
import type { PikudDtoDeletedAt } from './pikudDtoDeletedAt';
import type { PikudDtoDeletedBy } from './pikudDtoDeletedBy';

export interface PikudDto {
  createdAt: string;
  createdBy: number;
  updatedAt: string;
  updatedBy: number;
  /** @nullable */
  deletedAt: PikudDtoDeletedAt;
  /** @nullable */
  deletedBy: PikudDtoDeletedBy;
  id: number;
  name: string;
  /** @nullable */
  icon: string | null;
}
