/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */

export type SocketEvent = (typeof SocketEvent)[keyof typeof SocketEvent]

export const SocketEvent = {
	TASK_EXTRACTION_FINISHED: "TASK_EXTRACTION_FINISHED",
} as const
