/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */
import type { ExtractionStatus } from "./extraction-status"
import type { TagDto } from "./tag-dto"
import type { TaskDto } from "./task-dto"

export interface SourceWithTasksDto {
	createdAt: Date
	createdBy: number
	updatedAt: Date
	updatedBy: number
	/** @nullable */
	deletedAt: Date | null
	/** @nullable */
	deletedBy: number | null
	id: number
	name: string
	/** @nullable */
	date: Date | null
	workspaceId: number
	/** @nullable */
	attachmentKey: string | null
	/** @nullable */
	attachmentName: string | null
	draft: boolean
	extractionStatus: ExtractionStatus | null
	tags: TagDto[]
	tasks: TaskDto[]
}
