/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */

export interface TagDto {
	createdAt: Date
	createdBy: number
	updatedAt: Date
	updatedBy: number
	id: number
	name: string
	workspaceId: number
}
