/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */
import type { AssigneeStatusDto } from "./assignee-status-dto"
import type { DeadlineType } from "./deadline-type"
import type { MessageDto } from "./message-dto"
import type { SourceDto } from "./source-dto"
import type { TagDto } from "./tag-dto"
import type { TaskCreationType } from "./task-creation-type"
import type { WorkspaceStatusDto } from "./workspace-status-dto"

export interface TaskDto {
	createdAt: Date
	createdBy: number
	updatedAt: Date
	updatedBy: number
	/** @nullable */
	deletedAt: Date | null
	/** @nullable */
	deletedBy: number | null
	id: number
	title: string
	/** @nullable */
	description: string | null
	flagged: boolean
	deadlineType: DeadlineType
	creationType: TaskCreationType
	/** @nullable */
	dueDate: Date | null
	/** @nullable */
	notes: string | null
	/** @nullable */
	archivedAt: Date | null
	workspaceId: number
	status: WorkspaceStatusDto
	/** @nullable */
	source: SourceDto | null
	tags: TagDto[]
	lastMessage: MessageDto
	messageCount: number
	editable: boolean
	assigneeStatuses: AssigneeStatusDto[]
}
