/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */

export type TaskCreationType =
	(typeof TaskCreationType)[keyof typeof TaskCreationType]

export const TaskCreationType = {
	HUMAN: "HUMAN",
	AI_HUMAN: "AI_HUMAN",
	AI: "AI",
} as const
