/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */
import type { AssigneeStatusDto } from "./assignee-status-dto"
import type { SourceDto } from "./source-dto"
import type { TagDto } from "./tag-dto"
import type { TaskDtoDeletedAt } from "./task-dto-deleted-at"
import type { TaskDtoDeletedBy } from "./task-dto-deleted-by"

export interface TaskDto {
	createdAt: string
	createdBy: number
	updatedAt: string
	updatedBy: number
	/** @nullable */
	deletedAt: TaskDtoDeletedAt
	/** @nullable */
	deletedBy: TaskDtoDeletedBy
	id: number
	title: string
	/** @nullable */
	description: string | null
	flagged: boolean
	deadlineType: string
	issuedAt: string
	dueDate: string
	/** @nullable */
	notes: string | null
	workspaceId: number
	source: SourceDto
	tags: TagDto[]
	assigneeStatuses: AssigneeStatusDto[]
}
