/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */
import type { AssigneeStatusDto } from "./assignee-status-dto"
import type { DeadlineType } from "./deadline-type"
import type { SourceDto } from "./source-dto"
import type { TagDto } from "./tag-dto"

export interface TaskDto {
	createdAt: Date
	createdBy: number
	updatedAt: Date
	updatedBy: number
	/** @nullable */
	deletedAt: Date | null
	/** @nullable */
	deletedBy: number | null
	id: number
	title: string
	/** @nullable */
	description: string | null
	flagged: boolean
	deadlineType: DeadlineType
	dueDate: Date
	/** @nullable */
	notes: string | null
	workspaceId: number
	/** @nullable */
	source: SourceDto | null
	tags: TagDto[]
	assigneeStatuses: AssigneeStatusDto[]
}
