/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */
import type { AssigneeStatusDto } from "./assignee-status-dto"
import type { SourceDto } from "./source-dto"
import type { TagDto } from "./tag-dto"
import type { TaskWithWorkspaceDtoDeletedAt } from "./task-with-workspace-dto-deleted-at"
import type { TaskWithWorkspaceDtoDeletedBy } from "./task-with-workspace-dto-deleted-by"
import type { WorkspaceDto } from "./workspace-dto"

export interface TaskWithWorkspaceDto {
	createdAt: string
	createdBy: number
	updatedAt: string
	updatedBy: number
	/** @nullable */
	deletedAt: TaskWithWorkspaceDtoDeletedAt
	/** @nullable */
	deletedBy: TaskWithWorkspaceDtoDeletedBy
	id: number
	title: string
	/** @nullable */
	description: string | null
	flagged: boolean
	deadlineType: string
	issuedAt: string
	dueDate: string
	/** @nullable */
	notes: string | null
	workspaceId: number
	source: SourceDto
	tags: TagDto[]
	assigneeStatuses: AssigneeStatusDto[]
	workspace: WorkspaceDto
}
