/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */
import type { TaskHistoryAction } from "./task-history-action"

export interface TaskHistoryDto {
	id: number
	action: TaskHistoryAction
	field: string
	/** @nullable */
	value: string | null
	timestamp: Date
	taskId: number
	workspaceId: number
	userId: number
}
