/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */

export type TaskHistoryDtoAction = typeof TaskHistoryDtoAction[keyof typeof TaskHistoryDtoAction];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TaskHistoryDtoAction = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DUPLICATE: 'DUPLICATE',
  DELETE: 'DELETE',
} as const;
