/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */
import type { DeadlineType } from "./deadline-type"
import type { GetTaskAssigneeDto } from "./get-task-assignee-dto"
import type { TaskCreationType } from "./task-creation-type"

export interface UpdateTaskDto {
	title?: string
	description?: string
	flagged?: boolean
	deadlineType?: DeadlineType
	/** @nullable */
	dueDate?: Date | null
	notes?: string
	tags?: string[]
	creationType?: TaskCreationType
	/** @nullable */
	sourceId?: number | null
	assignees?: GetTaskAssigneeDto[]
	statusId?: number
}
