/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */
import type { WorkspaceStatusType } from "./workspace-status-type"

export interface UpdateWorkspaceStatusDto {
	name?: string
	color?: string
	type?: WorkspaceStatusType
}
