/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */

export interface UpdateAssigneeTaskStatusDto {
	taskId: number
	assigneeId: number
	statusId: number
	description?: string
}
