/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */
import type { UpdateWorkspaceErrorDtoMessage } from "./update-workspace-error-dto-message"

export interface UpdateWorkspaceErrorDto {
	statusCode: number
	/** Specific error code key */
	message: UpdateWorkspaceErrorDtoMessage
	error?: string
}
