/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */
import type { UpdateWorkspaceStatusDtoType } from "./update-workspace-status-dto-type"

export interface UpdateWorkspaceStatusDto {
	name?: string
	color?: string
	type?: UpdateWorkspaceStatusDtoType
}
