/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */
import type { UpdatePermissionDtoType } from './updatePermissionDtoType';

export interface UpdatePermissionDto {
  workspaceId: number;
  upn: string;
  type: UpdatePermissionDtoType;
}
