/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */

export type UpdatePermissionDtoType = typeof UpdatePermissionDtoType[keyof typeof UpdatePermissionDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdatePermissionDtoType = {
  VIEWER: 'VIEWER',
  MANAGER: 'MANAGER',
} as const;
