/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */

/**
 * Specific error code key
 */
export type UpdateWorkspaceRequestErrorDtoMessage =
	(typeof UpdateWorkspaceRequestErrorDtoMessage)[keyof typeof UpdateWorkspaceRequestErrorDtoMessage]

export const UpdateWorkspaceRequestErrorDtoMessage = {
	"workspace-request-not-found": "workspace-request-not-found",
	"urlname-exists": "urlname-exists",
	"title-exists": "title-exists",
	"pikud-not-found": "pikud-not-found",
} as const
