/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */

export interface UpdateWorkspaceDto {
	/** @nullable */
	icon?: string | null
	assigneeStatusEditable?: boolean
	chatNotification?: boolean
	mailNotification?: boolean
	pikudId?: number
	urlName?: string
	title?: string
}
