/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */
import type { ColumnFilterDto } from "./column-filter-dto"
import type { ColumnSortDto } from "./column-sort-dto"
import type { ColumnVisibilityDto } from "./column-visibility-dto"
import type { QuickFilter } from "./quick-filter"

export interface UserViewTableDto {
	sorting: ColumnSortDto[]
	columnFilters: ColumnFilterDto[]
	quickFilter: QuickFilter[]
	columnVisibility: ColumnVisibilityDto
}
