/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */
import type { WorkspaceRequestNotFoundErrorDtoMessage } from "./workspace-request-not-found-error-dto-message"

export interface WorkspaceRequestNotFoundErrorDto {
	statusCode: number
	/** Specific error code key */
	message: WorkspaceRequestNotFoundErrorDtoMessage
	error?: string
}
