/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */
import type { PermissionType } from "./permission-type"
import type { UserDto } from "./user-dto"

export interface WorkspaceWithPermissionDto {
	createdAt: Date
	createdBy: UserDto
	updatedAt: Date
	updatedBy: UserDto
	/** @nullable */
	deletedAt: Date | null
	/** @nullable */
	deletedBy: UserDto | null
	id: number
	title: string
	urlName: string
	/** @nullable */
	icon: string | null
	assigneeStatusEditable: boolean
	chatNotification: boolean
	mailNotification: boolean
	pikudId: number
	permissionType: PermissionType | null
}
