/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */

export interface WorkspaceStatusDto {
  id: number;
  name: string;
  color: string;
  statusType: string;
  workspaceId: number;
}
