/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */

export interface WorkspaceDto {
	createdAt: Date
	createdBy: number
	updatedAt: Date
	updatedBy: number
	/** @nullable */
	deletedAt: Date | null
	/** @nullable */
	deletedBy: number | null
	id: number
	title: string
	urlName: string
	/** @nullable */
	icon: string | null
	assigneeStatusEditable: boolean
	chatNotification: boolean
	mailNotification: boolean
	pikudId: number
}
