/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */
import type { WorkspaceDtoDeletedAt } from "./workspace-dto-deleted-at";
import type { WorkspaceDtoDeletedBy } from "./workspace-dto-deleted-by";
import type { WorkspaceDtoIcon } from "./workspace-dto-icon";

export interface WorkspaceDto {
	createdAt: string;
	createdBy: number;
	updatedAt: string;
	updatedBy: number;
	/** @nullable */
	deletedAt: WorkspaceDtoDeletedAt;
	/** @nullable */
	deletedBy: WorkspaceDtoDeletedBy;
	id: number;
	title: string;
	urlName: string;
	/** @nullable */
	icon: WorkspaceDtoIcon;
	assigneeStatusEditable: boolean;
	pikudId: number;
}
