/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewWorkspaceRouteImport } from './routes/new-workspace'
import { Route as PersonalRouteImport } from './routes/personal'
import { Route as WorkspaceUrlNameRouteRouteImport } from './routes/workspace/$urlName/route'
import { Route as PersonalTaskTaskIdRouteImport } from './routes/personal/task/$taskId'
import { Route as WorkspaceUrlNameIndexRouteImport } from './routes/workspace/$urlName/index'
import { Route as WorkspaceUrlNameDashboardRouteImport } from './routes/workspace/$urlName/dashboard'
import { Route as WorkspaceUrlNameSettingsRouteImport } from './routes/workspace/$urlName/settings'
import { Route as WorkspaceUrlNameTasksRouteImport } from './routes/workspace/$urlName/tasks'
import { Route as PersonalTaskTaskIdIndexRouteImport } from './routes/personal/task/$taskId/index'
import { Route as PersonalTaskTaskIdEditRouteImport } from './routes/personal/task/$taskId/edit'
import { Route as WorkspaceUrlNameDashboardNewRouteImport } from './routes/workspace/$urlName/dashboard/new'
import { Route as WorkspaceUrlNameSettingsIndexRouteImport } from './routes/workspace/$urlName/settings/index'
import { Route as WorkspaceUrlNameSettingsAssigneesRouteImport } from './routes/workspace/$urlName/settings/assignees'
import { Route as WorkspaceUrlNameSettingsGeneralRouteImport } from './routes/workspace/$urlName/settings/general'
import { Route as WorkspaceUrlNameSettingsPermissionsRouteImport } from './routes/workspace/$urlName/settings/permissions'
import { Route as WorkspaceUrlNameTasksIndexRouteImport } from './routes/workspace/$urlName/tasks/index'
import { Route as WorkspaceUrlNameTasksTaskIdRouteImport } from './routes/workspace/$urlName/tasks/$taskId'
import { Route as WorkspaceUrlNameTasksNewRouteImport } from './routes/workspace/$urlName/tasks/new'
import { Route as WorkspaceUrlNameDashboardTaskTaskIdRouteImport } from './routes/workspace/$urlName/dashboard/task/$taskId'
import { Route as WorkspaceUrlNameSettingsAssigneesAssigneeIdRouteImport } from './routes/workspace/$urlName/settings/assignees/$assigneeId'
import { Route as WorkspaceUrlNameSettingsAssigneesNewRouteImport } from './routes/workspace/$urlName/settings/assignees/new'
import { Route as WorkspaceUrlNameTasksTaskIdIndexRouteImport } from './routes/workspace/$urlName/tasks/$taskId/index'
import { Route as WorkspaceUrlNameTasksTaskIdEditRouteImport } from './routes/workspace/$urlName/tasks/$taskId/edit'
import { Route as WorkspaceUrlNameDashboardTaskTaskIdIndexRouteImport } from './routes/workspace/$urlName/dashboard/task/$taskId/index'
import { Route as WorkspaceUrlNameDashboardTaskTaskIdEditRouteImport } from './routes/workspace/$urlName/dashboard/task/$taskId/edit'
import { Route as WorkspaceUrlNameSettingsAssigneesAssigneeIdIndexRouteImport } from './routes/workspace/$urlName/settings/assignees/$assigneeId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewWorkspaceRoute = NewWorkspaceRouteImport.update({
  id: '/new-workspace',
  path: '/new-workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalRoute = PersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceUrlNameRouteRoute = WorkspaceUrlNameRouteRouteImport.update({
  id: '/workspace/$urlName',
  path: '/workspace/$urlName',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalTaskTaskIdRoute = PersonalTaskTaskIdRouteImport.update({
  id: '/task/$taskId',
  path: '/task/$taskId',
  getParentRoute: () => PersonalRoute,
} as any)
const WorkspaceUrlNameIndexRoute = WorkspaceUrlNameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceUrlNameRouteRoute,
} as any)
const WorkspaceUrlNameDashboardRoute =
  WorkspaceUrlNameDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => WorkspaceUrlNameRouteRoute,
  } as any)
const WorkspaceUrlNameSettingsRoute =
  WorkspaceUrlNameSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => WorkspaceUrlNameRouteRoute,
  } as any)
const WorkspaceUrlNameTasksRoute = WorkspaceUrlNameTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => WorkspaceUrlNameRouteRoute,
} as any)
const PersonalTaskTaskIdIndexRoute = PersonalTaskTaskIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PersonalTaskTaskIdRoute,
} as any)
const PersonalTaskTaskIdEditRoute = PersonalTaskTaskIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PersonalTaskTaskIdRoute,
} as any)
const WorkspaceUrlNameDashboardNewRoute =
  WorkspaceUrlNameDashboardNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => WorkspaceUrlNameDashboardRoute,
  } as any)
const WorkspaceUrlNameSettingsIndexRoute =
  WorkspaceUrlNameSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceUrlNameSettingsRoute,
  } as any)
const WorkspaceUrlNameSettingsAssigneesRoute =
  WorkspaceUrlNameSettingsAssigneesRouteImport.update({
    id: '/assignees',
    path: '/assignees',
    getParentRoute: () => WorkspaceUrlNameSettingsRoute,
  } as any)
const WorkspaceUrlNameSettingsGeneralRoute =
  WorkspaceUrlNameSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => WorkspaceUrlNameSettingsRoute,
  } as any)
const WorkspaceUrlNameSettingsPermissionsRoute =
  WorkspaceUrlNameSettingsPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => WorkspaceUrlNameSettingsRoute,
  } as any)
const WorkspaceUrlNameTasksIndexRoute =
  WorkspaceUrlNameTasksIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceUrlNameTasksRoute,
  } as any)
const WorkspaceUrlNameTasksTaskIdRoute =
  WorkspaceUrlNameTasksTaskIdRouteImport.update({
    id: '/$taskId',
    path: '/$taskId',
    getParentRoute: () => WorkspaceUrlNameTasksRoute,
  } as any)
const WorkspaceUrlNameTasksNewRoute =
  WorkspaceUrlNameTasksNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => WorkspaceUrlNameTasksRoute,
  } as any)
const WorkspaceUrlNameDashboardTaskTaskIdRoute =
  WorkspaceUrlNameDashboardTaskTaskIdRouteImport.update({
    id: '/task/$taskId',
    path: '/task/$taskId',
    getParentRoute: () => WorkspaceUrlNameDashboardRoute,
  } as any)
const WorkspaceUrlNameSettingsAssigneesAssigneeIdRoute =
  WorkspaceUrlNameSettingsAssigneesAssigneeIdRouteImport.update({
    id: '/$assigneeId',
    path: '/$assigneeId',
    getParentRoute: () => WorkspaceUrlNameSettingsAssigneesRoute,
  } as any)
const WorkspaceUrlNameSettingsAssigneesNewRoute =
  WorkspaceUrlNameSettingsAssigneesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => WorkspaceUrlNameSettingsAssigneesRoute,
  } as any)
const WorkspaceUrlNameTasksTaskIdIndexRoute =
  WorkspaceUrlNameTasksTaskIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceUrlNameTasksTaskIdRoute,
  } as any)
const WorkspaceUrlNameTasksTaskIdEditRoute =
  WorkspaceUrlNameTasksTaskIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => WorkspaceUrlNameTasksTaskIdRoute,
  } as any)
const WorkspaceUrlNameDashboardTaskTaskIdIndexRoute =
  WorkspaceUrlNameDashboardTaskTaskIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceUrlNameDashboardTaskTaskIdRoute,
  } as any)
const WorkspaceUrlNameDashboardTaskTaskIdEditRoute =
  WorkspaceUrlNameDashboardTaskTaskIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => WorkspaceUrlNameDashboardTaskTaskIdRoute,
  } as any)
const WorkspaceUrlNameSettingsAssigneesAssigneeIdIndexRoute =
  WorkspaceUrlNameSettingsAssigneesAssigneeIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceUrlNameSettingsAssigneesAssigneeIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new-workspace': typeof NewWorkspaceRoute
  '/personal': typeof PersonalRouteWithChildren
  '/workspace/$urlName': typeof WorkspaceUrlNameRouteRouteWithChildren
  '/personal/task/$taskId': typeof PersonalTaskTaskIdRouteWithChildren
  '/workspace/$urlName/dashboard': typeof WorkspaceUrlNameDashboardRouteWithChildren
  '/workspace/$urlName/settings': typeof WorkspaceUrlNameSettingsRouteWithChildren
  '/workspace/$urlName/tasks': typeof WorkspaceUrlNameTasksRouteWithChildren
  '/workspace/$urlName/': typeof WorkspaceUrlNameIndexRoute
  '/personal/task/$taskId/edit': typeof PersonalTaskTaskIdEditRoute
  '/workspace/$urlName/dashboard/new': typeof WorkspaceUrlNameDashboardNewRoute
  '/workspace/$urlName/settings/assignees': typeof WorkspaceUrlNameSettingsAssigneesRouteWithChildren
  '/workspace/$urlName/settings/general': typeof WorkspaceUrlNameSettingsGeneralRoute
  '/workspace/$urlName/settings/permissions': typeof WorkspaceUrlNameSettingsPermissionsRoute
  '/workspace/$urlName/tasks/$taskId': typeof WorkspaceUrlNameTasksTaskIdRouteWithChildren
  '/workspace/$urlName/tasks/new': typeof WorkspaceUrlNameTasksNewRoute
  '/personal/task/$taskId/': typeof PersonalTaskTaskIdIndexRoute
  '/workspace/$urlName/settings/': typeof WorkspaceUrlNameSettingsIndexRoute
  '/workspace/$urlName/tasks/': typeof WorkspaceUrlNameTasksIndexRoute
  '/workspace/$urlName/dashboard/task/$taskId': typeof WorkspaceUrlNameDashboardTaskTaskIdRouteWithChildren
  '/workspace/$urlName/settings/assignees/$assigneeId': typeof WorkspaceUrlNameSettingsAssigneesAssigneeIdRouteWithChildren
  '/workspace/$urlName/settings/assignees/new': typeof WorkspaceUrlNameSettingsAssigneesNewRoute
  '/workspace/$urlName/tasks/$taskId/edit': typeof WorkspaceUrlNameTasksTaskIdEditRoute
  '/workspace/$urlName/tasks/$taskId/': typeof WorkspaceUrlNameTasksTaskIdIndexRoute
  '/workspace/$urlName/dashboard/task/$taskId/edit': typeof WorkspaceUrlNameDashboardTaskTaskIdEditRoute
  '/workspace/$urlName/dashboard/task/$taskId/': typeof WorkspaceUrlNameDashboardTaskTaskIdIndexRoute
  '/workspace/$urlName/settings/assignees/$assigneeId/': typeof WorkspaceUrlNameSettingsAssigneesAssigneeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new-workspace': typeof NewWorkspaceRoute
  '/personal': typeof PersonalRouteWithChildren
  '/workspace/$urlName/dashboard': typeof WorkspaceUrlNameDashboardRouteWithChildren
  '/workspace/$urlName': typeof WorkspaceUrlNameIndexRoute
  '/personal/task/$taskId/edit': typeof PersonalTaskTaskIdEditRoute
  '/workspace/$urlName/dashboard/new': typeof WorkspaceUrlNameDashboardNewRoute
  '/workspace/$urlName/settings/assignees': typeof WorkspaceUrlNameSettingsAssigneesRouteWithChildren
  '/workspace/$urlName/settings/general': typeof WorkspaceUrlNameSettingsGeneralRoute
  '/workspace/$urlName/settings/permissions': typeof WorkspaceUrlNameSettingsPermissionsRoute
  '/workspace/$urlName/tasks/new': typeof WorkspaceUrlNameTasksNewRoute
  '/personal/task/$taskId': typeof PersonalTaskTaskIdIndexRoute
  '/workspace/$urlName/settings': typeof WorkspaceUrlNameSettingsIndexRoute
  '/workspace/$urlName/tasks': typeof WorkspaceUrlNameTasksIndexRoute
  '/workspace/$urlName/settings/assignees/new': typeof WorkspaceUrlNameSettingsAssigneesNewRoute
  '/workspace/$urlName/tasks/$taskId/edit': typeof WorkspaceUrlNameTasksTaskIdEditRoute
  '/workspace/$urlName/tasks/$taskId': typeof WorkspaceUrlNameTasksTaskIdIndexRoute
  '/workspace/$urlName/dashboard/task/$taskId/edit': typeof WorkspaceUrlNameDashboardTaskTaskIdEditRoute
  '/workspace/$urlName/dashboard/task/$taskId': typeof WorkspaceUrlNameDashboardTaskTaskIdIndexRoute
  '/workspace/$urlName/settings/assignees/$assigneeId': typeof WorkspaceUrlNameSettingsAssigneesAssigneeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new-workspace': typeof NewWorkspaceRoute
  '/personal': typeof PersonalRouteWithChildren
  '/workspace/$urlName': typeof WorkspaceUrlNameRouteRouteWithChildren
  '/personal/task/$taskId': typeof PersonalTaskTaskIdRouteWithChildren
  '/workspace/$urlName/dashboard': typeof WorkspaceUrlNameDashboardRouteWithChildren
  '/workspace/$urlName/settings': typeof WorkspaceUrlNameSettingsRouteWithChildren
  '/workspace/$urlName/tasks': typeof WorkspaceUrlNameTasksRouteWithChildren
  '/workspace/$urlName/': typeof WorkspaceUrlNameIndexRoute
  '/personal/task/$taskId/edit': typeof PersonalTaskTaskIdEditRoute
  '/workspace/$urlName/dashboard/new': typeof WorkspaceUrlNameDashboardNewRoute
  '/workspace/$urlName/settings/assignees': typeof WorkspaceUrlNameSettingsAssigneesRouteWithChildren
  '/workspace/$urlName/settings/general': typeof WorkspaceUrlNameSettingsGeneralRoute
  '/workspace/$urlName/settings/permissions': typeof WorkspaceUrlNameSettingsPermissionsRoute
  '/workspace/$urlName/tasks/$taskId': typeof WorkspaceUrlNameTasksTaskIdRouteWithChildren
  '/workspace/$urlName/tasks/new': typeof WorkspaceUrlNameTasksNewRoute
  '/personal/task/$taskId/': typeof PersonalTaskTaskIdIndexRoute
  '/workspace/$urlName/settings/': typeof WorkspaceUrlNameSettingsIndexRoute
  '/workspace/$urlName/tasks/': typeof WorkspaceUrlNameTasksIndexRoute
  '/workspace/$urlName/dashboard/task/$taskId': typeof WorkspaceUrlNameDashboardTaskTaskIdRouteWithChildren
  '/workspace/$urlName/settings/assignees/$assigneeId': typeof WorkspaceUrlNameSettingsAssigneesAssigneeIdRouteWithChildren
  '/workspace/$urlName/settings/assignees/new': typeof WorkspaceUrlNameSettingsAssigneesNewRoute
  '/workspace/$urlName/tasks/$taskId/edit': typeof WorkspaceUrlNameTasksTaskIdEditRoute
  '/workspace/$urlName/tasks/$taskId/': typeof WorkspaceUrlNameTasksTaskIdIndexRoute
  '/workspace/$urlName/dashboard/task/$taskId/edit': typeof WorkspaceUrlNameDashboardTaskTaskIdEditRoute
  '/workspace/$urlName/dashboard/task/$taskId/': typeof WorkspaceUrlNameDashboardTaskTaskIdIndexRoute
  '/workspace/$urlName/settings/assignees/$assigneeId/': typeof WorkspaceUrlNameSettingsAssigneesAssigneeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/new-workspace'
    | '/personal'
    | '/workspace/$urlName'
    | '/personal/task/$taskId'
    | '/workspace/$urlName/dashboard'
    | '/workspace/$urlName/settings'
    | '/workspace/$urlName/tasks'
    | '/workspace/$urlName/'
    | '/personal/task/$taskId/edit'
    | '/workspace/$urlName/dashboard/new'
    | '/workspace/$urlName/settings/assignees'
    | '/workspace/$urlName/settings/general'
    | '/workspace/$urlName/settings/permissions'
    | '/workspace/$urlName/tasks/$taskId'
    | '/workspace/$urlName/tasks/new'
    | '/personal/task/$taskId/'
    | '/workspace/$urlName/settings/'
    | '/workspace/$urlName/tasks/'
    | '/workspace/$urlName/dashboard/task/$taskId'
    | '/workspace/$urlName/settings/assignees/$assigneeId'
    | '/workspace/$urlName/settings/assignees/new'
    | '/workspace/$urlName/tasks/$taskId/edit'
    | '/workspace/$urlName/tasks/$taskId/'
    | '/workspace/$urlName/dashboard/task/$taskId/edit'
    | '/workspace/$urlName/dashboard/task/$taskId/'
    | '/workspace/$urlName/settings/assignees/$assigneeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/new-workspace'
    | '/personal'
    | '/workspace/$urlName/dashboard'
    | '/workspace/$urlName'
    | '/personal/task/$taskId/edit'
    | '/workspace/$urlName/dashboard/new'
    | '/workspace/$urlName/settings/assignees'
    | '/workspace/$urlName/settings/general'
    | '/workspace/$urlName/settings/permissions'
    | '/workspace/$urlName/tasks/new'
    | '/personal/task/$taskId'
    | '/workspace/$urlName/settings'
    | '/workspace/$urlName/tasks'
    | '/workspace/$urlName/settings/assignees/new'
    | '/workspace/$urlName/tasks/$taskId/edit'
    | '/workspace/$urlName/tasks/$taskId'
    | '/workspace/$urlName/dashboard/task/$taskId/edit'
    | '/workspace/$urlName/dashboard/task/$taskId'
    | '/workspace/$urlName/settings/assignees/$assigneeId'
  id:
    | '__root__'
    | '/'
    | '/new-workspace'
    | '/personal'
    | '/workspace/$urlName'
    | '/personal/task/$taskId'
    | '/workspace/$urlName/dashboard'
    | '/workspace/$urlName/settings'
    | '/workspace/$urlName/tasks'
    | '/workspace/$urlName/'
    | '/personal/task/$taskId/edit'
    | '/workspace/$urlName/dashboard/new'
    | '/workspace/$urlName/settings/assignees'
    | '/workspace/$urlName/settings/general'
    | '/workspace/$urlName/settings/permissions'
    | '/workspace/$urlName/tasks/$taskId'
    | '/workspace/$urlName/tasks/new'
    | '/personal/task/$taskId/'
    | '/workspace/$urlName/settings/'
    | '/workspace/$urlName/tasks/'
    | '/workspace/$urlName/dashboard/task/$taskId'
    | '/workspace/$urlName/settings/assignees/$assigneeId'
    | '/workspace/$urlName/settings/assignees/new'
    | '/workspace/$urlName/tasks/$taskId/edit'
    | '/workspace/$urlName/tasks/$taskId/'
    | '/workspace/$urlName/dashboard/task/$taskId/edit'
    | '/workspace/$urlName/dashboard/task/$taskId/'
    | '/workspace/$urlName/settings/assignees/$assigneeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewWorkspaceRoute: typeof NewWorkspaceRoute
  PersonalRoute: typeof PersonalRouteWithChildren
  WorkspaceUrlNameRouteRoute: typeof WorkspaceUrlNameRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-workspace': {
      id: '/new-workspace'
      path: '/new-workspace'
      fullPath: '/new-workspace'
      preLoaderRoute: typeof NewWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal': {
      id: '/personal'
      path: '/personal'
      fullPath: '/personal'
      preLoaderRoute: typeof PersonalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$urlName': {
      id: '/workspace/$urlName'
      path: '/workspace/$urlName'
      fullPath: '/workspace/$urlName'
      preLoaderRoute: typeof WorkspaceUrlNameRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal/task/$taskId': {
      id: '/personal/task/$taskId'
      path: '/task/$taskId'
      fullPath: '/personal/task/$taskId'
      preLoaderRoute: typeof PersonalTaskTaskIdRouteImport
      parentRoute: typeof PersonalRoute
    }
    '/workspace/$urlName/': {
      id: '/workspace/$urlName/'
      path: '/'
      fullPath: '/workspace/$urlName/'
      preLoaderRoute: typeof WorkspaceUrlNameIndexRouteImport
      parentRoute: typeof WorkspaceUrlNameRouteRoute
    }
    '/workspace/$urlName/dashboard': {
      id: '/workspace/$urlName/dashboard'
      path: '/dashboard'
      fullPath: '/workspace/$urlName/dashboard'
      preLoaderRoute: typeof WorkspaceUrlNameDashboardRouteImport
      parentRoute: typeof WorkspaceUrlNameRouteRoute
    }
    '/workspace/$urlName/settings': {
      id: '/workspace/$urlName/settings'
      path: '/settings'
      fullPath: '/workspace/$urlName/settings'
      preLoaderRoute: typeof WorkspaceUrlNameSettingsRouteImport
      parentRoute: typeof WorkspaceUrlNameRouteRoute
    }
    '/workspace/$urlName/tasks': {
      id: '/workspace/$urlName/tasks'
      path: '/tasks'
      fullPath: '/workspace/$urlName/tasks'
      preLoaderRoute: typeof WorkspaceUrlNameTasksRouteImport
      parentRoute: typeof WorkspaceUrlNameRouteRoute
    }
    '/personal/task/$taskId/': {
      id: '/personal/task/$taskId/'
      path: '/'
      fullPath: '/personal/task/$taskId/'
      preLoaderRoute: typeof PersonalTaskTaskIdIndexRouteImport
      parentRoute: typeof PersonalTaskTaskIdRoute
    }
    '/personal/task/$taskId/edit': {
      id: '/personal/task/$taskId/edit'
      path: '/edit'
      fullPath: '/personal/task/$taskId/edit'
      preLoaderRoute: typeof PersonalTaskTaskIdEditRouteImport
      parentRoute: typeof PersonalTaskTaskIdRoute
    }
    '/workspace/$urlName/dashboard/new': {
      id: '/workspace/$urlName/dashboard/new'
      path: '/new'
      fullPath: '/workspace/$urlName/dashboard/new'
      preLoaderRoute: typeof WorkspaceUrlNameDashboardNewRouteImport
      parentRoute: typeof WorkspaceUrlNameDashboardRoute
    }
    '/workspace/$urlName/settings/': {
      id: '/workspace/$urlName/settings/'
      path: '/'
      fullPath: '/workspace/$urlName/settings/'
      preLoaderRoute: typeof WorkspaceUrlNameSettingsIndexRouteImport
      parentRoute: typeof WorkspaceUrlNameSettingsRoute
    }
    '/workspace/$urlName/settings/assignees': {
      id: '/workspace/$urlName/settings/assignees'
      path: '/assignees'
      fullPath: '/workspace/$urlName/settings/assignees'
      preLoaderRoute: typeof WorkspaceUrlNameSettingsAssigneesRouteImport
      parentRoute: typeof WorkspaceUrlNameSettingsRoute
    }
    '/workspace/$urlName/settings/general': {
      id: '/workspace/$urlName/settings/general'
      path: '/general'
      fullPath: '/workspace/$urlName/settings/general'
      preLoaderRoute: typeof WorkspaceUrlNameSettingsGeneralRouteImport
      parentRoute: typeof WorkspaceUrlNameSettingsRoute
    }
    '/workspace/$urlName/settings/permissions': {
      id: '/workspace/$urlName/settings/permissions'
      path: '/permissions'
      fullPath: '/workspace/$urlName/settings/permissions'
      preLoaderRoute: typeof WorkspaceUrlNameSettingsPermissionsRouteImport
      parentRoute: typeof WorkspaceUrlNameSettingsRoute
    }
    '/workspace/$urlName/tasks/': {
      id: '/workspace/$urlName/tasks/'
      path: '/'
      fullPath: '/workspace/$urlName/tasks/'
      preLoaderRoute: typeof WorkspaceUrlNameTasksIndexRouteImport
      parentRoute: typeof WorkspaceUrlNameTasksRoute
    }
    '/workspace/$urlName/tasks/$taskId': {
      id: '/workspace/$urlName/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/workspace/$urlName/tasks/$taskId'
      preLoaderRoute: typeof WorkspaceUrlNameTasksTaskIdRouteImport
      parentRoute: typeof WorkspaceUrlNameTasksRoute
    }
    '/workspace/$urlName/tasks/new': {
      id: '/workspace/$urlName/tasks/new'
      path: '/new'
      fullPath: '/workspace/$urlName/tasks/new'
      preLoaderRoute: typeof WorkspaceUrlNameTasksNewRouteImport
      parentRoute: typeof WorkspaceUrlNameTasksRoute
    }
    '/workspace/$urlName/dashboard/task/$taskId': {
      id: '/workspace/$urlName/dashboard/task/$taskId'
      path: '/task/$taskId'
      fullPath: '/workspace/$urlName/dashboard/task/$taskId'
      preLoaderRoute: typeof WorkspaceUrlNameDashboardTaskTaskIdRouteImport
      parentRoute: typeof WorkspaceUrlNameDashboardRoute
    }
    '/workspace/$urlName/settings/assignees/$assigneeId': {
      id: '/workspace/$urlName/settings/assignees/$assigneeId'
      path: '/$assigneeId'
      fullPath: '/workspace/$urlName/settings/assignees/$assigneeId'
      preLoaderRoute: typeof WorkspaceUrlNameSettingsAssigneesAssigneeIdRouteImport
      parentRoute: typeof WorkspaceUrlNameSettingsAssigneesRoute
    }
    '/workspace/$urlName/settings/assignees/new': {
      id: '/workspace/$urlName/settings/assignees/new'
      path: '/new'
      fullPath: '/workspace/$urlName/settings/assignees/new'
      preLoaderRoute: typeof WorkspaceUrlNameSettingsAssigneesNewRouteImport
      parentRoute: typeof WorkspaceUrlNameSettingsAssigneesRoute
    }
    '/workspace/$urlName/tasks/$taskId/': {
      id: '/workspace/$urlName/tasks/$taskId/'
      path: '/'
      fullPath: '/workspace/$urlName/tasks/$taskId/'
      preLoaderRoute: typeof WorkspaceUrlNameTasksTaskIdIndexRouteImport
      parentRoute: typeof WorkspaceUrlNameTasksTaskIdRoute
    }
    '/workspace/$urlName/tasks/$taskId/edit': {
      id: '/workspace/$urlName/tasks/$taskId/edit'
      path: '/edit'
      fullPath: '/workspace/$urlName/tasks/$taskId/edit'
      preLoaderRoute: typeof WorkspaceUrlNameTasksTaskIdEditRouteImport
      parentRoute: typeof WorkspaceUrlNameTasksTaskIdRoute
    }
    '/workspace/$urlName/dashboard/task/$taskId/': {
      id: '/workspace/$urlName/dashboard/task/$taskId/'
      path: '/'
      fullPath: '/workspace/$urlName/dashboard/task/$taskId/'
      preLoaderRoute: typeof WorkspaceUrlNameDashboardTaskTaskIdIndexRouteImport
      parentRoute: typeof WorkspaceUrlNameDashboardTaskTaskIdRoute
    }
    '/workspace/$urlName/dashboard/task/$taskId/edit': {
      id: '/workspace/$urlName/dashboard/task/$taskId/edit'
      path: '/edit'
      fullPath: '/workspace/$urlName/dashboard/task/$taskId/edit'
      preLoaderRoute: typeof WorkspaceUrlNameDashboardTaskTaskIdEditRouteImport
      parentRoute: typeof WorkspaceUrlNameDashboardTaskTaskIdRoute
    }
    '/workspace/$urlName/settings/assignees/$assigneeId/': {
      id: '/workspace/$urlName/settings/assignees/$assigneeId/'
      path: '/'
      fullPath: '/workspace/$urlName/settings/assignees/$assigneeId/'
      preLoaderRoute: typeof WorkspaceUrlNameSettingsAssigneesAssigneeIdIndexRouteImport
      parentRoute: typeof WorkspaceUrlNameSettingsAssigneesAssigneeIdRoute
    }
  }
}

interface PersonalTaskTaskIdRouteChildren {
  PersonalTaskTaskIdEditRoute: typeof PersonalTaskTaskIdEditRoute
  PersonalTaskTaskIdIndexRoute: typeof PersonalTaskTaskIdIndexRoute
}

const PersonalTaskTaskIdRouteChildren: PersonalTaskTaskIdRouteChildren = {
  PersonalTaskTaskIdEditRoute: PersonalTaskTaskIdEditRoute,
  PersonalTaskTaskIdIndexRoute: PersonalTaskTaskIdIndexRoute,
}

const PersonalTaskTaskIdRouteWithChildren =
  PersonalTaskTaskIdRoute._addFileChildren(PersonalTaskTaskIdRouteChildren)

interface PersonalRouteChildren {
  PersonalTaskTaskIdRoute: typeof PersonalTaskTaskIdRouteWithChildren
}

const PersonalRouteChildren: PersonalRouteChildren = {
  PersonalTaskTaskIdRoute: PersonalTaskTaskIdRouteWithChildren,
}

const PersonalRouteWithChildren = PersonalRoute._addFileChildren(
  PersonalRouteChildren,
)

interface WorkspaceUrlNameDashboardTaskTaskIdRouteChildren {
  WorkspaceUrlNameDashboardTaskTaskIdEditRoute: typeof WorkspaceUrlNameDashboardTaskTaskIdEditRoute
  WorkspaceUrlNameDashboardTaskTaskIdIndexRoute: typeof WorkspaceUrlNameDashboardTaskTaskIdIndexRoute
}

const WorkspaceUrlNameDashboardTaskTaskIdRouteChildren: WorkspaceUrlNameDashboardTaskTaskIdRouteChildren =
  {
    WorkspaceUrlNameDashboardTaskTaskIdEditRoute:
      WorkspaceUrlNameDashboardTaskTaskIdEditRoute,
    WorkspaceUrlNameDashboardTaskTaskIdIndexRoute:
      WorkspaceUrlNameDashboardTaskTaskIdIndexRoute,
  }

const WorkspaceUrlNameDashboardTaskTaskIdRouteWithChildren =
  WorkspaceUrlNameDashboardTaskTaskIdRoute._addFileChildren(
    WorkspaceUrlNameDashboardTaskTaskIdRouteChildren,
  )

interface WorkspaceUrlNameDashboardRouteChildren {
  WorkspaceUrlNameDashboardNewRoute: typeof WorkspaceUrlNameDashboardNewRoute
  WorkspaceUrlNameDashboardTaskTaskIdRoute: typeof WorkspaceUrlNameDashboardTaskTaskIdRouteWithChildren
}

const WorkspaceUrlNameDashboardRouteChildren: WorkspaceUrlNameDashboardRouteChildren =
  {
    WorkspaceUrlNameDashboardNewRoute: WorkspaceUrlNameDashboardNewRoute,
    WorkspaceUrlNameDashboardTaskTaskIdRoute:
      WorkspaceUrlNameDashboardTaskTaskIdRouteWithChildren,
  }

const WorkspaceUrlNameDashboardRouteWithChildren =
  WorkspaceUrlNameDashboardRoute._addFileChildren(
    WorkspaceUrlNameDashboardRouteChildren,
  )

interface WorkspaceUrlNameSettingsAssigneesAssigneeIdRouteChildren {
  WorkspaceUrlNameSettingsAssigneesAssigneeIdIndexRoute: typeof WorkspaceUrlNameSettingsAssigneesAssigneeIdIndexRoute
}

const WorkspaceUrlNameSettingsAssigneesAssigneeIdRouteChildren: WorkspaceUrlNameSettingsAssigneesAssigneeIdRouteChildren =
  {
    WorkspaceUrlNameSettingsAssigneesAssigneeIdIndexRoute:
      WorkspaceUrlNameSettingsAssigneesAssigneeIdIndexRoute,
  }

const WorkspaceUrlNameSettingsAssigneesAssigneeIdRouteWithChildren =
  WorkspaceUrlNameSettingsAssigneesAssigneeIdRoute._addFileChildren(
    WorkspaceUrlNameSettingsAssigneesAssigneeIdRouteChildren,
  )

interface WorkspaceUrlNameSettingsAssigneesRouteChildren {
  WorkspaceUrlNameSettingsAssigneesAssigneeIdRoute: typeof WorkspaceUrlNameSettingsAssigneesAssigneeIdRouteWithChildren
  WorkspaceUrlNameSettingsAssigneesNewRoute: typeof WorkspaceUrlNameSettingsAssigneesNewRoute
}

const WorkspaceUrlNameSettingsAssigneesRouteChildren: WorkspaceUrlNameSettingsAssigneesRouteChildren =
  {
    WorkspaceUrlNameSettingsAssigneesAssigneeIdRoute:
      WorkspaceUrlNameSettingsAssigneesAssigneeIdRouteWithChildren,
    WorkspaceUrlNameSettingsAssigneesNewRoute:
      WorkspaceUrlNameSettingsAssigneesNewRoute,
  }

const WorkspaceUrlNameSettingsAssigneesRouteWithChildren =
  WorkspaceUrlNameSettingsAssigneesRoute._addFileChildren(
    WorkspaceUrlNameSettingsAssigneesRouteChildren,
  )

interface WorkspaceUrlNameSettingsRouteChildren {
  WorkspaceUrlNameSettingsAssigneesRoute: typeof WorkspaceUrlNameSettingsAssigneesRouteWithChildren
  WorkspaceUrlNameSettingsGeneralRoute: typeof WorkspaceUrlNameSettingsGeneralRoute
  WorkspaceUrlNameSettingsPermissionsRoute: typeof WorkspaceUrlNameSettingsPermissionsRoute
  WorkspaceUrlNameSettingsIndexRoute: typeof WorkspaceUrlNameSettingsIndexRoute
}

const WorkspaceUrlNameSettingsRouteChildren: WorkspaceUrlNameSettingsRouteChildren =
  {
    WorkspaceUrlNameSettingsAssigneesRoute:
      WorkspaceUrlNameSettingsAssigneesRouteWithChildren,
    WorkspaceUrlNameSettingsGeneralRoute: WorkspaceUrlNameSettingsGeneralRoute,
    WorkspaceUrlNameSettingsPermissionsRoute:
      WorkspaceUrlNameSettingsPermissionsRoute,
    WorkspaceUrlNameSettingsIndexRoute: WorkspaceUrlNameSettingsIndexRoute,
  }

const WorkspaceUrlNameSettingsRouteWithChildren =
  WorkspaceUrlNameSettingsRoute._addFileChildren(
    WorkspaceUrlNameSettingsRouteChildren,
  )

interface WorkspaceUrlNameTasksTaskIdRouteChildren {
  WorkspaceUrlNameTasksTaskIdEditRoute: typeof WorkspaceUrlNameTasksTaskIdEditRoute
  WorkspaceUrlNameTasksTaskIdIndexRoute: typeof WorkspaceUrlNameTasksTaskIdIndexRoute
}

const WorkspaceUrlNameTasksTaskIdRouteChildren: WorkspaceUrlNameTasksTaskIdRouteChildren =
  {
    WorkspaceUrlNameTasksTaskIdEditRoute: WorkspaceUrlNameTasksTaskIdEditRoute,
    WorkspaceUrlNameTasksTaskIdIndexRoute:
      WorkspaceUrlNameTasksTaskIdIndexRoute,
  }

const WorkspaceUrlNameTasksTaskIdRouteWithChildren =
  WorkspaceUrlNameTasksTaskIdRoute._addFileChildren(
    WorkspaceUrlNameTasksTaskIdRouteChildren,
  )

interface WorkspaceUrlNameTasksRouteChildren {
  WorkspaceUrlNameTasksTaskIdRoute: typeof WorkspaceUrlNameTasksTaskIdRouteWithChildren
  WorkspaceUrlNameTasksNewRoute: typeof WorkspaceUrlNameTasksNewRoute
  WorkspaceUrlNameTasksIndexRoute: typeof WorkspaceUrlNameTasksIndexRoute
}

const WorkspaceUrlNameTasksRouteChildren: WorkspaceUrlNameTasksRouteChildren = {
  WorkspaceUrlNameTasksTaskIdRoute:
    WorkspaceUrlNameTasksTaskIdRouteWithChildren,
  WorkspaceUrlNameTasksNewRoute: WorkspaceUrlNameTasksNewRoute,
  WorkspaceUrlNameTasksIndexRoute: WorkspaceUrlNameTasksIndexRoute,
}

const WorkspaceUrlNameTasksRouteWithChildren =
  WorkspaceUrlNameTasksRoute._addFileChildren(
    WorkspaceUrlNameTasksRouteChildren,
  )

interface WorkspaceUrlNameRouteRouteChildren {
  WorkspaceUrlNameDashboardRoute: typeof WorkspaceUrlNameDashboardRouteWithChildren
  WorkspaceUrlNameSettingsRoute: typeof WorkspaceUrlNameSettingsRouteWithChildren
  WorkspaceUrlNameTasksRoute: typeof WorkspaceUrlNameTasksRouteWithChildren
  WorkspaceUrlNameIndexRoute: typeof WorkspaceUrlNameIndexRoute
}

const WorkspaceUrlNameRouteRouteChildren: WorkspaceUrlNameRouteRouteChildren = {
  WorkspaceUrlNameDashboardRoute: WorkspaceUrlNameDashboardRouteWithChildren,
  WorkspaceUrlNameSettingsRoute: WorkspaceUrlNameSettingsRouteWithChildren,
  WorkspaceUrlNameTasksRoute: WorkspaceUrlNameTasksRouteWithChildren,
  WorkspaceUrlNameIndexRoute: WorkspaceUrlNameIndexRoute,
}

const WorkspaceUrlNameRouteRouteWithChildren =
  WorkspaceUrlNameRouteRoute._addFileChildren(
    WorkspaceUrlNameRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewWorkspaceRoute: NewWorkspaceRoute,
  PersonalRoute: PersonalRouteWithChildren,
  WorkspaceUrlNameRouteRoute: WorkspaceUrlNameRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
