/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Vector
 * The Vector API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreatePikudDto,
  PikudDto
} from '.././model';





export const createPikud = (
  createPikudDto: CreatePikudDto, options?: AxiosRequestConfig
): Promise<AxiosResponse<PikudDto>> => {


  return axios.default.post(
    `/pikud`,
    createPikudDto, options
  );
}



export const getCreatePikudMutationOptions = <TError = AxiosError<unknown>,
  TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof createPikud>>, TError, { data: CreatePikudDto }, TContext>, axios?: AxiosRequestConfig }
  ): UseMutationOptions<Awaited<ReturnType<typeof createPikud>>, TError, { data: CreatePikudDto }, TContext> => {

  const mutationKey = ['createPikud'];
  const { mutation: mutationOptions, axios: axiosOptions } = options ?
    options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey, }, axios: undefined };




  const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPikud>>, { data: CreatePikudDto }> = (props) => {
    const { data } = props ?? {};

    return createPikud(data, axiosOptions)
  }




  return { mutationFn, ...mutationOptions }
}

export type CreatePikudMutationResult = NonNullable<Awaited<ReturnType<typeof createPikud>>>
export type CreatePikudMutationBody = CreatePikudDto
export type CreatePikudMutationError = AxiosError<unknown>

export const useCreatePikud = <TError = AxiosError<unknown>,
  TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof createPikud>>, TError, { data: CreatePikudDto }, TContext>, axios?: AxiosRequestConfig }
  ): UseMutationResult<
    Awaited<ReturnType<typeof createPikud>>,
    TError,
    { data: CreatePikudDto },
    TContext
  > => {

  const mutationOptions = getCreatePikudMutationOptions(options);

  return useMutation(mutationOptions);
}
export const listPikuds = (
  createPikudDto: CreatePikudDto[], options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {


  return axios.default.get(
    `/pikud`, options
  );
}




export const getListPikudsQueryKey = (createPikudDto?: CreatePikudDto[],) => {
  return [
    `/pikud`, createPikudDto
  ] as const;
}


export const getListPikudsQueryOptions = <TData = Awaited<ReturnType<typeof listPikuds>>, TError = AxiosError<unknown>>(createPikudDto: CreatePikudDto[], options?: { query?: UseQueryOptions<Awaited<ReturnType<typeof listPikuds>>, TError, TData>, axios?: AxiosRequestConfig }
) => {

  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListPikudsQueryKey(createPikudDto);



  const queryFn: QueryFunction<Awaited<ReturnType<typeof listPikuds>>> = ({ signal }) => listPikuds(createPikudDto, { signal, ...axiosOptions });





  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof listPikuds>>, TError, TData> & { queryKey: QueryKey }
}

export type ListPikudsQueryResult = NonNullable<Awaited<ReturnType<typeof listPikuds>>>
export type ListPikudsQueryError = AxiosError<unknown>



export function useListPikuds<TData = Awaited<ReturnType<typeof listPikuds>>, TError = AxiosError<unknown>>(
  createPikudDto: CreatePikudDto[], options?: { query?: UseQueryOptions<Awaited<ReturnType<typeof listPikuds>>, TError, TData>, axios?: AxiosRequestConfig }

): UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListPikudsQueryOptions(createPikudDto, options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}



export const pikudController = (
  id: number, options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {


  return axios.default.delete(
    `/pikud/${id}`, options
  );
}



export const getPikudControllerMutationOptions = <TError = AxiosError<unknown>,
  TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof pikudController>>, TError, { id: number }, TContext>, axios?: AxiosRequestConfig }
  ): UseMutationOptions<Awaited<ReturnType<typeof pikudController>>, TError, { id: number }, TContext> => {

  const mutationKey = ['pikudController'];
  const { mutation: mutationOptions, axios: axiosOptions } = options ?
    options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey, }, axios: undefined };




  const mutationFn: MutationFunction<Awaited<ReturnType<typeof pikudController>>, { id: number }> = (props) => {
    const { id } = props ?? {};

    return pikudController(id, axiosOptions)
  }




  return { mutationFn, ...mutationOptions }
}

export type PikudControllerMutationResult = NonNullable<Awaited<ReturnType<typeof pikudController>>>

export type PikudControllerMutationError = AxiosError<unknown>

export const usePikudController = <TError = AxiosError<unknown>,
  TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof pikudController>>, TError, { id: number }, TContext>, axios?: AxiosRequestConfig }
  ): UseMutationResult<
    Awaited<ReturnType<typeof pikudController>>,
    TError,
    { id: number },
    TContext
  > => {

  const mutationOptions = getPikudControllerMutationOptions(options);

  return useMutation(mutationOptions);
}
